/*$File_version=ms4.3.0.48$*/
/*$file name : spyadrpmnspcrauthcrdoc.sql*/  
/*$version   : 4.0.0.022		*/  
/*==================================================  
   stored procedure : spyadrpmnspcrauthcrdoc  
   method           : spyadrpmnmtcrauthcrdoc   
   author           : Veera  
   created on       : 26 mar 2002 19:18:10:487  
   created at       : s4353  
   generated by     : fpuser  
    Modifed by 	    : Chitra S
    Modified date   : 11/08/03 	    
*/
/********************************************************************************/
/* modified by  : B. Uma Maheswari	                                        */
/* date         : 17/2/2004                                                     */
/* description  : German Bank Implementation                                    */
/*   Modified by      : Vikas 
   date             : 02/03/2004                                                    
   description      : For GBank Development*/
/*   Modified by      : Jinesh K
   date             : 17-Apr-2004
   description      : SPYDMS41ACTST_000109	*/
/*   Modified by      : Jinesh K
   date             : 17-Apr-2004 ,19-Apr-2004,20-Apr-2004
   description      : SPYDMS41ACTST_000112	*/
/*   Modified by      : Jinesh K
   date             : 20-Apr-2004,21-Apr-2004,26-Apr-2004
   description      : SPYDMS41ACTST_000111,SPYDMS41ACTST_000110	*/
/*   Modified by      : Jinesh K
   date             : 20-Apr-2004,21-Apr-2004,26-Apr-2004
   description      : SPYDMS41ACTST_000143,144,145		*/
/*   Modified by      : Jinesh K
   date             : 27-Apr-2004,28-Apr-2004
   description      : SPYDMS41ACTST_000150			*/
/*Modified by      : Jinesh K
   date             : 13-May-2004
   description      : SPYDMS41UTST_000013			*/

/********************************************************************************/
/********************************************************************************/
/* modified by  : Rajesh R                                                      */
/* date         : 29-Apr-2004                                                   */
/* description  : SPYDMS41UTST_000009- DMS4.1 MERGING                           */
/* modified by  : Jinesh K                                                      */
/* date         : 28-May-2004                                                   */
/* description  : SPYDMS41SYTST_000015			                         */
/********************************************************************************/
/*Modified by		Date				Remarks		*/
/*S.Shankaranand		5/9/04				For German Transaction		*/
/******************************************************************************************/
/* modified by  : Jinesh K                                              		  */
/* date         : 29-Jun-2004                                         	          	  */
/* description  : SPYDMS41SYTST_000015				                          */
/*******************************************************************************************/
/*	Modified by	:	S.balaji						   */
/*	Modified On	:	24/9/2004						   */
/*	Purpose		:	SPYFIN41CT_000011					   */
/*******************************************************************************************/
/*	Modified by	:		Modified On		:		Purpose							*/
/*	S.balaji			19/11/2004			SPYFIN41CT_000015	   				*/
/*	Nagarajan G 		19/01/2005			SPYFIN41CT_000017	   				*/ 
/*  A.R.R.balaji        28/12/2005          AEC_SPY_BASEFIXES_000543			*/
/*	S.balaji			21/02/2006			SPYBGL_000019						*/
/*	S.balaji			24/02/2006			SPYBGL_000019						*/
/*	S.balaji			21/03/2006			SPYDMS412AT_000122					*/
/*  S.balaji			06/05/2005			SPYDMS412AT_000181  				*/
/* Porselvi.J			30-01-2007			SPYDMS412AT_000299					*/
/* Porselvi.J			13-02-2007			SPYDMS412AT_000324					*/
/* Porselvi.J			19-02-2007			SPYDMS412AT_000343					*/
/* Rajeswari.C			13-04-2007			SPYDMS412AT_000368					*/
/* Aparna M.			22/05/2007			SPYDMS412AT_000452					*/
/* Porselvi.J			28-07-2007			SPYDMS412AT_000483					*/
/* Aparna M.			23/08/2007			SRDMS412AT_000079					*/
/* Karthi k.k			26/10/2007			SPYDMS412AT_000541					*/
/* Porselvi.J			12-12-2007			DMS412AT_SPY_00001					*/
/* Aparna M.			17/04/2008			ES_spy_00003						*/
/* Aparna M.			05/06/2008			8H123-1_spy_00001					*/
/* Vijayan.J			16/06/2008			DMS412AT_spy_00026					*/
/* Vijayan.J			02/07/2008			ES_spy_00021						*/
/* Uma Maheswari		20th Nov 2008		ES_spy_00061						*/
/* Thiruvengadam.S		06/03/2009			ES_spy_00088						*/
/* Esther J				24/03/2009			ES_bnkdef_00013 					*/
/* Uma Maheswari		29th May 2009		ES_spy_00124						*/
/* Uma Maheswari		01st June 2009		ES_spy_00124						*/
/* K.S.Karthik Prabhu	06/07/2009			ES_SPY_00112						*/
/* Vairamani C			30 Oct 2009			ES_SPY_00176						*/
/* Angelin.R			05/01/2010			9H123-1_spy_00027					*/
/* R.Mohandas			19/01/2010			9H123-1_SPY_00026					*/
/* R.Mohandas			22/01/2010			9H123-1_SPY_00030(9H123-1_SPY_00026)*/
/* Samuel G				19/12/2010			ES_spy_00308						*/
/* Deepika V			9/8/2011			ES_spy_00397:[11H103_spy_00010:11H103_spy_00038]*/
/* Nithya P				10/5/2012			ES_spy_00542		*/
/* Nithya P				07/09/2013			ES_spy_00712		*/
/* Divyalekaa			10/03/2014			13H120_GENERAL_00034 */
/*Harsha oram           24/03/2014          ES_sdin_01018                          */
/* Kavitha R			23/03/2015			14H109_TCAL_00039					*/
/* Kavitha R			23/04/2015			14H109_spy_00035					*/
/* Kavitha R			24/04/2015			14H109_spy_00039					*/
/* Kavitha R			24/04/2015			14H109_spy_00038					*/
/*Anusha R				18/08/2015			ES_spy_01238				*/
/*Kavitha R				18/02/2016		14H109_mcam_00001*/
/*Balaji C				22/04/2016			ES_spy_01118						*/
/*Balaji C				05/03/2016			ES_spy_01415						*/
/*Vishweswaran			02/06/2016			14H109_general_00137				*/
/* Anusha p				21/07/2016			14H109_General_00138*/
/* Aditya S				17/11/2016			ES_spy_01568						*/
/* Sweety Ninave		16/08/2017			CAMPSS-120							*/
/* Aditya S				24/01/2018			RIL-241								*/
/* Divyalekaa			08/07/2018			EPE-7271							*/
/*Sweety Ninave			25-02-2019			EBS-2667							*/
/*Priyadarshini R       03/05/2019          EPE-13408*/
/*Aditya S				29/10/2020			CKBW2-1612*/
/* Abinaya V			08-06-2022			EPE-46106		*/
/*Kiran Kumar Minuku	07/09/2022			EPE-48054							*/
/* Preethi Venkatraman			14/12/2023			EPE-70571					*/
/*Umar Mohammad			11-01-2024			EPE-70587			*/
/*Saranraj C            21/03/2022          RCEPL-635       */
/*Kavitha R				25/05/2024			EPE-79558:EPE-81543*/
/*	Amirtha P.			25.11.2024			RITSL/PJRMC-980	*/
/*	yokesh.k			12/04/2025			RITSL/PJRMC-1535	*/
/********************************************************************************/
-- grant exec on spyadrpmnspcrauthcrdoc to public
create       procedure spyadrpmnspcrauthcrdoc  
	@applieddiscountml			fin_amount,  
	@appliedpenaltyml     		fin_amount,  
	@creditdocamount     		fin_amount,  
	@creditdoccurrency   		fin_currencycode,  
	@creditdocnumber     		fin_documentnumber,  
	@ctxt_language      		fin_ctxt_language,  
	@ctxt_ouinstance        	fin_ctxt_ouinstance,  
	@ctxt_service           	fin_ctxt_service,  
	@ctxt_user       			fin_ctxt_user,  
	@doctype       				fin_documenttype,  
	@duedate       				fin_date,  
	@guid        				fin_guid,  
	@modeflag       			fin_modeflag,  
	@ouinstidpo       			fin_ouinstid,  
	@paybatchnumber         	fin_documentnumber,  
	@paymodeml       			fin_paymode,  
	@paytosupplier      		fin_suppliercode,  
	@paytosuppliername      	fin_name, 
	@presentoutstandingamount  	fin_amount,  
	@priority     				fin_priority,  
	@proposeddiscountml     	fin_amount,  
	@proposedpenaltyml      	fin_amount,  
	@spaytrannetamount      	fin_amount,  
	/* Code added and commented for ES_sdin_01018  starts here */
	--@supplierdocumentnumberml  	fin_documentnumber,
	@supplierdocumentnumberml  	fin_description,
	/* Code added and commented for ES_sdin_01018  ends here */   
	@supplierml       			fin_suppliercode,  
	@suppliernameml      		fin_name,  
	@termnumberhdnhdr     		fin_termnumber,  
	@tranamount       			fin_amount,  
	@transactiontype     		fin_transactiontype,  
	@errorno      				fin_errorno,  
	@fprowno       				fin_rowno,  
	@placeholder1      			fin_placeholder,  
	@placeholder2      			fin_placeholder,  
	@placeholder3      			fin_placeholder,  
	@placeholder4      			fin_placeholder,  
	@successflag      			fin_successflag,
	@crdocou					fin_ouinstname,
	@lcnumberml					fin_lcnumber , --code added by Esther J for the defect ES_bnkdef_00013 ; LC	
	@refid						fin_refid,
	@FinanceBookML				fin_financebookid,--Code Added by K.S.Karthik Prabhu for the DTS Id: ES_SPY_00112
	@SupplierInvoiceDateML		fin_date, --Code Added by Angelin.R for the Bug id : 9H123-1_spy_00027
	/*Code Added by samuel for bud id ES_spy_00308*/
	@exrate                     fin_exchangerate, --Input  
	@payamount                  fin_amount, --Input/Output 
	@baseamount                 fin_amount, --Input/Output 
	/*Code Added by samuel for bud id ES_spy_00308*/
	--14H109_TCAL_00039
	@appliedwhtam             	fin_amount, --Input 
	@proposwhtam              	fin_amount, --Input 
	--14H109_TCAL_00039
	@proj_refdoc				udd_unitcode, --ES_spy_01238
	@ForwardContractNo          fin_documentno,  --EPE-48054
	@m_errorid      			fin_int output 
as  
BEGIN
	-- nocount should be switched on to prevent phantom rows
	SET NOCOUNT ON
	-- @m_errorid should be 0 to indicate success
	SELECT @m_errorid = 0 
	
	--BEGIN of Standard code for getting precision type  
	DECLARE @pqty_tmp    fin_int,
	        @pamt_tmp    fin_int,
	        @prate_tmp   fin_int,
	        @perate_tmp  fin_int,
	        @phigh_tmp   fin_int,
	        @pmed_tmp    fin_int,
	        @plow_tmp    fin_int  
	
	EXEC fin_sp_precisiontype_rtr @pqty_tmp OUTPUT,
			@pamt_tmp OUTPUT,
			@prate_tmp OUTPUT,
			@perate_tmp OUTPUT,
			@phigh_tmp OUTPUT,
			@pmed_tmp OUTPUT,
			@plow_tmp OUTPUT
	--END of Standard code for getting precision type  
	
	SELECT @creditdoccurrency 				= LTRIM(RTRIM(@creditdoccurrency))
	SELECT @creditdocnumber 				= LTRIM(RTRIM(@creditdocnumber))
	SELECT @ctxt_service 					= LTRIM(RTRIM(@ctxt_service))
	SELECT @ctxt_user 						= LTRIM(RTRIM(@ctxt_user))
	SELECT @doctype 						= LTRIM(RTRIM(@doctype))
	SELECT @duedate 						= LTRIM(RTRIM(@duedate))
	SELECT @guid 							= LTRIM(RTRIM(@guid))
	SELECT @modeflag 						= LTRIM(RTRIM(@modeflag))
	SELECT @paybatchnumber 					= LTRIM(RTRIM(@paybatchnumber))
	SELECT @paymodeml 						= LTRIM(RTRIM(@paymodeml))
	SELECT @paytosupplier 					= LTRIM(RTRIM(@paytosupplier))
	SELECT @paytosuppliername 				= LTRIM(RTRIM(@paytosuppliername))
	SELECT @supplierdocumentnumberml 		= LTRIM(RTRIM(@supplierdocumentnumberml))
	SELECT @supplierml 						= LTRIM(RTRIM(@supplierml))
	SELECT @suppliernameml 					= LTRIM(RTRIM(@suppliernameml))
	SELECT @termnumberhdnhdr 				= LTRIM(RTRIM(@termnumberhdnhdr))
	SELECT @transactiontype 				= LTRIM(RTRIM(@transactiontype))
	SELECT @placeholder1 					= LTRIM(RTRIM(@placeholder1))
	SELECT @placeholder2 					= LTRIM(RTRIM(@placeholder2))
	SELECT @placeholder3 					= LTRIM(RTRIM(@placeholder3))
	SELECT @placeholder4 					= LTRIM(RTRIM(@placeholder4))
	SELECT @crdocou 						= LTRIM(RTRIM(@crdocou))
	SELECT @SupplierInvoiceDateML 			= LTRIM(RTRIM(@SupplierInvoiceDateML)) --Code Added by Angelin.R for the Bug id : 9H123-1_spy_00027
	/*Code Added by samuel for bud id ES_spy_00308*/
	SELECT @exrate							= @exrate	
	SELECT @payamount						= @payamount 
	SELECT @baseamount						= @baseamount
	/*Code Added by samuel for bud id ES_spy_00308*/
	SELECT @proj_refdoc 					= LTRIM(RTRIM(@proj_refdoc)) --ES_spy_01238
	Select @ForwardContractNo                = ltrim(rtrim(@ForwardContractNo))--EPE-48054	
	
	IF @applieddiscountml = -915
	    SELECT @applieddiscountml = NULL
	
	IF @appliedpenaltyml = -915
	    SELECT @appliedpenaltyml = NULL
	
	IF @creditdocamount = -915
	    SELECT @creditdocamount = NULL
	
	IF @creditdoccurrency = '~#~'
	    SELECT @creditdoccurrency = NULL
	
	IF @creditdocnumber = '~#~'
	    SELECT @creditdocnumber = NULL
	
	IF @ctxt_language = -915
	    SELECT @ctxt_language = NULL
	
	IF @ctxt_ouinstance = -915
	    SELECT @ctxt_ouinstance = NULL
	
	IF @ctxt_service = '~#~'
	    SELECT @ctxt_service = NULL
	
	IF @ctxt_user = '~#~'
	    SELECT @ctxt_user = NULL
	
	IF @doctype = '~#~'
	    SELECT @doctype = NULL
	
	IF @duedate = '1900-01-01'
	    SELECT @duedate = NULL
	
	IF @guid = '~#~'
	    SELECT @guid = NULL
	
	IF @modeflag = '~#~'
	    SELECT @modeflag = NULL
	
	IF @ouinstidpo = -915
	    SELECT @ouinstidpo = NULL
	
	IF @paybatchnumber = '~#~'
	    SELECT @paybatchnumber = NULL
	
	IF @paymodeml = '~#~'
	    SELECT @paymodeml = NULL
	
	IF @paytosupplier = '~#~'
	    SELECT @paytosupplier = NULL
	
	IF @paytosuppliername = '~#~'
	    SELECT @paytosuppliername = NULL
	
	IF @presentoutstandingamount = -915
	    SELECT @presentoutstandingamount = NULL
	
	IF @proposeddiscountml = -915
	    SELECT @proposeddiscountml = NULL
	
	IF @proposedpenaltyml = -915
	    SELECT @proposedpenaltyml = NULL
	
	IF @spaytrannetamount = -915
	 SELECT @spaytrannetamount = NULL
	
	IF @supplierdocumentnumberml = '~#~'
	    SELECT @supplierdocumentnumberml = NULL
	
	IF @supplierml = '~#~'
	    SELECT @supplierml = NULL
	
	IF @suppliernameml = '~#~'
	    SELECT @suppliernameml = NULL
	
	IF @termnumberhdnhdr = '~#~'
	    SELECT @termnumberhdnhdr = NULL
	
	IF @tranamount = -915
	    SELECT @tranamount = NULL
	
	IF @transactiontype = '~#~'
	    SELECT @transactiontype = NULL
	
	IF @errorno = -915
	    SELECT @errorno = NULL
	
	IF @fprowno = -915
	    SELECT @fprowno = NULL
	
	IF @placeholder1 = '~#~'
	    SELECT @placeholder1 = NULL
	
	IF @placeholder2 = '~#~'
	    SELECT @placeholder2 = NULL
	
	IF @placeholder3 = '~#~'
	 SELECT @placeholder3 = NULL
	
	IF @placeholder4 = '~#~'
	    SELECT @placeholder4 = NULL
	
	IF @successflag = -915
	    SELECT @successflag = NULL
	
	IF @crdocou = '~#~'
	    SELECT @crdocou = NULL
	
	SELECT @lcnumberml = LTRIM(RTRIM(@lcnumberml)) --code added by Esther J for the defect ES_bnkdef_00013 ; LC	
	IF @lcnumberml = '~#~'
	    SELECT @lcnumberml = NULL
	
	SELECT @refid = LTRIM(RTRIM(@refid)) 
	IF @refid = '~#~'
	    SELECT @refid = NULL

	/*Code Added by Angelin.R for the Bug id : 9H123-1_spy_00027 Starts here*/
	IF @SupplierInvoiceDateML = '1900-01-01'
	    SELECT @SupplierInvoiceDateML = NULL
	/*Code Added by Angelin.R for the Bug id : 9H123-1_spy_00027 Ends here*/
	
	/*Code Added by samuel for bud id ES_spy_00308*/
	IF @exrate = -915
		Select @exrate = null  
		
	IF @payamount = -915
		Select @payamount = null  

	IF @baseamount = -915
		Select @baseamount = null  
	/*Code Added by samuel for bud id ES_spy_00308*/

--14H109_TCAL_00039	
	if @appliedwhtam  = -915
		select @appliedwhtam = null
	
	if @proposwhtam  = -915
		select @proposwhtam = null	
--14H109_TCAL_00039		

IF @proj_refdoc = '~#~'--ES_spy_01238
	    SELECT @proj_refdoc = NULL--ES_spy_01238

	IF @ForwardContractNo = '~#~' 
		Select @ForwardContractNo = null --EPE-48054
		
	
	DECLARE @paycur              fin_currencycode,
	        @paycurml            fin_currencycode,
	        @paycur_erate        fin_exchangerate,
	        @basecur_erate       fin_exchangerate,
	        @parbasecur_erate    fin_exchangerate,
	        @payamount1           fin_amount,
	        @compcode            fin_companycode,
	        @requestdate         fin_date,
	        @allowmodisc         fin_paramcode,
	        @paymode_tmp         fin_paymode,
	        @paymode_hdr         fin_paymode,
	        @pay_tmp             fin_paymode,
	        @paytype_tmp         fin_route,
	        @paybatchnumber_tmp  fin_documentnumber,
	        @paymethodml1_tmp    fin_route,
	       -- @crdocchk fin_paramcode,
	        @date_tmp            fin_date,
	        @bankcash_tmp        fin_bankcashcode,
	       -- @guid_tmp            fin_guid,
	       -- @supdrbla_tmp        fin_amount,
	        @paychargeby_tmp     fin_paramcode,
	        @elect_payment       fin_flag,
	        @cr_doc_fb_id        fin_financebookid,
	        @errmsg              fin_desc255 -- Porselvi.J - SPYDMS412AT_000324
	        ,
	        @acct_type_tmp       fin_flag --Aparna M. -SRDMS412AT_000079
	        ,
	        @paydate             fin_date ,--Aparna M.	8H123-1_spy_00001	
			@ppsmulticurr_flag	 fin_flag --Code Added by samuel for bug id : es_spy_00308
		    ,@allfedatedsupppay  fin_paramcode
			,@suppou_tmp				fin_ctxt_ouinstance  --EBS-2667
	
	Select @suppou_tmp = dbo.get_cim_ou(@ctxt_ouinstance,'SPY','SUPP') --EBS-2667

	/* Code Added by samuel for bug id : es_spy_00308 starts here */
	select	@ppsmulticurr_flag = FLAG_YES_NO
	from	PPS_FEATURE_LIST(nolock)
	Where	FEATURE_ID		=	'SYNR_FID_0001'
	and		COMPONENT_NAME	=	'SPY' 
	/* Code Added by samuel for bug id : es_spy_00308 ends here */
--14H109_mcam_00001
	declare	@called_from	fin_desc40
	
	select 	@called_from	=	'NONE'
	if exists(select 1 from mca_sel_doc_tmp(nolock)
				where  hdn_guid = @guid)
	begin
		select @called_from = 'MCAM'
		update	mca_sel_doc_tmp
		set		error_id	= 1
		where	hdn_guid = @guid		
	end		
--14H109_mcam_00001	
	/* code added for the defect id EPE-79558:EPE-81543 begins here */
	if exists(	select	'X'
					from	fb_tmp(nolock)
					where   rsih_guid_tmp = @guid
					AND		pps_flag	in	('APP','REJ')
				)
	begin
		select	@called_from	= 'MOB_APPR'
	end
	/* code added for the defect id EPE-79558:EPE-81543 ends here */	
 	IF @fprowno IS NULL
	--or @fprowno = 0--9H123-1_SPY_00030(9H123-1_SPY_00026)
	BEGIN
 	   -- SELECT @fprowno = 1--9H123-1_SPY_00030(9H123-1_SPY_00026)
		  SELECT @fprowno = 0
 	END
	/*Code added for ITS ID : ES_spy_01415 starts*/
	if	@ouinstidpo	is	null
	begin
		SELECT	@ouinstidpo	=	ou_id
		FROM	emod_ou_vw(NOLOCK)
		WHERE	ouinstname	=	@Crdocou
	end


	
	if	isnull(@transactiontype,'')	=	''
	begin
		select	@transactiontype	=	parameter_code
		from	fin_quick_code_met(NOLOCK)
		where	component_id		= 'SPY'
		and		parameter_type		= 'TRNTP'
		and		parameter_category	= 'TRANTYPE'
		and		language_id			= @ctxt_language
		and		parameter_text		= @doctype
	end
	
	--select '@doctype',@doctype,@transactiontype

	if	isnull(@termnumberhdnhdr,'')	=	''
	begin
		select	top 1 @termnumberhdnhdr	=	term_no
		from   si_doc_balance(nolock)
		where	tran_no		=	@creditdocnumber
		and		tran_ou		=	@ouinstidpo
		and		tran_type	=	@transactiontype
		and		base_outstanding_amt	>	0
		and		isnull(due_date,'1900-01-01')	=	isnull(@duedate,isnull(due_date,'1900-01-01'))
		order by due_date asc
	end
	/*Code added for ITS ID : ES_spy_01415 ends*/	
	
	--Added for DTS Id:9H123-1_SPY_00030(9H123-1_SPY_00026) begins
	IF @modeflag = 'D'
	BEGIN
	--14H109_spy_00038
		delete from  spy_paybatch_dtl_tmp 
		where 	guid			= @guid
		and		cr_doc_no		= @creditdocnumber
		and		cr_doc_ou		= @ouinstidpo
		and		term_no			= @termnumberhdnhdr
		and		cr_doc_type		= @transactiontype
	--14H109_spy_00038	

	    SELECT @errorno 'ERRORNO',
			   @fprowno 'FPROWNO',
	           @successflag 'SUCCESSFLAG'
	    RETURN
	END
	
	SELECT @fprowno = @fprowno + 1 
	--Added for DTS Id:9H123-1_SPY_00030(9H123-1_SPY_00026) ends

		--EPE-70587 code begins
	if (@modeflag in ( 'Z','Y') and @ctxt_service in ( 'spyadrpmnsrcrauth','spyadrpmnsrcreate')) 
	Begin

	SELECT @compcode 	= company_code
	FROM   emod_ou_vw(NOLOCK)
	WHERE  ou_id 		= @ctxt_ouinstance
	Declare @pps_flag fin_flag,
			@flag	  fin_flag,
			@docflag  fin_flag

	select @pps_flag = FLAG_YES_NO
	From pps_finance_feature_list with(nolock)
	where FEATURE_ID = 'PPS_TCAL_00004'
	and company_code = @compcode

	If @pps_flag is null
	begin
	Select @pps_flag = FLAG_YES_NO
	From pps_finance_feature_list with(nolock)
	where FEATURE_ID = 'PPS_TCAL_00004'
	and company_code is null
	end
		

if @pps_flag = 'Yes'
			Begin
				select @flag = upper(FLAG_YES_NO)
				From pps_finance_feature_list with(nolock)
				where FEATURE_ID = 'PPS_TCAL_00008'
				and company_code = @compcode

				If @flag is null
				begin
				Select @flag = upper(FLAG_YES_NO)
				From pps_finance_feature_list with(nolock)
				where FEATURE_ID = 'PPS_TCAL_00008'
				and company_code is null
				end

			 If not exists(Select 'X' from tstl_tran_hdr(nolock)
			 			  where tran_no			= @creditdocnumber
			 			  and   tran_ou			= @ouinstidpo
			 			  and	tran_type		= @transactiontype
			 			  and	tax_type		= 'GST'
			 			  and	tax_community	= 'INDIA'
			 			  and	recon_flag		= 'R' )  
						  and @flag = 'GSTR2A' and @transactiontype not in ('PM_ORPI','PM_DPI')
			 			  Begin
			 					Select @docflag  = 'Y'
			 			  End

			 If not exists(Select 'X' from tstl_tran_hdr(nolock)
			 			  where tran_no				= @creditdocnumber
			 			  and   tran_ou				= @ouinstidpo
			 			  and	tran_type			= @transactiontype
			 			  and	tax_type			= 'GST'
			 			  and	tax_community		= 'INDIA'
			 			  and	recon_flag_gstr2b	= 'R' )  
						  and @flag = 'GSTR2B' and @transactiontype not in ('PM_ORPI','PM_DPI')
			 			  Begin
			 					Select @docflag  = 'Y'
			 			  End

				if @docflag = 'Y'
				Begin
				  if exists(Select '*' from TCAL_TRAN_HDR(nolock)
							where tran_no			= @creditdocnumber
							and   tran_ou			= @ouinstidpo
							and	tran_type		= @transactiontype
							and	tax_type		= 'GST'
							and	tax_community	= 'INDIA'
							 )
							Begin

											  Declare @paybatch_no fin_documentno,
													  @sum		    fin_amount,
													  @total_amt	fin_amount,
													  @gst_amt		fin_amount,
													  @blnc_amt		numeric(18,2),
													  @prevtrn_amt	fin_amount
											  Select @sum = 0

											  if exists( Select '*' from spy_paybatch_dtl(nolock)
														where cr_doc_no   = @creditdocnumber
														and	cr_doc_ou   = @ouinstidpo
														and   cr_doc_type = @transactiontype
														) 

											  begin 
											  Declare amtsum cursor for 
											  Select distinct paybatch_no 
											  from spy_paybatch_dtl(nolock)
											  where cr_doc_no   = @creditdocnumber
											  and	cr_doc_ou   = @ouinstidpo
											  and   cr_doc_type = @transactiontype

											  open amtsum
											  fetch next from amtsum into @paybatch_no
											   while @@fetch_status = 0   
											   begin
														Select @sum = @sum+ d.tran_amount
														from  spy_paybatch_dtl d(nolock),
															  spy_paybatch_hdr h(nolock)
														where d.paybatch_no = h.paybatch_no
														and   d.ou_id		= h.ou_id
														and	  cr_doc_no     = @creditdocnumber
														and	  cr_doc_ou     = @ouinstidpo
														and   cr_doc_type   = @transactiontype
														and	  d.paybatch_no = @paybatch_no
														and	  d.ou_id		= @ctxt_ouinstance
														and   h.status in ('A','F','DF','RT')

											   fetch next from amtsum into @paybatch_no
											   End
											   close amtsum  
											   deallocate amtsum
											   end  											  
											  if exists ( Select '*' from spy_paybatch_dtl_tmp(nolock)
																			where	cr_doc_no   = @creditdocnumber
																			and		cr_doc_ou   = @ouinstidpo
																			and		cr_doc_type = @transactiontype
																			and		guid		= @guid
																			and     rowno is not null
																			)
											   begin
											   Declare amtsum cursor for 
											   Select distinct paybatch_no 
											   from spy_paybatch_dtl_tmp(nolock)
											   where cr_doc_no   = @creditdocnumber
											   and	 cr_doc_ou   = @ouinstidpo
											   and   cr_doc_type = @transactiontype
											   and	 guid		 = @guid
											   and   rowno is not null

											   open amtsum
											   fetch next from amtsum into @paybatch_no

											   while @@fetch_status = 0   
											   begin
														Select @sum = @sum+ d.tran_amount
														from  spy_paybatch_dtl_tmp d(nolock)	  
														where cr_doc_no   = @creditdocnumber
											            and	  cr_doc_ou   = @ouinstidpo
														and   guid		  = @guid
														and   rowno is not null

											   fetch next from amtsum into @paybatch_no
											   End
											   close amtsum  
											   deallocate amtsum
											   End  		
											  End
							
								Select  @total_amt = tran_amount
								from    si_doc_hdr(nolock)
								where	tran_no   = @creditdocnumber
								and     tran_ou   = @ouinstidpo
								and		tran_type = @transactiontype

								
								Select  @gst_amt = comp_tax_amt
								from    tcal_tran_hdr(nolock)
								where	tran_no   = @creditdocnumber
								and     tran_ou   = @ouinstidpo
								and		tran_type = @transactiontype
								and     tax_type  = 'GST'
								and     tax_community = 'INDIA'
						

								Select @blnc_amt = @total_amt - @gst_amt - @sum +isnull(@prevtrn_amt,0)
								
								if @ctxt_user = 'amtuser'
								begin
									Select @blnc_amt '@blnc_amt',@total_amt '@total_amt', @tranamount '@tranamount' ,@gst_amt'@gstamount',@sum 'sumused',@prevtrn_amt'@prevtrn_amt'
								end
								

								if @tranamount > @blnc_amt
								Begin
									Select @blnc_amt   = @tranamount - @blnc_amt		-- To find balance post removal of incoming tran amount							
									Select @blnc_amt   = (round(@tranamount,2)) - (round(@blnc_amt,2))  --max amount available for the usr to enter as tran amount
									exec fin_german_raiserror_sp 'SPY',@ctxt_language,400,@creditdocnumber,@fprowno,@flag,@blnc_amt
									SELECT @m_errorid = 400
									return
								End					 
							 End
							
			End
	End
--EPE-70587 code ends

	IF @modeflag NOT IN ('X', 'Y', 'Z')
	BEGIN
		/*Code added for 13H120_GENERAL_00034 begins here*/
		if exists (	select	'x'
					from	FB_TMP (nolock)
					where	rsih_guid_tmp			= @guid
					and		rsih_fb_tmp in ('ICT_MPAY_Ser_Sav','ICT_MPAY_Ser_Aut')
				  )
		begin	
			return
		end
		/*Code added for 13H120_GENERAL_00034 ends here*/		

	--14H109_spy_00038
		delete from  spy_paybatch_dtl_tmp 
		where 	guid			= @guid
		and		cr_doc_no		= @creditdocnumber
		and		cr_doc_ou		= @ouinstidpo
		and		term_no			= @termnumberhdnhdr
		and		cr_doc_type		= @transactiontype
	--14H109_spy_00038	
		
	    SELECT @errorno 'ERRORNO',
			   @fprowno 'FPROWNO',
	           @successflag 'SUCCESSFLAG'
	    RETURN
	END

	/*SELECT @fprowno = 2*/-- Code commented by R.Mohandas For the DTS ID:9H123-1_SPY_00030(9H123-1_SPY_00026)

	SELECT @date_tmp = CONVERT(NVARCHAR(40), dbo.RES_Getdate(@ctxt_ouinstance), 120) --Aparna M.	8H123-1_spy_00001	
	
	SELECT @compcode 	= company_code
	FROM   emod_ou_vw(NOLOCK)
	WHERE  ou_id 		= @ctxt_ouinstance
	

	IF @tranamount IS NULL
	BEGIN
	    -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8452
		  return
		end
	-----EPE-13408  ends---------
	else
	begin 
	    --raiserror('Enter Tran Amount',16,1) 
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	         '',
	         'SPY',
	         452,
	         @m_errorid OUTPUT
	    
	    RETURN
		end
	END  
	
	IF @tranamount <= 0
	BEGIN
	 -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8630
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    -- raiserror('Tran Amount should be greater than zero',16,1)  
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	         '',
	   'SPY',
	         630,
	 @m_errorid OUTPUT
	    
	    RETURN
    end
	END  
	
--select 'crdoc_sp',@tranamount,@presentoutstandingamount
	
	IF @tranamount > @presentoutstandingamount
	BEGIN
	-----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8631
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    --raiserror('Transaction Amount should be less than or equal to outstanding amount',16,1) 
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	         '',
	         'SPY',
	         631,
	         @m_errorid OUTPUT
	    
	    RETURN
   end
	END  
	
	IF ISNULL(@applieddiscountml, 0) <> 0
	AND ISNULL(@appliedpenaltyml, 0) <> 0
	BEGIN
	  -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8380
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    -- raiserror('Both discount and Penalty should not be given',16,1) 380 
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	         '',
	         'SPY',
	       380,
	         @m_errorid OUTPUT
	    
	    RETURN
   end
	END 
	
	IF ISNULL(@applieddiscountml, 0) >= @tranamount
	BEGIN
	   -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8395
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    --raiserror('Discount should be less than tran amount',16,1)  
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	         '',
	         'SPY',
	         395,
	         @m_errorid OUTPUT
	    
	    RETURN
  end
	END
	
	IF ISNULL(@appliedpenaltyml, 0) >= @tranamount
	BEGIN
	  -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8550
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    -- raiserror('Penalty should be less than tran amount',16,1)550  
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	    '',
	         'SPY',
	         550,
	         @m_errorid OUTPUT
	    
	    RETURN
    end
	END
	
--14H109_spy_00038
	if exists(select 1 from  spy_paybatch_dtl_tmp (nolock)
				where 	guid			= @guid
				and		cr_doc_no		= @creditdocnumber
				and		cr_doc_ou		= @ouinstidpo
				and		term_no			= @termnumberhdnhdr
				and		cr_doc_type		= @transactiontype
				and		tran_amount		<> @tranamount)
	begin 
	 -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 6000
		  return
		end
	-----EPE-13408  ends---------
		else 
		begin
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,6000
			return
		end
	end
	else
	begin
		delete from  spy_paybatch_dtl_tmp
		where 	guid			= @guid
		and		cr_doc_no		= @creditdocnumber
		and		cr_doc_ou		= @ouinstidpo
		and		term_no			= @termnumberhdnhdr
		and		cr_doc_type		= @transactiontype
	end			
--14H109_spy_00038	

	/*Code added for ITS ID : ES_spy_01118 starts*/
	exec	spy_cmn_mlinval
			@applieddiscountml,
			@appliedpenaltyml,
			@creditdocamount,
			@creditdoccurrency,
			@creditdocnumber,
			@ctxt_language,
			@ctxt_ouinstance,
			@ctxt_service,
			@ctxt_user,
			@doctype,
			@duedate,               
			@exrate,
			null,
			@guid,
			@modeflag,            
			@paybatchnumber,     
			null,
			@paydate,
			null,
			null,
			@paymodeml,
			@paytosupplier,
			@paytosuppliername,
			@presentoutstandingamount,
			@proposeddiscountml,
			@proposedpenaltyml,
			@requestdate,
			@spaytrannetamount,
			@supplierdocumentnumberml,
			@supplierml,
			@suppliernameml,
			@tranamount,
			@errorno,
			@fprowno,
			@placeholder1,
			@placeholder2,
			@placeholder3,
			@placeholder4,
			@successflag,
			@crdocou,
			null,
			null,	
			@FinanceBookML,
			@SupplierInvoiceDateML,
			@appliedwhtam,
			@proposwhtam,
			@termnumberhdnhdr out,
			@transactiontype out,
			@ouinstidpo out,
			@m_errorid	out

			if @ctxt_user = 'jobuser'
			begin
				if @m_errorid <> 0
				begin
				select @m_errorid = 1
				return
				end
			end
	/*Code added for ITS ID : ES_spy_01118 ends*/

	--select 'spyadrpmnspcrauthcrdoc',@guid
	--select * FROM   spy_paybatch_hdr_tmp(NOLOCK)
	--WHERE  guid  = @guid
	
	SELECT @paycur 				= pay_currency,
	       @paymode_hdr 		= pay_mode,
	       @requestdate 		= request_date,
	       @paytype_tmp 		= payment_route,
	 @paybatchnumber_tmp 	= paybatch_no,
	       @bankcash_tmp 		= bankcash,
	       @paychargeby_tmp 	= ISNULL(pay_chargeby, ''),	-- Porselvi.J - SPYDMS412AT_000343
	       @elect_payment 		= elect_payment,
	       @paycur_erate 		= basecur_erate,
	       @paydate 			= pay_date --Aparna M.	8H123-1_spy_00001
	FROM   spy_paybatch_hdr_tmp(NOLOCK)
	WHERE  guid 				= @guid

	
	-- Code added by Rajeswari.C for Bug id: SPYDMS412AT_000368 Starts	
	IF EXISTS
	(
		SELECT 	'X'
		FROM   	/*sdin_invoice_hdr*/si_doc_hdr(NOLOCK)--code modified by karthi k.k for the bug id SPYDMS412AT_000541
		WHERE  	tran_no 	= @creditdocnumber
		AND    	tran_ou 	= @ouinstidpo
		AND    	tran_date 	> @requestdate
		AND    tran_type 	= @transactiontype /* Code Added by Vairamani C for ES_SPY_00176 */
	   )
	BEGIN
	     -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 51
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    -- raiserror ('Request Date cannot be earlier than the reference document date',16,1)
	    EXEC fin_german_raiserror_sp 'SPY',
	         @ctxt_language,
	         1900030143, /*'51' ErrorId modified for RCEPL-635*/
	         @creditdocnumber, /*placeholder1 added for RCEPL-635*/
	         '',
	         '',
	         '',
	  '',
	         '',
	         '',
	         @errmsg OUTPUT
	  
	    RETURN
    end
	END
	-- Code added by Rajeswari.C for Bug id: SPYDMS412AT_000368 Ends
	
	IF @ctxt_service = 'spyedrpmnsrmodify'
	BEGIN
	    SELECT @paybatchnumber_tmp = @paybatchnumber
	END  
	
	IF @paycur IS NULL
	OR @paycur = ''
	BEGIN
	    SELECT @paycurml = @creditdoccurrency
	END
	ELSE
	BEGIN
	    SELECT @paycurml = @paycur
	END  

	IF @paymode_hdr IS NULL
	OR @paymode_hdr = ''
	BEGIN
		SELECT @paymode_tmp = paymode
		FROM   spy_paymode_vw(NOLOCK)
		WHERE  paymode_desc = @paymodeml  
		
		IF @paymode_tmp IS NULL ----code added by Esther J for the defect ES_bnkdef_00013 ; LC
		BEGIN
			SELECT 	@paymode_tmp 		= parameter_code
			FROM   	fin_quick_code_met(NOLOCK)
			WHERE  	component_id 		= 'BNKDEF'
			AND    	parameter_type 		= 'COMBO'
			AND    	parameter_category 	= 'PAYMODE'
			AND    	parameter_text 		= @paymodeml
			AND    	language_id 		= @ctxt_language
		END
		/*Code added for EPE-7271 begins here*/		
		if @paymode_tmp is null  
		begin
			select @paymode_tmp = @paymodeml--ecs
		end	
		/*Code added for EPE-7271 ends here*/		
	END
	ELSE
	BEGIN
		SELECT @paymode_tmp = @paymode_hdr
	END  
	
	IF (
	       (@paymode_hdr = '' OR @paymode_hdr IS NULL)
	   		AND @paymodeml = ''
	   )
	BEGIN
	      -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8593
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    --  raiserror 50000 'Select pay mode' 593 
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	         '',
	         'SPY',
	         593,
	         @m_errorid OUTPUT
	    
	    RETURN
    end
	END
	
	IF @paymode_hdr IS NULL
	AND @paymodeml IS NULL
	BEGIN
	  -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid =1900030098
		 return
		end
	-----EPE-13408  ends---------
	else
	begin
	    EXEC fin_sp_raise_error @creditdocnumber,
	         '',
	         '',
	         '',
	         'rr',
	         268,
	         @m_errorid OUTPUT
	    
	    RETURN
   end
	END
	
	/*code added by Esther J for the defect id ES_bnkdef_00013 starts*/
	DECLARE @lo     fin_loid
	DECLARE @today  fin_date
	
	SELECT @today = CONVERT(NVARCHAR(20), dbo.RES_Getdate(@ctxt_ouinstance), 110)
	
	SELECT 	@lo 		= lo_id
	FROM   	emod_lo_bu_ou_vw
	WHERE  	ou_id 		= @ctxt_ouinstance
	AND    	dbo.RES_Getdate(@ctxt_ouinstance) BETWEEN effective_from 
			AND ISNULL(effective_to, dbo.RES_Getdate(@ctxt_ouinstance))

	/*code added for the dtsid:9H123-1_SPY_00026 starts here*/
	if @paydate > @today
	begin	
		if EXISTS(
				select 'X' 
				from  supp_spmn_suplmain (nolock)
				where supp_spmn_supcode = @supplierml
				and	  supp_spmn_suptype = 'OT'
				and	  supp_spmn_loid	=  @lo
				
				 )
			begin
			 -----EPE-13408 starts---------
			if(@ctxt_user = 'jobuser')
			begin
			  select  @m_errorid = 1222
			  return
			end
			-----EPE-13408  ends---------
	else
	begin
				exec fin_german_raiserror_sp 'SPY',@ctxt_language,1222,@fprowno
				return
			end
     end
	end
	/*code added for the dtsid:9H123-1_SPY_00026 ends here*/
	
	IF @paymode_tmp = 'LC'
	BEGIN
	    IF @lcnumberml IS NULL
	    OR @refid IS NULL
	    BEGIN
		 -----EPE-13408 starts---------
			if(@ctxt_user = 'jobuser')
			begin
			  select  @m_errorid = 2010
			  return
			end
			-----EPE-13408  ends---------
	else
	begin
	        --2010	Paymode cannot be selected as Letter of Credit for the credit document %s as LC details are not available for the document. Modify paymode and Proceed
	        EXEC fin_german_raiserror_sp 'SPY',
	             @ctxt_language,
	             2010,
	             @creditdocnumber
	        
	        RETURN
     end
	    END

	    ELSE
	    BEGIN
			IF EXISTS 
			(
				SELECT 	'x'
				FROM   	lc_header(NOLOCK)
				WHERE  	LCH_LO 			= @lo
				AND    	LCH_LC_no 		= @lcnumberml
				AND    	LCH_Ref_Id 		= @refid
				AND    	LCH_LC_Exp_Date < @today
			)
			BEGIN
			   -----EPE-13408 starts---------
			if(@ctxt_user = 'jobuser')
			begin
			  select  @m_errorid = 2011
			  return
			end
			-----EPE-13408  ends---------
			else
			begin
				--2011	Paymode cannot be selected as Letter of Credit for the credit document %s as the LC has expired. Modify paymode and Proceed
				EXEC fin_german_raiserror_sp 'SPY',
					@ctxt_language,
					2011,
					@creditdocnumber
				
				RETURN
            end
			END
	    END
	END
	
	DECLARE @paymodeml_text fin_param_text
	
	SELECT 	@paymodeml_text 		= rcpt_pymt_mode
	FROM   	bnkdef_rcpt_pay_mode_vw(NOLOCK)
	WHERE  	rcpt_pymt_mode_code 	= @paymode_tmp
	AND    	language_id 			= @ctxt_language
	
	IF @paymodeml_text IS NULL
	BEGIN
		SELECT 	@paymodeml_text 	= parameter_text
		FROM   	fin_quick_code_met(NOLOCK)
		WHERE  	component_id 		= 'BNKDEF'
		AND    	parameter_type 		= 'COMBO'
		AND    	parameter_category 	= 'PAYMODE'
		AND    	parameter_code 		= @paymode_tmp
		AND    	language_id 		= @ctxt_language
	END
	
	IF @paymode_tmp <> 'LC'
	BEGIN
	    IF @lcnumberml IS NULL
	    BEGIN
			SELECT 	@lcnumberml = lcnumber,
					@refid 		= refid
			FROM   	sin_invoice_hdr(NOLOCK)
			WHERE  	tran_ou 	= @ouinstidpo
			AND    	tran_no 	= @creditdocnumber
			AND    	tran_type 	= 'PM_PI'
			/*code added for the dtsid:ES_spy_00397:[11H103_spy_00010:11H103_spy_00038] begins here*/
			SELECT 	@lcnumberml = lc_number,
	               	@refid 		= lc_refid
	        FROM   	sdin_invoice_hdr(NOLOCK)
	        WHERE  	tran_ou 	= @ouinstidpo
	        AND    	tran_no 	= @creditdocnumber
	        AND    	tran_type 	in ('PM_EV','PM_IV')
			/*code added for the dtsid:ES_spy_00397:[11H103_spy_00010:11H103_spy_00038] ends here*/

	    END
	    
	    IF @lcnumberml IS NOT NULL
	    OR @refid IS NOT NULL
	    BEGIN
			IF EXISTS 
			(
				SELECT 	'x'
				FROM   	lc_header(NOLOCK)
				WHERE  	LCH_LO 			= @lo
				AND    	LCH_LC_no 		= @lcnumberml
				AND    	LCH_Ref_Id 		= @refid
				AND    	LCH_LC_Class 	= 'US'
				AND    	LCH_LC_Exp_Date >= @today
			)
			BEGIN
			     -----EPE-13408 starts---------
			if(@ctxt_user = 'jobuser')
			begin
			  select  @m_errorid = 1900030102
			  return
			end
			-----EPE-13408  ends---------
			else
			begin
				--2012	Paymode cannot be selected as %s, as LC details exists for the Credit Document %s .Choose paymode as Letter of Credit and Proceed
				EXEC fin_german_raiserror_sp 'SPY',
					@ctxt_language,
					2012,
					@paymodeml_text,
					@creditdocnumber
				
				RETURN
            end
			END
	    END
	END
	
	/*code added by Esther J for the defect id ES_bnkdef_00013 ends*/
	
	--Code added by Aparna M. for 8H123-1_spy_00001 starts
	/*M4SPY010	Pay Date validity check - 2	
	If Pay Date is later than System Date, and if the Paymode is "Blank" in Payment information Group Box,  
	then Invoke Service from QCD, check the paymodes of the documents selected in the Multiline. If the Paymode 
	for any one of the document is other than the paymode available in the metadata as Pay mode for Post Dated 
	Instruments then display error. */
	
	--code for Def.Id 14H109_general_00137 starts here
	
	select @allfedatedsupppay	= parameter_code				
	from  cps_processparam_sys (nolock)
	where company_code			= @compcode
	AND	  parameter_type 		= 'PMSYS'
	and	  parameter_category 	= 'PDCPV' 
	and   language_id			= @ctxt_language
	
	
	
	if exists
		(select 'X'
		from	bnkdef_rcpt_pay_mode_vw (nolock)
		WHERE 	language_id  			= 	@ctxt_language
		--and 	elect_flag_code			=	@ep_tmp
		and     ou_id					= 	@ctxt_ouinstance
		and     rcpt_pymt_mode_code		=  @paymode_tmp
		AND		allow_future_date_flag	=	1 
		)or @paymode_tmp ='ECS'--EPE-7271
		
		begin
		
			select	@ctxt_service	= @ctxt_service
		end
	else
	begin
		if @paydate > @date_tmp
		begin	
		  
	 -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 1062
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
			-- raiserror ('Pay Date cannot be later than the system date for the selected Pay Mode. 
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,1062,'','','','','','','',@errmsg output 
			return		
		end
	END
	END	
	
	
	--IF @paytype_tmp = 'B'
	--AND @paydate > @date_tmp
	--BEGIN
	--    IF EXISTS
	--	(
	--		SELECT 	'X'
	--		FROM   	fin_quick_code_met(NOLOCK)
	--		WHERE  	component_id 		= 'SPY'
	--		AND    	parameter_type 		= 'PDCOPT'
	--		AND    	parameter_category 	= 'PDCOPT'
	--		AND    	parameter_code 		= @paymode_tmp
	--		AND    	language_id 		= @ctxt_language
	--	)
	--    BEGIN
	--        SELECT @ctxt_service = @ctxt_service
	--    END
	--    ELSE
	--    BEGIN
	--        --Pay Date cannot be later than the system date for the Pay Mode of the selected document <%%>.
	--        --Modify the Pay Date and Proceed
	--        EXEC fin_german_raiserror_sp 'SPY',
	--             @ctxt_language,
	--             1063,
	--             @creditdocnumber
	        
	--        RETURN
	--    END
	--END

	--Code added by Aparna M. for 8H123-1_spy_00001 ends
	--code for Def.Id 14H109_general_00137 ends here

	IF @paytype_tmp NOT IN 
	(
		SELECT 	rcpt_pymt_route_code
		FROM   	bnkdef_rcpt_pay_mode_vw(NOLOCK)
		WHERE  	rcpt_pymt_mode_code 	= @paymode_tmp
		AND    	ou_id 					= @ouinstidpo
		AND    	rcpt_pymt_method_code 	<> 'N'
		AND    	language_id 			= @ctxt_language
	)
	AND @paymode_tmp <> 'LC' --code added for the defect id ES_bnkdef_00013
	and @paymode_tmp <> 'ECS'--EPE-7271
	BEGIN
	  -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 3691043
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	 --raiserror ('Selected  Paymode is not valid for the selected Pay Route',16,1)
	    SELECT @m_errorid = 3691043
	    RETURN
    end
	END
	
	/* Code commented and handled in hchk sp by vijayan.j for the bugid:ES_spy_00021 starts here*/
	/*
	if @paymode_tmp in ('PO','DD') and @paychargeby_tmp = ''
	begin
	select @m_errorid = 261
	return
	end
	
	if @paymode_tmp not in ('PO','DD') and @paychargeby_tmp <> ''
	begin
	select @m_errorid = 3691044
	return
	end
	*/
	/* Code commented and handled in hchk sp by vijayan.j for the bugid:ES_spy_00021 ends here*/
	
	IF @paytype_tmp = 'B'
	AND @paymode_tmp = 'CA'
	BEGIN
	    -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8535
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    -- raiserror 50000 'Pay mode selected is invalid for the selected payment route'  
	    EXEC fin_sp_raise_error '',
	         '',
	         '',
	    '',
	         'SPY',
	         535,
	         @m_errorid OUTPUT
	    
	    RETURN
   end
	END  
	
	IF @paytype_tmp = 'C'
	AND @paymode_tmp <> 'CA'
	BEGIN
	     -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8535
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    -- raiserror 50000 'Pay mode selected is invalid for the selected payment route'  
	   EXEC fin_sp_raise_error '',
	         '',
	         '',
	         '',
	         'SPY',
	         535,
	         @m_errorid OUTPUT
	    
	    RETURN
    end
	END
			
	IF @creditdoccurrency <> @paycurml 
	BEGIN
	  -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 8194
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    --raiserror 50000 'Credit doc currency should be the same as Pay currency'  
	    EXEC fin_sp_raise_error '',
	      '',
	         '',
	         '',
	         'SPY',
	         385,
	   @m_errorid OUTPUT
	    RETURN
    end
	END 
	
	-- Porselvi.J - DMS412AT_SPY_00001 - starts
	/*
	select 	@pay_tmp	= pay_mode   
	from 	spy_invoice_dtl_vw (nolock)
	where 	ou_id  		= @ouinstidpo  
	and 	invoice_no 	= @creditdocnumber  
	*/
	SELECT 	@pay_tmp 	= pay_mode
	FROM   	si_doc_hdr(NOLOCK)
	WHERE  	tran_ou 	= @ouinstidpo
	AND    	tran_type 	= @creditdocnumber
	AND    	tran_type 	= @transactiontype /* Code Added by Vairamani C for ES_SPY_00176 */
	-- Porselvi.J - DMS412AT_SPY_00001 - ends
	
	IF @pay_tmp = 'LSV'
	AND @paymode_tmp <> 'LSV'
	BEGIN
	     -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 1900030099
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	    EXEC fin_sp_raise_error @creditdocnumber,
	         '',
	         '',
	         '',
	         'RR',
	         26,
	         @m_errorid OUTPUT
	    
	    RETURN
    end
	END   
	
	IF @pay_tmp = 'ESR'
	BEGIN
	    IF @paymode_tmp NOT IN ('ESR', 'ESR+')
	    BEGIN
		   -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 1900030097
		  return
		end
	-----EPE-13408  ends---------
	else
	begin
	        EXEC fin_sp_raise_error @creditdocnumber,
	             '',
	             '',
	             '',
	             'RR',
	             28,
	             @m_errorid OUTPUT
	        
	        RETURN
     end
	    END
	END
	
	SELECT 	@paymethodml1_tmp 		= rcpt_pymt_method_code
	FROM   	bnkdef_rcpt_pay_mode_vw(NOLOCK)
	WHERE  	rcpt_pymt_mode_code 	= @pay_tmp
	AND    	rcpt_pymt_method_code 	<> 'N'
	AND    	ou_id 					= @ouinstidpo
	AND    	language_id 			= @ctxt_language
	
	SELECT 	@paymodeml 				= rcpt_pymt_mode
	FROM   	bnkdef_rcpt_pay_mode_vw(NOLOCK)
	WHERE  	rcpt_pymt_mode_code 	= @paymode_tmp
	AND    	ou_id 					= @ouinstidpo
	AND    	rcpt_pymt_method_code 	<> 'N'
	AND    	language_id 			= @ctxt_language
	
	--code added by Aparna M. for the bug ES_spy_00003 starts
	/* Code added by vijayan.j for the bugid:DMS412AT_spy_00026 starts here*/
	IF @ctxt_service IN ('SPYAdRpMnSrCreate', 'SPYAdRpMnSrCrAuth') 
	BEGIN
	    /* Code added by vijayan.j for the bugid:DMS412AT_spy_00026 ends here*/
		IF EXISTS
		(
			SELECT 	'x'
			FROM   	(
						SELECT 	cr_doc_amount,
								SUM(pay_amount) 'amt' --code has been added for ES_spy_00088
						FROM   	spy_paybatch_dtl DTL(NOLOCK),
								spy_paybatch_hdr HDR(NOLOCK)
						WHERE  	DTL.cr_doc_ou 		= @ouinstidpo
						AND    	DTL.cr_doc_no 		= @creditdocnumber
						AND    	DTL.term_no 		= @termnumberhdnhdr
						AND    	DTL.tran_type 		= @transactiontype
						AND    	DTL.paybatch_no 	= HDR.paybatch_no
						AND    	DTL.ou_id 			= HDR.ou_id
						AND  	HDR.status	IN ('F', 'RE', 'DF')
						--code has been added for ES_spy_00088 begins
						GROUP BY cr_doc_amount
					)TMP
			WHERE  (cr_doc_amount - TMP.amt) < @tranamount
		)
		--code has been added for ES_spy_00088 ends
		BEGIN
		   -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 504
		  return
		end
		-----EPE-13408  ends---------
		else
		begin
			EXEC fin_german_raiserror_sp 'SPY',
				@ctxt_language,
				504
			
			RETURN
        end
		END
	END -- Code added by vijayan.j for the bugid:DMS412AT_spy_00026
	    --code added by Aparna M. for the bug ES_spy_00003 ends
/* Code added by Anusha  P for the defect id : 14H109_General_00138 starts here	*/
  
		declare	@lease_no	fin_documentno,
				@lease_ou	fin_ouinstid	
		
		
			select	@lease_no	=	lease_no,
					@lease_ou	=	lease_ou
			from	ales_lease_doc_dtl(nolock)
			where	tran_no		=	@creditdocnumber
			and		tran_type	=	'PM_EV'
			and		tran_ou		=	@ctxt_ouinstance
			
			if @lease_no is not null
			begin
				update	ales_lease_doc_dtl
				set		tran_status	=	'REQ',
						mod_flag	=	'N'
				where	tran_no		=	@creditdocnumber
				and		tran_type	=	'PM_EV'
				and		tran_ou		=	@ctxt_ouinstance
				
				update	ales_lease_hdr
				set		rev_allowed		=	'N'
				where	lease_no		=	@lease_no
				and		lease_ou		=	@lease_ou
			end
	/* Code added by Anusha P for the defect id : 14H109_General_00138 ends here	*/
		
	/*code added for defect id:ES_spy_00712 starts here*/	
	if exists (	select	'X'
				from	si_Doc_balance(nolock)	
				where	tran_no		=	@creditdocnumber
				and		tran_ou		=	@ouinstidpo
				and		tran_type	=	@transactiontype
				and		term_no 	=	@termnumberhdnhdr
				and		isnull(requested_amount,0) + isnull(paid_amt,0) + isnull(adjusted_amount,0) + @tranamount > tran_amount
				)
	begin

	   -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 504
		  return
		end
		-----EPE-13408  ends---------
		else
		begin
		EXEC fin_german_raiserror_sp 'SPY',@ctxt_language,504
		RETURN
		end
	end
	
	/*code added for defect id:ES_spy_00712 ends here*/
		
	IF @paymethodml1_tmp NOT IN 
	(
		SELECT 	rcpt_pymt_method_code
		FROM   	bnkdef_rcpt_pay_mode_vw(NOLOCK)
		WHERE  	rcpt_pymt_mode 			= @paymodeml
		AND    	ou_id 					= @ouinstidpo
		AND    	rcpt_pymt_method_code 	<> 'N'
		AND    	language_id 			= @ctxt_language
	)
	AND @paymode_tmp <> 'LC' --code added for the defect id ES_bnkdef_00013
	and @paymode_tmp <> 'ECS'--EPE-7271
	BEGIN
	-----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 3691042
		  return
		end
		-----EPE-13408  ends---------
		else
		begin
	    --raiserror ('Payment Method of Credit Document and Pay Mode selected does not match. Modify Pay Mode.',16,1)
	    SELECT @m_errorid = 3691042
	    RETURN
      end
	END
	
	SELECT 	@allowmodisc 			= LTRIM(RTRIM(parameter_text))
	FROM   	fin_processparam_sys(NOLOCK)
	WHERE  	component_id 			= 'SPY'
	AND    	ou_id 					= @ctxt_ouinstance
	AND    	parameter_category 		= 'FNDEF'
	AND    	parameter_code 			= 'MODDIS'
	AND    	company_code 			= @compcode
	
	--Code modified by Porselvi.J for bug id : SPYDMS412AT_000324 starts
	IF @allowmodisc = 'N'
	BEGIN
	    IF @applieddiscountml <> @proposeddiscountml
	    BEGIN
		   -----EPE-13408 starts---------
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 45
		  return
		end
		-----EPE-13408  ends---------
		else
		begin
	        EXEC fin_german_raiserror_sp 'SPY',
	             @ctxt_language,
	             45,
	             @creditdocnumber,
	             '',
	             '',
	             '',
	        '',
	             '',
	             '',
	             @errmsg OUTPUT
	        
	        RETURN
        end
	    END
	END 
	--Code modified by Porselvi.J for bug id : SPYDMS412AT_000324 ends
	
	IF @appliedpenaltyml > @proposedpenaltyml
	BEGIN
	  if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 1313
		  return
		end
		-----EPE-13408  ends---------
		else
		begin
	    EXEC fin_sp_raise_error @creditdocnumber,
	         '',
	         '',
	         '',
	         'RR',
	         7,
	         @m_errorid OUTPUT
	    
	    RETURN
		end
	END
	
	/* Code moved here for the defect id :ES_spy_00061 starts here */
	SELECT 	@cr_doc_fb_id 		= fb_id,
	       	@basecur_erate 		= exchange_rate,
	       	@parbasecur_erate 	= par_exchange_rate
	FROM   	si_doc_hdr(NOLOCK)
	WHERE  	tran_no 			= @creditdocnumber
	AND    	tran_ou 			= @ouinstidpo
	AND    	tran_type 			= @transactiontype
	/* Code moved here for the defect id :ES_spy_00061 ends here */

	 --CKBW2-1612
	if not exists
	(
		select 'x'
		from	pps_finance_feature_list (nolock)
		where	feature_id = 'PPS_indvat_7280_1'
		and		flag_yes_no = 'YES'
	)
	begin
	--CKBW2-1612

	/*code added for defect id:ES_spy_00542 starts*/
	SELECT 	@basecur_erate 		= exchange_rate,
   			@parbasecur_erate 	= par_exchange_rate
	FROM   	si_acct_info_dtl(NOLOCK)
	WHERE  	tran_no 			= @creditdocnumber
	AND  	tran_ou 			= @ouinstidpo
	AND    	tran_type 			= @transactiontype
	and		account_type		in ('SCA','SPA','SDA')
	/*code added for defect id:ES_spy_00542 ends*/

	end --CKBW2-1612

	/*
	If OU Function Default "Action on Debit Document check"   
	is set to "Hold", invoke service SdcnSerSpyTrn1
	*/
	-- Code commented and added in hdrchk sp for EPE-70571
	--SELECT 	@crdocchk 			= LTRIM(RTRIM(parameter_text))
	--FROM   	fin_processparam_sys(NOLOCK)
	--WHERE  	component_id 		= 'SPY'
	--AND    	ou_id 				= @ctxt_ouinstance
	--AND   	parameter_category 	= 'FNDEF'
	--AND    	parameter_code 		= 'DBDCHK'
	--AND    	company_code 		= @compcode  
	
	--IF @crdocchk = 'H'
	--BEGIN
	    --Revisit (Hari) New view should be used.
	    --Code modified by Aparna M.(Need to be clarified with hari) for the bug SPYDMS412AT_000452 starts
	--    IF EXISTS
	--	(
	--		/*Code commented and added by Uma for the defect id : ES_spy_00061 Starts here*/
	--		/*
	--		select 'X' 
	--		from 	si_spy_debit_due_vw	si(nolock),
	--		scdn_spy_item_dtl_vw scdn(nolock)
	--		where	si.documentno		= scdn.tran_no
	--		and	si.tran_type		= scdn.tran_type
	--		and	si.ou_id		= scdn.tran_ou
	--		and	scdn.ref_doc_no 	= @creditdocnumber
	--		and	scdn.ref_doc_type 	= @transactiontype
	--		*/
	--		SELECT 	'X'
	--		FROM   	si_doc_balance SI(NOLOCK),
	--				emod_ou_Vw EMOD(NOLOCK)
	--		WHERE  	fb_id 				= @cr_doc_fb_id
	--		AND    	supp_code 			= @supplierml
	--		AND    	outstanding_amt 	> 0
	--		AND    	company_code 		= @compcode
	--		AND    	SI.tran_ou 			= EMOD.ou_id
	--		AND    	tran_date 			<= @requestdate
	--		AND    	tran_type	IN ('PM_SDA', 'PM_SDI', 'PM_STD')
	--		/*Code commented and added by Uma for the defect id : ES_spy_00061 ends here*/
	--		--Code modified by Aparna M.(Need to be clarified with hari) for the bug SPYDMS412AT_000452 ends
	--	)
	--    BEGIN
	--	if(@ctxt_user = 'jobuser')
	--	begin
	--	  select  @m_errorid = 1900030095
	--	  return
	--	end
	--	-----EPE-13408  ends---------
	--	else
	--	begin
	--        EXEC fin_sp_raise_error @creditdocnumber,
	--             '',
	--             '',
	--             '',
	--             'SPY',
	--             333,
	--       @m_errorid OUTPUT
	        
	--        RETURN
 --       end
	--    END  
	    
	--    SELECT @crdocchk = ''
	--END
	
	/*
	If OU Function Default "Action on Debit balance check" is set to "Hold",   
	for each Supplier selected in m/l, invoke service SISerSpyTrn4 of 
	Supplier Inquiry component
	*/
	--SELECT 	@crdocchk 			= LTRIM(RTRIM(parameter_text))
	--FROM   	fin_processparam_sys(NOLOCK)
	--WHERE  	component_id 		= 'SPY'
	--AND    	ou_id = 			@ctxt_ouinstance
	--AND    	parameter_category 	= 'FNDEF'
	--AND    	parameter_code 		= 'DDLCHK'
	--AND    	company_code 		= @compcode  

	--IF @crdocchk = 'H'
	--BEGIN
	 /* Code modified by Uma for the defect id : ES_spy_00124 Starts here*/
	    /*
	    --Revisit (Hari) New SP should be used.
	    exec 	si_spy_supp_balance_sp
	    @ctxt_ouinstance,@supplierml,@requestdate,
	    @guid_tmp,@m_errorid output
	    
	    select 	@supdrbla_tmp	= tran_amount
	    from    si_cur_bal_vw(nolock)
	    where  	guid		= @guid_tmp
	    and 	currency	= @paycurml
	    */
	    
	    /* Code modified by Uma on 1st Jun 2009 for the defect id : ES_spy_00124 Starts here*/
	    /*
	    select @supdrbla_tmp = 	sum(
	    case
	    when 	drcr_flag = 'DR' then tran_amount_acc_cur else - tran_amount_acc_cur 
	    end) 
	    from 	si_acct_info_dtl SI(nolock)
	    where 	fb_id           = @cr_doc_fb_id
	    and	supplier_code	= @supplierml
	    and	company_code	= @compcode
	    and	posting_date	< = @requestdate
	    and	account_type 	in('SCA','SDA','SPA')
	    */
	    
	    --DECLARE @fin_year    fin_financeyear,
	    --        @fin_period  fin_financeperiod,
	    --        @basecur     fin_currencycode	
	    
	    --SELECT 	@basecur 		= currency_code
	    --FROM   	emod_basecurr_vw(NOLOCK)
	    --WHERE  	company_code 	= @compcode
	    --AND    	flag 			= 'B'
	  
	    --SELECT 	@fin_year 		= fin_year,
	    --       	@fin_period 	= fin_period
	    --FROM   	fcc_prd_close_status(NOLOCK)
	    --WHERE  	company_code 	= @compcode
	    --AND    	fb_id 			= @cr_doc_fb_id
	    --AND    	STATUS 			= 'O'
	    --AND    	@date_tmp BETWEEN fcc_finprd_startdt AND fcc_finprd_enddt
	    
	    --SELECT 	@supdrbla_tmp 		= SUM(ISNULL(cb_debit, 0)) - SUM(ISNULL(cb_credit, 0))
	    --FROM   	si_supplier_balance SI(NOLOCK)
	    --WHERE  	fb_id 				= @cr_doc_fb_id
	    --AND    	supplier_code 		= @supplierml
	    --AND    	company_code 		= @compcode
	    --AND    	account_type 		= 'SCA'
	    --AND    	fin_year 			= @fin_year
	    --AND    	fin_period 			= @fin_period
	    --AND    	balance_currency 	= @basecur
	    --/* Code modified by Uma on 1st Jun 2009 for the defect id : ES_spy_00124 Ends here*/
	    
	    --IF @supdrbla_tmp > 0 
	       -- if @supdrbla_tmp <0  
	       /* Code modified by Uma for the defect id : ES_spy_00124 Ends here*/
	--    BEGIN
	--		    -----EPE-13408 starts---------
	--		if(@ctxt_user = 'jobuser')
	--		begin
	--		  select  @m_errorid = 1900030135
	--		  return
	--		end
	--		-----EPE-13408  ends---------
	--		else
	--		begin
	--			 --raiserror ('Debit balance exists for the Supplier %s Payment cannot be made.',16,1,@supplierml)
	--			 SELECT @m_errorid = 3691045
	--			 RETURN
 --           end
	--    END

	--    EXEC si_clear_sp
	--         @ctxt_user,
	--         @ctxt_ouinstance,
	--         @ctxt_service,
	--    @guid_tmp,
	--         @m_errorid
	--END
	-- Code commented and added in hdrchk sp for EPE-70571

	SELECT @spaytrannetamount = ROUND(@tranamount, @pamt_tmp)
	       - ROUND(ISNULL(@applieddiscountml, 0), @pamt_tmp)
	       + ROUND(ISNULL(@appliedpenaltyml, 0), @pamt_tmp)-ISNULL(@appliedwhtam,0)----14H109_TCAL_00039
	
	SELECT @payamount1 = ROUND(@spaytrannetamount, @pamt_tmp)  -- code modified by samuel for bug id : es_spy_00308
	
	IF EXISTS
	(
		SELECT 	'X'
		FROM   	supp_ou_suplmain sup(NOLOCK)
		WHERE  	--supp_ou_ouinstid 	= @ouinstidpo
		 		supp_ou_ouinstid	in (@ouinstidpo,@suppou_tmp) --EBS-2667
		--AND    	supp_ou_supcode 	= @paytosupplier	--ES_spy_01568
		AND    	supp_ou_supcode 	= isnull(@paytosupplier,@supplierml) --ES_spy_01568
		AND 	supp_ou_supstatus NOT IN ('AC','HB')					 --RIL-241	
	)
	BEGIN
		--CAMPSS-120
	    -- Supplier is not in Active Status
	    --EXEC fin_german_raiserror_sp 'SPY',
	    --     @ctxt_language,
	    --     39
		if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 1900030100
		  return
		end
		-----EPE-13408  ends---------
		else
		begin
		 EXEC fin_german_raiserror_sp 'TP',@ctxt_language,99,@supplierml
		 --    Supplier Code "%s" is not in Active status.
		--CAMPSS-120
	    RETURN
     end
	END

/*	/*Code added by Kavitha R for defect id 14H109_spy_00035 begins here*/
	exec spy_recompute_check_sp @ctxt_ouinstance,@ctxt_language,@ctxt_user,@ctxt_service,
								@creditdocnumber,@ouinstidpo,@transactiontype,@termnumberhdnhdr,
								@duedate,@proposeddiscountml,@proposedpenaltyml,@presentoutstandingamount,
								@tranamount, @proposwhtam,@paybatchnumber, @m_errorid out --14H109_spy_00039
								
	if 	@m_errorid <> 0
	begin
		exec fin_german_raiserror_sp 'SPY',@ctxt_language,6000
		return	
	end							
	/*Code added by Kavitha R for defect id 14H109_spy_00035 ends here*/	
	
*/
--14H109_TCAL_00039
	/*Check for Tolerance Limit check for WHT amount*/
	exec tcal_tolchk_WHTAMT	@ctxt_ouinstance,	@ctxt_service,	@ctxt_user,
							@ctxt_language,		@compcode,	@appliedwhtam,
							@proposwhtam,	@m_errorid out
	if 	@m_errorid	<> 0
	begin
	if(@ctxt_user = 'jobuser')
		begin
		  select  @m_errorid = 1900030101
		  return
		end
		-----EPE-13408  ends---------
		else
		begin
		exec fin_german_raiserror_sp 'TCAL',@ctxt_language,1900027400,@fprowno
		return
        end
	end	
--14H109_TCAL_00039
		
	--Code added by Aparna M. for SRDMS412AT_000079 starts
	SELECT 	@acct_type_tmp 	= account_type
	FROM   	si_doc_balance(NOLOCK)
	WHERE  	tran_no 		= @creditdocnumber
	AND    	tran_ou 		= @ouinstidpo
	AND    	tran_type 		= @transactiontype
	AND    	term_no 		= @termnumberhdnhdr
	--Code added by Aparna M. for SRDMS412AT_000079 ends
	

	/*Code added for EPE-48054 starts here */
	IF @modeflag IN ('X','Y','Z')
	BEGIN
		exec frwrd_cntrt_cmnml_validate
			@ctxt_language,     
			@ctxt_ouinstance,   
			@ctxt_service,      
			@ctxt_user,         
			@crdocou,     
			@creditdocnumber,		
			@transactiontype,     
			@compcode,		
			@ForwardContractNo,	
			'SPY',		
			@fprowno,			
			@m_errorid output
		
		IF @m_errorid <> 0 
		BEGIN
			return
		END
	END

	/*Code added for EPE-48054 ends here */
	--PJRMC-1535
		DECLARE @doc_date date
select @doc_date =(select tran_date from si_doc_hdr where tran_no=@creditdocnumber AND TRAN_ou=@ctxt_ouinstance)

if @doc_date>='2025-04-01'
begin
--PJRMC-1535

/*Code added by  krishnan start*/	
Declare @tax_excl_amt udd_amount,@matchType  varchar(50),@paidamount udd_amount

select @paidamount=sum(tran_amount) from spy_paybatch_dtl(nolock) a
inner join spy_paybatch_hdr (nolock) b on a.paybatch_no=b.paybatch_no
where  cr_doc_no = @creditdocnumber
and status in ('A','F')
and a.paybatch_no<>@paybatchnumber

			select  @tax_excl_amt= tax_excl_amt,@matchType=case when isnull(matchType,'Notmatched') in('exact') then 'matched'else 'Notmatched' end  from 
			scmdb..tcal_tran_hdr(nolock) 
			left join  (select documentReferenceNumber,matchType from interfacedb..ClearMaxITC_Result_Result r (nolock) 
						inner join interfacedb..ClearMaxITC_Result_Govt g  (nolock)  on   g.refdocumentId=r.refdocumentId
						/*/*Code Added for RITSL/PJRMC-980 Begins*/
						union					
						Select gred_tranno,'exact' from gre_rectax_inv_hdr with (nolock)
						Join	gre_rectax_inv_dtl	with (nolock)
						On		gred_batchno	=	greh_batchno
						And		gred_ouid		=	greh_ouid
						where	greh_status		=	'AU'
						/*Code Added for RITSL/PJRMC-980 Ends*/*/
						/*Code Added for RITSL/PJRMC-980 Begins*/
						union	
						Select	CreditDocNo,MatchType
						From	Zrit_Max_ITC_Exclude_Doc with (nolock)
						where	CreditDocNo		=	@creditdocnumber
						--And		CreditDocOU		=	@ctxt_ouinstance
						union
						Select	@creditdocnumber,'exact'
						From	supp_spmn_suplmain with(nolock)
						where	supp_spmn_supcode = @supplierml
						And		supp_msme_flag	=	'Y'
						/*Code Added for RITSL/PJRMC-980 Ends*/
						
						) k
			on documentReferenceNumber =tran_no 
			where tax_type='GST'
			and  tran_no = @creditdocnumber
--select @tax_excl_amt,@tranamount,@matchType,@creditdocnumber
if @tranamount+isnull(@paidamount,0)>@tax_excl_amt  and @matchType='Notmatched'
begin
/*Code Commented and Added by Amirtha P. on 15.12.2024 Begins*/
--Raiserror('Pay amount should be Excluding Tax amount.GST not filled %s',16,1,@creditdocnumber)
Raiserror('GST is not filed for the Invoice No.:%s. Hence, Transaction Amount should be excluding GST.',16,1,@creditdocnumber)
/*Code Commented and Added by Amirtha P. on 15.12.2024 Ends*/
return
end 
/*Code added by  krishnan end*/	
	end --PJRMC-1535
	INSERT INTO spy_paybatch_dtl_tmp
	(
			guid,
			ou_id,
			paybatch_no,
			cr_doc_ou,
			cr_doc_no,
			cr_doc_cur,
			cr_doc_amount,
			cr_doc_fb_id,
			supplier_code,
			pay_to_supp,
			tran_type,
			cr_doc_type,
			pay_currency,
			pay_amount,
			tran_amount,
			tran_net_amount,
			outstanding_amt,
			discount,
			penalty,
			due_date,
			pay_mode,
			basecur_erate,
			crosscur_erate,
			pay_cur_erate,
			STATUS,
			supp_ctrl_acct,
			supp_acc_no,	--Aparna M. -SRDMS412AT_000079
			supplier_invoice_no,
			TIMESTAMP,
			sel_flag,
			term_no,
			parbasecur_erate,
			proposed_penalty,
			proposed_discount,
			cr_doc_ou_name,
			lcnumber,
			refid,
			supplier_invoice_date --Code Added by Angelin.R : 9H123-1_spy_00027
		--/*14H109_TCAL_00039*/
			,prop_wht_amt,
			app_wht_amt,
		/*14H109_TCAL_00039*/
		rowno --EPE-70587
			
	)--code added by Esther J for the defect ES_bnkdef_00013 ; LC
	VALUES
	(
			@guid,
			@ctxt_ouinstance,
			@paybatchnumber_tmp,
			@ouinstidpo,
			@creditdocnumber,
			@creditdoccurrency,
			ROUND(@creditdocamount, @pamt_tmp),
			@cr_doc_fb_id,
			@supplierml,
			@paytosupplier,
			@transactiontype,
			@transactiontype,
			@paycurml,
			ROUND(@payamount1, @pamt_tmp),  -- code modified by samuel for bug id : es_spy_00308
			ROUND(@tranamount, @pamt_tmp),
			ROUND(@spaytrannetamount, @pamt_tmp),
			ROUND(@presentoutstandingamount, @pamt_tmp),
			ROUND(@applieddiscountml, @pamt_tmp),
			ROUND(@appliedpenaltyml, @pamt_tmp),
			@duedate,
			@paymode_tmp,
			ROUND(@basecur_erate, @perate_tmp),
			ROUND(@paycur_erate, @perate_tmp),
			ROUND(@paycur_erate, @perate_tmp),
			'DF',
			'SCA',
			@acct_type_tmp,
			@supplierdocumentnumberml,
			1,
			'S',
			@termnumberhdnhdr,	--Aparna M. -SRDMS412AT_000079
			ROUND(@parbasecur_erate, @perate_tmp),
			ROUND(@appliedpenaltyml, @pamt_tmp),
			ROUND(@applieddiscountml, @pamt_tmp),
			@crdocou,
			@lcnumberml,
			@refid,
			@SupplierInvoiceDateML --Code Added by Angelin.R : 9H123-1_spy_00027
			--/*14H109_TCAL_00039*/
			,@proposwhtam,
			@appliedwhtam, 
		/*14H109_TCAL_00039*/
		@fprowno --EPE-70587
	) --code added by Esther J for the defect ES_bnkdef_00013 ; LC	
	
	/*Code added for EPE-7271 begins here*/


	if exists(	select	'*'
				from	FB_TMP (nolock)
				where	rsih_guid_tmp	= 	@guid
				and		REMARKS			=	'0'
				and		rsih_fb_tmp in ('ICT_MPAY_Ser_Sav','ICT_MPAY_Ser_Aut')
			)
	begin
		UPDATE	FB_TMP 
		SET		REMARKS		=	'1'
		where	rsih_guid_tmp			= @guid
		and		rsih_fb_tmp in ('ICT_MPAY_Ser_Sav','ICT_MPAY_Ser_Aut')
		
		return
	end	
	/*Code added for EPE-7271 ends here*/	
	/*Code added for 13H120_GENERAL_00034 begins here*/
	if exists (	select	'x'
				from	FB_TMP (nolock)
				where	rsih_guid_tmp			= @guid
				and		rsih_fb_tmp in ('ICT_MPAY_Ser_Sav','ICT_MPAY_Ser_Aut')
			  )
	begin	
		return
	end
	 ----EPE-13408-----
	if @ctxt_user = 'jobuser'
		begin
			select @m_errorid = 0
			return
		end
    ----EPE-13408-----	
	/*Code added for 13H120_GENERAL_00034 ends here*/	

	--EPE-46106 starts
	if @placeholder4 = 'SPYMailer'
	begin
		return
	end
	--EPE-46106 ends
	if @called_from = 'NONE'
	begin	
	SELECT 	0 						'ERRORNO',
			@fprowno 				'FPROWNO',
			'' 						'PLACEHOLDER1',
			'' 						'PLACEHOLDER2',
			'' 						'PLACEHOLDER3',
			'' 						'PLACEHOLDER4',
			0 						'SUCCESSFLAG',
			/*Code Added by samuel for bud id ES_spy_00308*/
			null					'exrate', 
			null					'payamount', 
			null					'baseamount'
			/*Code Added by samuel for bud id ES_spy_00308*/
	end
	else
	begin
		update	mca_sel_doc_tmp
		set		error_id	= 0
		where	hdn_guid = @guid		
	end		
	
	SET NOCOUNT OFF
END


















