/*$File_version=ms4.3.0.47$*/
/*$file name : spyauppmnspreturnhdrsave.sql			*/
/*$version   : 4.0.0.14					*/
/*==================================================  
   stored procedure : spyauppmnspreturnhdrsave   
   method           : spyauppmnspreturnhdrsave  
   author           : Sellapillai N.  
   created on       : 26 mar 2002 19:18:36:693  
   created at       : s4353  
   generated by     : fpuser  
   Modified By     : Sushil Saxena  
   Modify Date     : 07 Oct 2002  
   Modified By     : BIJU  
   Modify Date     : 20 May 2003  
   Modified By     : BIJU  
   Modify Date     : 30 Sep 2003  
   Purpose		   :SPYRGGSYSTST_000181
   Modified By     : Jinesh K  
   Modify Date     : 05 Apr 2003  
   Purpose		   :SPYDMS41ACTST_000067  	
   Modified By     : Jinesh K  
   Modify Date     : 07 Apr 2003  
   Purpose		   :SPYDMS41UTST_000001   	
  
declare @P1 fin_int  
select @P1=0  
exec spyauppmnspmodauthdrsave 1, '15', 'spyedppmnsrmodaut', 'demouser', '1', '~#~',   
'By Payee', 1.000000000000000e+000, 'FB-001', '3B1E52EC-8365-11D6-BBBA-000795010322',   
'demouser', '2002-06-20', 2.000000000000000e+002, 'INR', '2002-06-20', 'Bank', 'Cash',   
'PrePayment', 'Medium', 'Testou', '~#~', '2002-06-20', 'Fresh', '903', 'Testou',   
2.200000000000000e+001, '2002-06-20', '1', '~#~', 2, 'CPV0018', @P1 output  
select @P1  
==================================================*/
/********************************************************************************/
/* modified by  : Rajesh R                                                      */
/* date         : 29-Apr-2004                                                   */
/* description  : SPYDMS41UTST_000009- DMS4.1 MERGING                           */
/********************************************************************************/
/*   Modified By     : Jinesh K  
   Modify Date     : 21-Jun-2004 
   Purpose	   :SPYDMS41SYTST_000028					*/
/********************************************************************************/
/*Modified by			Date			Remarks			*/
/*S.Shankaranand		5/9/04			For German Transaction	*/
/*S.balaji				31/01/2006		SPYDMS412AT_000100	*/
/*A.R.R.balaji          14/03/2006      SPYBASEFIXES_000739 */
/*S.balaji				06/05/2005		SPYDMS412AT_000181  */
/*S.balaji				25/05/2006		SPYDMS412AT_000204	*/
/*S.balaji				08/09/2006		SPYDMS412AT_000254	*/
/*S.balaji				08/09/2006		SPYDMS412AT_000254	*/
/*Jeganathan.M			16/04/2007		SPYDMS412AT_000275	*/
/*Ravikrishnan.N		19/Jul/2007		SPYDMS412AT_000473	*/
/*Esther J				13-08-2007 		SPYDMS412AT_000518 : Performance Tuning */
/*Antoinette			19-09-2007		SPYDMS412AT_000534	*/
/*Karthi K.K			19-10-2007		SPYDMS412AT_000551	*/
/*Porselvi.J			23-06-2008		ES_spy_00012		*/
/*Esther J				24/03/2009		ES_bnkdef_00013 	*/
/* Nithya P				18/09/2009		ES_spy_00138		*/
/* Ananth P.			30/09/2009		ES_spy_00173		*/
/* Esther J				08/10/2009		9H123-!_spy_00014	*/
/* Esther J				21/10/2009		9H123-!_spy_00017	*/
/* Deepika.V			28/12/2009		ES_spy_00194		*/	
/* R.Mohandas			19/01/2010		9H123-1_SPY_00026	*/
/* Pusba Prasanaa.B.R.	30/07/2010		ES_cps_00008		*/
/* Deepika V			16/09/2010	    ES_spy_00248[10H109_spy_00034]*/
/* Deepika V			16/09/2010	    ES_spy_00248[10H109_spy_00034:10H109_spy_00044]*/
/* Veangadakrishnan R   09/11/2010	    ES_fcc_00084(10H109_FCC_00001)*/
/* Samuvel g			30/12/2010      ES_SPY_00308  */  
/* Esther J			    15/12/2010		10H109_spy_00047(TRUST RECEIPTS)*/
/* Indira G             03/06/2011      ES_spy_00391        */
/* Indira G             20/07/2011      ES_spy_00401       */
/* Sharmila M			25/07/2011			ES_spy_00397: 11H103_spy_00010	*/
/* Sharmila M			2/08/2011			ES_spy_00397[11H103_spy_00010:11H103_spy_00032]*/
/* Esther J				10/01/2012		11H103_rp_00054 [ES_rp_00328] */ 
/* Esther J				20/01/2012			11H103_spy_00047[ES_bnkdef_00048]*/
/* Esther J				14/02/2012		11H103_spy_00048	*/
/* Esther J				28/02/2012		11H103_spy_00048:11H103_spy_00117 */
/* Nithya P				02/05/2012		ES_spy_00526 */
/* Sharmila	M			15/09/2012		ES_Po_00914:12H124_PO_00002					*/
/* Kavitha R			04/03/2016		14H109_mcam_00001*/
/* Kavitha R			18/03/2016		14H109_SPY_00056		*/
/* Vishweswaran		   4/May/2016		14H109_General_00137 */	
/*Anusha.p             10/10/2018        epe-9608 */
/*Banurekha B           10/4/2019         PE-162                  */
/* Sangeetha M			04/09/2018		EPE-9790(Logistics_prepayment)		    */
--gokul M						16/04/2020				epe-17774
/*Mabel Rita.L           09/6/2020         TLET-612                  */
/*Balaji C				03/08/2020			TLET-621				*/
/*Mabel Rita.L           31/8/2020         CUPE-489                  */
/* Shobana				11/06/2021			EPE-32731			*/
/* Vignesh E			04/06/2021			EPE-34128			*/
--Amani.P			15-09-2021			EPE-37936
--Amani.P			11-10-2021			EPE-38698
--Preethi Venkatraman            13-08-2022              EPE-48054
/*Ramesh Kumar C				25-08-2022			EPE-44709	*/
/* Abinav						02/03/2023			EPE-60038 	*/
/*Divyalekaa					22/01/2023			EPE-70555	*/
/* Kavitha R					23/05/2024			EPE-79558:EPE-81543	*/
/* Amirtha P					16.08.2024			RITSL/RMC_FIN_53 	*/
/********************************************************************************/
create   procedure spyauppmnspreturnhdrsave
	@ctxt_language                 fin_ctxt_language,
	@ctxt_ouinstance               fin_ctxt_ouinstance,
	@ctxt_service                  fin_ctxt_service,
	@ctxt_user                     fin_ctxt_user,
	@bankcash                      fin_bankcashcode,
	@bankdescription               fin_bankdescription,
	@ddoption                      fin_ddoption,
	@exchangerate                  fin_exchangerate,
	@fb                            fin_financebookid,
	@guid                          fin_guid,
	@lastmodificationby            fin_ctxt_user,
	@lastmodifieddate              fin_date,
	@payamount                     fin_amount,
	@paycurrencycode               fin_currencycode,
	@paydate                       fin_date,
	@paymentroute                  fin_route,
	@paymode                       fin_paymode,
	@ppvouchertype                 fin_documenttype,
	@priority  					   fin_priority,
	@relpayou                      fin_ouinstname,
	@remarks                       fin_text255,
	@requestdate         	       fin_date,
	@status                        fin_status,
	@supplier  		      		   fin_suppliercode,
	@supplierarea                  fin_ouinstname,
	@supplierdocumentamount        fin_amount,
	@supplierdocumentdate 	       fin_date,
	/*Code commented and added for the defect id PE-162 starts here*/
	--@supplierdocumentnumber        fin_documentnumber,
	@supplierdocumentnumber        fin_Description,
	/*Code commented and added for the defect id PE-162 ends here*/
	@suppliername                  fin_name, 
	@timestamp   		       	   fin_timestamp,
	@vouchernumber    	       	   fin_documentno,
	@accountcode                   fin_accountcode,
	@accountdesc                   fin_accountdesc,
	@lcnumber		      		   fin_lcnumber, --code added by Esther J for the defect ES_bnkdef_00013 ; LC	
	/* Code added for the dts id 10H109_spy_00047 starts */
	@tr_payment					   fin_option,
	@tr_precent					   fin_duepercentage,
	@tr_amount					   fin_Amount,
	@tr_tenure					   fin_number,
	@tr_duedate					   fin_date,
	@tr_lmtbalance				   fin_Amount,
	@surnumtype					   fin_notypeno,
	/* Code added for the dts id 10H109_spy_00047 ends*/
	/*Code Added By Indira.G For Defect Id:ES_spy_00391 Starts*/
	@exrate             fin_exchangerate, --Input/Output 
	@payamount1         fin_amount, --Input/Output
	@baseamount         fin_amount, --Input/Output
	/*Code Added By Indira.G For Defect Id:ES_spy_00391 Ends*/
	@lc_refid               	  udd_ref_id, --Input/Output --ES_spy_00397: 11H103_spy_00010
		/* code added for 11H103_spy_00048 starts */
	@PRJOU						fin_ouinstname,
	@PRJSUBPRJCD				fin_projectcode,
	@PRJSUBPRJDESC				fin_projectdescription,
	@trustreceiptwithbankeraccept 	notypeno, --Input/Output -- code added for EPE-32731
	/* code added for 11H103_spy_00048 ends*/
	@ForwardContractNo      fin_documentno,   --EPE-48054
	@m_errorid                     fin_int output
--to return execution status  
as	
begin	/*YTAG_1_BEGIN*/
	set nocount on
	--BEGIN of Standard code for getting precision type  
	declare	@pqty_tmp                      fin_int
	declare @pamt_tmp                      fin_int
	declare @prate_tmp                     fin_int
	declare @perate_tmp                    fin_int
	declare @phigh_tmp                     fin_int
	declare @pmed_tmp                      fin_int
	declare @plow_tmp                   fin_int 

	exec fin_sp_precisiontype_rtr       
	@pqty_tmp 	output,
	@pamt_tmp 	output,
	@prate_tmp 	output,
	@perate_tmp 	output,
	@phigh_tmp 	output,
	@pmed_tmp 	output,
	@plow_tmp 	output

	--END of Standard code for getting precision type  
	declare @sysdate_char                  fin_date
	declare @sysdate_tmp                   fin_date
	declare @companycode_tmp               fin_companycode
	declare @ou_status_tmp                 fin_status
	declare @pp_accountcode_tmp            fin_accountcode
	declare @ddoption_tmp                  fin_param_code
	declare @fb_tmp                        fin_financebookid
	declare @paymentroute_tmp      fin_param_code
	declare @paymode_tmp                   fin_param_code
	declare @ppvouchertype_tmp          fin_param_code
	declare @trantype_tmp                  fin_transactiontype
	declare @priority_tmp                  fin_param_code
	declare @relpayou_tmp                  fin_param_code
	declare @supplierarea_tmp              fin_param_code
	declare @basecurrencycode_tmp          fin_currency
	declare @bankcash_accountcode_tmp      fin_accountcode
	declare @errorno                       fin_errorno
	declare @fprowno               fin_rowno
	declare @placeholder1                  fin_placeholder
	declare @placeholder2                  fin_placeholder
	declare @placeholder3                  fin_placeholder
	declare @placeholder4                  fin_placeholder
	declare @ret_tmp  fin_bin
	declare @exchangerate_tmp              fin_exchangerate
	declare @exchangerate_max_tmp          fin_exchangerate
	declare @exchangerate_min_tmp          fin_exchangerate
	declare @exchangeratecat_tmp           fin_param_text
	declare @currencyunits_tmp             fin_int
	declare @bnkcshcurrency_tmp            fin_currency
	declare @exchangeratetype_tmp          fin_param_text
	declare @status_tmp                    fin_status
	declare @bu_id                         fin_buid
	declare @lo_id                         fin_loid
	declare @suppgroup_code                fin_suppliergroup
	declare @errormsg1                     fin_placeholder
	declare @getdate_tmp				   fin_date			-- Antoinette - SPYDMS412AT_000534 
	--declare @errmsg						   fin_desc255		-- Antoinette - SPYDMS412AT_000534 code commented for the defect id:ES_spy_00194
	declare @refid						   fin_refid,--code added by Esther J for the defect ES_bnkdef_00013 ; LC
		@today							   fin_date,
		@lo								   fin_loid,
		@swpay_tmp						   fin_flag,		--14H109_general_00137
		@ep_tmp							   fin_int			--14H109_general_00137
	
	
	declare @paytype_tmp				   fin_paytype
	declare	@albkdt						   fin_paramchar	-- Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008
	declare	@cur_date					   fin_date			-- Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008
	declare	@pymt_type					   fin_paramchar	-- Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008
	declare	@errmsg						   fin_desc255		-- Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008
	
	declare @ppsmulticurr_flag				fin_flag -- Code Added by samuel for bug id : es_spy_00308  
	declare	@Backdated_value				fin_int		  /* Code changes by Vignesh E for Rtrack ID EPE-34128 */
	declare @compcode                       fin_companycode  /* Code changes by Vignesh E for Rtrack ID EPE-34128 */

	select	 @m_errorid        = 0

	if	 @ctxt_language						= - 915
	select	 @ctxt_language    = null

	if	 @ctxt_ouinstance					= - 915
	select	 @ctxt_ouinstance               = null
	select	 @ctxt_service                  = ltrim( rtrim( @ctxt_service))

	if	 @ctxt_service						= '~#~'
	select	 @ctxt_service                  = null
	select	 @ctxt_user                     = ltrim( rtrim( @ctxt_user))

	if	 @ctxt_user							= '~#~'
	select	 @ctxt_user                     = null
	select	 @bankcash                      = ltrim( rtrim( @bankcash))

	if	 @bankcash							= '~#~'
	select	 @bankcash                      = null
	select	 @bankdescription				= ltrim( rtrim( @bankdescription))

	if	 @bankdescription					= '~#~'
	select	 @bankdescription   = null
	select	 @ddoption						= ltrim( rtrim( @ddoption))

	if	 @ddoption							= '~#~'
	select	 @ddoption                    = null

	if	 @exchangerate						= - 915
	select	 @exchangerate                  = null
	select	 @fb                            = ltrim( rtrim( @fb))

	if	 @fb								= '~#~'
	select	 @fb                            = null
	select	 @guid                          = ltrim( rtrim( @guid))

	if	 @guid								= '~#~'
	select	 @guid                          = null
	select	 @lastmodificationby            = ltrim( rtrim( @lastmodificationby))

	if	 @lastmodificationby				= '~#~'
	select	 @lastmodificationby            = null
	select	 @lastmodifieddate          = ltrim( rtrim( @lastmodifieddate))

	if	 @lastmodifieddate					= '1900-01-01'
	select	 @lastmodifieddate              = null

	if	 @payamount							= - 915
	select	 @payamount                  = null
	select	 @paycurrencycode               = ltrim( rtrim( @paycurrencycode))

	if	 @paycurrencycode					= '~#~'
	select	 @paycurrencycode               = null
	select	 @paydate                       = ltrim( rtrim( @paydate))

	if	 @paydate							= '1900-01-01'
	select	 @paydate                       = null
	select	 @paymentroute  = ltrim( rtrim( @paymentroute))

	if	 @paymentroute						= '~#~'
	select	 @paymentroute                  = null
	select	 @paymode                       = ltrim( rtrim( @paymode))

	if	 @paymode							= '~#~'
	select	 @paymode                       = null
	select	 @ppvouchertype                 = ltrim( rtrim( @ppvouchertype))

	if	 @ppvouchertype						= '~#~'
	select	 @ppvouchertype                 = null
	select	 @priority                      = ltrim( rtrim( @priority))

	if	 @priority							= '~#~'
	select	 @priority                      = null
	select	 @relpayou                      = ltrim( rtrim( @relpayou))

	if	 @relpayou							= '~#~'
	select	 @relpayou                      = null
	select	 @remarks                       = ltrim( rtrim( @remarks))

	if	 @remarks							= '~#~'
	select	 @remarks                       = null
	select	 @requestdate                   = ltrim( rtrim( @requestdate))

	if	 @requestdate						= '1900-01-01'
	select	 @requestdate                   = null
	select	 @status                        = ltrim( rtrim( @status))

	if	 @status							= '~#~'
	select	 @status                        = null
	select	 @supplier                      = ltrim( rtrim( @supplier))

	if	 @supplier							= '~#~'
	select	 @supplier                      = null
	select	 @supplierarea                  = ltrim( rtrim( @supplierarea))

	if	 @supplierarea						= '~#~'
	select	 @supplierarea             = null

	if	 @supplierdocumentamount			= - 915
	select	 @supplierdocumentamount        = null
	select	 @supplierdocumentdate          = ltrim( rtrim( @supplierdocumentdate))

	if	 @supplierdocumentdate				= '1900-01-01'
	select	 @supplierdocumentdate          = null
	select	 @supplierdocumentnumber        = ltrim( rtrim( @supplierdocumentnumber))

	if	 @supplierdocumentnumber			= '~#~'
	select	 @supplierdocumentnumber     = null
	select	 @suppliername                  = ltrim( rtrim( @suppliername))

	if	 @suppliername						= '~#~'
	select	 @suppliername                  = null

	if	 @timestamp							= - 915
	select	 @timestamp                     = null
	select	 @vouchernumber                 = ltrim( rtrim( @vouchernumber))

	if	 @vouchernumber						= '~#~'
	select	 @vouchernumber                 = null

	select	 @lcnumber						= ltrim( rtrim( @lcnumber)) --code added by Esther J for the defect ES_bnkdef_00013 ; LC	
	if	 @lcnumber							= '~#~' 
	select	 @lcnumber						= null
	
	/* Code added for the dts id 10H109_spy_00047 starts */
	select	 @tr_payment                 = ltrim( rtrim( @tr_payment))
	if	 @tr_payment                	 = '~#~'
	select	 @tr_payment                 = null

	if	 @tr_precent					= - 915
	select	 @tr_precent                = null

	if	 @tr_amount						= - 915
	select	 @tr_amount                 = null

	if	 @tr_tenure						= - 915
	select	 @tr_tenure                 = null

	select	 @tr_duedate                 = ltrim( rtrim( @tr_duedate))
	if	 @tr_duedate					= '01/01/1900'
	select	 @tr_duedate              	= null

	if	 @tr_lmtbalance					= - 915
	select	 @tr_lmtbalance              = null
						   
	select	 @surnumtype                 = ltrim( rtrim( @surnumtype))
	if	 @surnumtype					=  '~#~'
	select	 @surnumtype              	= null
	/* Code added for the dts id 10H109_spy_00047 ends*/

	
	/* code added for the bug id:ES_spy_00397: 11H103_spy_00010 starts here */
	select @lc_refid                = ltrim(rtrim(@lc_refid))
	if	@lc_refid = '~#~' 
		select @lc_refid = null			
		
	/* code added for the bug id:ES_spy_00397: 11H103_spy_00010 ends here */
    
    /*Code Added By Indira.G For Defect Id:ES_spy_00391 Starts*/
	IF @exrate = 0
		Select @exrate = null  

	IF @payamount1 = -915
		Select @payamount1 = null  

	IF @baseamount = -915
		Select @baseamount = null  
    /*Code Added By Indira.G For Defect Id:ES_spy_00391 Ends*/
	--Code added for EPE-48054 starts here
	if @ForwardContractNo = '~#~'
	select @ForwardContractNo = null
	--Code added for EPE-48054 ends here
    
        /* Code added for the dts id 11H103_spy_00048 starts */
	select	 @PRJOU                = ltrim( rtrim(@PRJOU))
	if	 @PRJOU             	= '~#~'
	select	 @PRJOU                = null
	
	select	 @PRJSUBPRJCD                = ltrim( rtrim(@PRJSUBPRJCD))
	if	 @PRJSUBPRJCD             	= '~#~'
	select	 @PRJSUBPRJCD                = null
	
	select	 @PRJSUBPRJDESC                = ltrim( rtrim(@PRJSUBPRJDESC))
	if	 @PRJSUBPRJDESC             	= '~#~'
	select	 @PRJSUBPRJDESC                = null
	
	-- code added for EPE-32731
	 Select @trustreceiptwithbankeraccept  = ltrim(rtrim(@trustreceiptwithbankeraccept))

 	IF @trustreceiptwithbankeraccept = '~#~' 
		Select @trustreceiptwithbankeraccept = null
	-- code added for EPE-32731
	declare  @prjou_tmp     fin_ouinstid,
			 @ccplaceholder	fin_desc255,
			 @successflag1	fin_flag
		
	select @prjou_tmp = ou_id
	from	emod_ou_Vw (nolock)
	where ouinstname	= @PRJOU
	/* Code added for the dts id 11H103_spy_00048 ends */


	/* Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008 starts here */
	
	 -- Code Added by samuel for bug id : es_spy_00308 starts here   
		 select @ppsmulticurr_flag = FLAG_YES_NO  
		 from PPS_FEATURE_LIST(nolock)  
		 Where FEATURE_ID  = 'SYNR_FID_0001'  
		 and  COMPONENT_NAME = 'SPY'   
	 -- Code Added by samuel for bug id : es_spy_00308 ends here  
	
	
	select @cur_date = convert(nvarchar(10),dbo.RES_Getdate(@ctxt_ouinstance),120)
--14H109_mcam_00001
	declare	@called_from	fin_desc40
	
	select 	@called_from	=	'NONE'
	if exists(select 1 from mca_sel_doc_tmp(nolock)
				where  hdn_guid = @guid)
	begin
		select @called_from = 'MCAM'
		update	mca_sel_doc_tmp
		set		error_id	= 1
		where	hdn_guid = @guid		
	end		

	/*code added for Logistics_prepayment starts*/
	if exists (	
				select 'X' from spy_prepay_tmp(nolock)
				where	old_guid	=	@guid
				and		service_name	in	('lpi_prpmn_sr_maint','LPI_PrPMn_Sr_Auth')
			  )
	begin
		select @called_from	= 'AUTOGEN'
	end

	/*code added for Logistics_prepayment ends*/

--14H109_mcam_00001	

	/* code added for the defect id EPE-79558:EPE-81543 begins here */
	if exists(	select	'X'
					from	fb_tmp(nolock)
					where   rsih_guid_tmp = @guid
					AND		pps_flag	in	('APP','REJ')
				)
	begin
		select	@called_from	= 'MOB_APPR'
	end
	/* code added for the defect id EPE-79558:EPE-81543 ends here */
	select	 @compcode                      = company_code
	from	 emod_ou_vw( nolock)
	where	 ou_id                          = @ctxt_ouinstance

	/*Code added for EPE-60038 begins */
	-- Checking restricted back dated transaction
	If @ctxt_service in ('spyedppmnsrmodify','spyedppmnsrmodaut')
	Begin
		If @ppvouchertype = 'Deposit'
			Exec restrict_bk_dated_tran_sp @ctxt_ouinstance,@ctxt_language,'PM_SDV',@requestdate,'SPY',@compcode,@m_errorid Output
		
		If @ppvouchertype = 'PrePayment'
			Exec restrict_bk_dated_tran_sp @ctxt_ouinstance,@ctxt_language,'PM_SPPV',@requestdate,'SPY',@compcode,@m_errorid Output

		If @m_errorid <> 0
			Return

	End
	/*Code added for EPE-60038 ends */

	Select @albkdt = parameter_code 
	from cps_processparam_sys(nolock) 
	where	parameter_type		= 'PMSYS' 
	and		parameter_category	= 'AlBakDtdTrans'
	and		language_id			= @ctxt_language
	and		company_code		=@compcode--EPE-38698
	--and		ou_id				= @ctxt_ouinstance EPE-37936
	
	select 	@pymt_type  		= ltrim(rtrim(parameter_code))
	from 	fin_quick_code_met (nolock)
	where 	component_id		= 'SPY'
	and 	parameter_type     	= 'COMBO'
	and 	parameter_category 	= 'PAYTYPE'
	and 	parameter_text     	= @paymentroute
	and 	language_id        	= @ctxt_language
	
	--14H109_spy_00056
	declare @allowcrosscurr		fin_flag
	
	select	@allowcrosscurr			= parameter_text
	from	fin_processparam_sys (NOLOCK)
	WHERE 	ou_id            		= @ctxt_ouinstance
	AND 	component_id       		= 'SPY'
	AND 	parameter_type     		= 'FNDEF'
	AND 	parameter_category 		= 'FNDEF'
	and		parameter_code			= 'CCPSPY'
	--14H109_spy_00056		
	--Added for 12h124_PO_00002 starts
	if @ctxt_service in( 'SPYEdPPMnSrModAut','SPYEdPPMnSrModify','spyauppmnsrreturn')  --epe-9608
	begin
		declare @auto_gen_flag fin_flag
			
		select	@auto_gen_flag	=	auto_gen_flag 
		from	spy_prepay_vch_hdr(nolock)
		where	ou_id 			= @ctxt_ouinstance
		and	voucher_no			= @vouchernumber
		and	tran_type		in ('PM_SPPV')
		
		select @auto_gen_flag =	isnull(@auto_gen_flag,'N')
		
		if @auto_gen_flag	=	'Y'
		begin
			if exists (	Select	'x'
						from	spy_prepay_vch_hdr(nolock)
						where	ou_id 			= @ctxt_ouinstance
						and		voucher_no		= @vouchernumber
						and		tran_type		in ('PM_SPPV')
						and		request_date	=	@requestdate
						and		fb_id			=	@fb
						and		pay_currency	=	@paycurrencycode
						and		pay_amount		=	@payamount
						and		pay_date		=	@paydate
						)
			begin
				select 	@ctxt_ouinstance	=	@ctxt_ouinstance
			end
			else
			begin
				exec fin_german_raiserror_sp 'SPY',@ctxt_language,5059
				RETURN
			end
			
			insert into  spy_prepayvch_dtl_tmp
			(
			ordering_ou,		ref_doc_no,			doc_type,      
			pay_amount,			batch_id,			Milestone_code,
			Milestone_desc,		line_no
			)
			select    
			ordering_ou,		ref_doc_no,			doc_type,      
			pay_amount,			@guid,			Milestone_code,
			Milestone_desc,		line_no
			from     spy_prepay_vch_dtl
			where	 ou_id      	= 	@ctxt_ouinstance
			and	 voucher_no     = 	@vouchernumber
			and	 tran_type      in ('PM_SPPV' )		
		end
	end
	--Added for 12h124_PO_00002 ends
/* Code changes by Vignesh E for Rtrack ID EPE-34128 starts here */



if @albkdt <>'NO'
BEGIN
	Select @Backdated_value = paymode_typevalue 
	from cps_backdated_payment(nolock) 
	where	company_code	=@compcode
	--and		ou_id				= @ctxt_ouinstance EPE-37936
	and		language_id	   =@ctxt_language
	and		paymode_category=@albkdt
	and		paymode_typecode='SPY'
	and		paymode_status	='AC'
end
/* Code changes by Vignesh E for Rtrack ID EPE-34128 ends here */

	if @paydate < @cur_date
	Begin
		if @albkdt = 'No'
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end	
		else 
		if @albkdt = 'CSH' and @pymt_type NOT IN ('C')
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end
		else
		if @albkdt = 'BNK' and @pymt_type NOT IN ('B')
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end
		else
		if @albkdt = 'BNKCSH' and @pymt_type NOT IN ('C','B')
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end
/* Code changes by Vignesh E for Rtrack ID EPE-34128 starts here */
		if (DATEDIFF(day, @paydate, @cur_date)>@Backdated_value)
			Begin
				--Back Dated Payments allowed only for %a days. Modify Pay Date.
				exec fin_german_raiserror_sp 'SPY',@ctxt_language,102,@Backdated_value,'','','','','','',@errmsg output
				return
			End
/* Code changes by Vignesh E for Rtrack ID EPE-34128 ends here */			
	End
		--CUPE-489
		if isnull(@paydate,'') = ''
		begin
			exec fin_german_raiserror_sp 'CR',@ctxt_language,434 
			return
		end
		--CUPE-489
	/* Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008 ends here */
	/*EPE-48054 Code Begins*/
	IF	@ctxt_service	= 'spyauppmnsrreturn'
	Begin
			exec frwd_cntrct_amt_back_update
			@ctxt_language,   
			@ctxt_ouinstance, 
			@ctxt_service,    
			@ctxt_user,		
			@vouchernumber,	
			Null,		
			'SPPV',	
			Null,		
			@m_errorid output
			
		If @m_errorid <> 0
		begin
			return
		end
	End


	/*EPE-48054 Code Ends*/


	IF @ctxt_service = 'spyedppmnsrmodify'
	begin
		if	 not exists(
			select	 'x'
			from	spy_prepay_vch_hdr( nolock)
			where	ou_id  = @ctxt_ouinstance
			and	    tran_type                      in ('PM_SPPV','PM_SDV')
			and	    voucher_no						= @vouchernumber
			and	    status                         in('F','DF','RT'))
		begin	
			select	@m_errorid = 352
			return	
		end
	end
	ELSE IF @ctxt_service	= 'SPYEdPPMnSrModAut'
	begin
		if	 not exists(
			select	 'x'
			from	spy_prepay_vch_hdr( nolock)
			where	ou_id                          = @ctxt_ouinstance
			and		tran_type                      in ('PM_SPPV','PM_SDV')
			and		voucher_no                     = @vouchernumber
			and		status                         in('F','RT'))

		begin
			select	@m_errorid = 352
			return	
		end
	end	
	ELSE IF	@ctxt_service	= 'spyauppmnsrreturn'
	BEGIN
		if	 not exists(
			select	 'x'
			from	 spy_prepay_vch_hdr( nolock)
			where	 ou_id                          = @ctxt_ouinstance
			and		 tran_type                      in ('PM_SPPV','PM_SDV')
			and		 voucher_no                     = @vouchernumber
			and		 status                         in('F'))

		begin
			select	@m_errorid = 355
			return	
		end
	END
	/*code moved here by deepika for the dtsid:ES_spy_00194 begins here*/
	select	 @companycode_tmp               = ltrim( rtrim( company_code))
	from	 emod_ou_vw( nolock)
	where	 ou_id             = @ctxt_ouinstance
	and	 dbo.fin_getdatepart( @paydate) between	 effective_from   and	 isnull( effective_to, '01-01-9999')
	/*code moved here by deepika for the dtsid:ES_spy_00194 begins here*/
	/* Code added for DTS Id: 9H123-1_SPY_00026 Begins Here */
	SELECT 	@lo 		= lo_id
	FROM   	emod_lo_bu_ou_vw
	WHERE  	ou_id 		= @ctxt_ouinstance
	AND    	dbo.RES_Getdate(@ctxt_ouinstance) BETWEEN effective_from 
			AND ISNULL(effective_to, dbo.RES_Getdate(@ctxt_ouinstance))
	/* Code added for DTS Id: 9H123-1_SPY_00026 Ends Here */
	
	--EPE-44709
	declare @pps_code  fin_desc40

	if  exists(		Select  '*'
					From    pps_finance_feature_list a(nolock)
					where   FEATURE_ID      = 'PPS_SPY_0001'
					and		company_code	= @companycode_tmp
				)
	begin
		select  @pps_code	=	FLAG_YES_NO
		From    pps_finance_feature_list a(nolock)
		where   FEATURE_ID      = 'PPS_SPY_0001'
		and		company_code	= @companycode_tmp
	end
	else
	begin
		select  @pps_code	=	FLAG_YES_NO
		From    pps_finance_feature_list a(nolock)
		where   FEATURE_ID      = 'PPS_SPY_0001'
		and		company_code	is null
	end	
	--EPE-44709

	/* Code Added By Jeganathan.M On 16/04/2007 For the bugid:- SPYDMS412AT_000275 Starts Here */
	if @ctxt_service in ('SPYEDPPMNSRMODIFY', 'SPYEDPPMNSRMODAUT')
	begin
		if isnull(@supplierdocumentnumber,'') <> ''
		begin
			/*code commented and added by deepika for dtsid:ES_spy_00194 begins here*/
			IF EXISTS(
			    SELECT 'x'
			       FROM   pps_feature_list
			       WHERE  component_name = 'COMMON'
			              AND flag_yes_no = 'YES'
			              AND FEATURE_ID = 'PPS_FID_0112'
			   )
			BEGIN
			    IF EXISTS (
			           SELECT 'x'
			    FROM   spy_prepay_vch_hdr a(NOLOCK),
			    emod_lo_bu_ou_vw b(NOLOCK)
			           WHERE  a.ou_id = b.ou_id
			                  AND a.tran_type			IN ('PM_SPPV', 'PM_SDV')
			                  --AND a.status <> 'DL'--TLET-612
							  and a.status not in ('DL','RV')  --TLET-612
			                  AND a.supp_doc_no = @supplierdocumentnumber
			                  AND a.supp_code = @supplier
			                  AND a.voucher_no <> @vouchernumber
			                  AND b.company_code = @companycode_tmp
							  --TLET-621 starts
							  and	not exists	(SELECT	'x'
												FROM 	si_doc_hdr_vw vw(NOLOCK)
												WHERE 	vw.tran_no	=	voucher_no
												and	vw.tran_type	in	('PM_SPPV','PM_SDV')
												and	vw.tran_ou 		= 	a.ou_id
												and	paid_status		=	'RVD'	)
							--TLET-621 ends
			       )
			    BEGIN
			        EXEC fin_german_raiserror_sp 'SPY',
			             @ctxt_language,
			             52,
			             '',
			             '',
			             '',
			             '',
			             '',
			     '',
			             '',
			             ''
			        
			        RETURN
			    END
			END
			ELSE
			BEGIN
			    IF EXISTS (
			           SELECT 'x'
			           FROM  spy_prepay_vch_hdr(NOLOCK)
			           WHERE  ou_id = @ctxt_ouinstance
			                  AND tran_type      IN ('PM_SPPV', 'PM_SDV')
			                 -- AND STATUS <> 'DL' --TLET-612
							  and status not in ('DL','RV') --TLET-612
			                  AND supp_doc_no = @supplierdocumentnumber
			                  AND voucher_no <> @vouchernumber --Ravikrishnan - SPYDMS412AT_000473
			                  AND supp_code = @supplier -- Porselvi.J - ES_spy_00012
							  --TLET-621 starts
							  and	not exists	(SELECT	'x'
												FROM 	si_doc_hdr_vw vw(NOLOCK)
												WHERE 	vw.tran_no	=	voucher_no
												and	vw.tran_type	in	('PM_SPPV','PM_SDV')
												and	vw.tran_ou 		= 	ou_id
												and	paid_status		=	'RVD'	)
							--TLET-621 ends
			       )
			    BEGIN
			        EXEC fin_german_raiserror_sp 'SPY',
			             @ctxt_language,
			             52,
			             '',
			             '',
			             '',
			             '',
			             '',
			             '',
			             '',
			             ''
			        
			        RETURN
			    END
			END	

	/*		begin
				exec 	fin_german_raiserror_sp 'SPY',@ctxt_language,52,'','','','','','','',''
				return 
			end */
/*code commented and added by deepika for dtsid:ES_spy_00194 ends here*/
		end
	end 
	/* Code Added By Jeganathan.M On 16/04/2007 For the bugid:- SPYDMS412AT_000275 Ends Here */
	
	select @sysdate_char                  = convert( nvarchar( 10), dbo.RES_Getdate(@ctxt_ouinstance), 101)
	select @sysdate_tmp					  = convert( datetime, @sysdate_char)

	/*code moved up by deepika for the dtsid:ES_spy_00194 */
	/*select	 @companycode_tmp       = ltrim( rtrim( company_code))
	from	 emod_ou_vw( nolock)
	where	 ou_id                          = @ctxt_ouinstance
	and	 dbo.fin_getdatepart( @paydate) between	 effective_from   and	 isnull( effective_to, '01-01-9999')*/


	select	 @supplierarea_tmp              = ou_id
	from	 emod_ou_vw(nolock)
	where	 ouinstname                     = @supplierarea

	select	@bu_id							= bu_id, 
		@lo_id								= lo_id
	from	emod_lo_bu_ou_vw(nolock)
	where	ou_id                          = @supplierarea_tmp

	--begin find the codes  
	select @ddoption_tmp 			= dbo.spy_getcode( 'COMBO','DDCHARGES',@ddoption,@ctxt_language)
	select @paymentroute_tmp        = dbo.spy_getcode( 'COMBO','PAYTYPE',@paymentroute,@ctxt_language)
	select @ppvouchertype_tmp       = dbo.spy_getcode( 'COMBO','PPVOUTYPE',@ppvouchertype,@ctxt_language)
	select @priority_tmp            = dbo.spy_getcode( 'COMBO','PRIORITY',@priority,@ctxt_language)

	select	 @paymode_tmp   = ltrim( rtrim( rcpt_pymt_mode_code))
	from	 bnkdef_rcpt_pay_mode_vw(nolock)
	where	 rcpt_pymt_mode                 = @paymode
	and		language_id                     = @ctxt_language

	/*code added by Esther J on 24/03/2009 for the defect id ES_bnkdef_00013 starts*/
	if @paymode_tmp is null  
	begin
		select @paymode_tmp = parameter_code
		from	fin_quick_code_met(nolock)
		where	component_id		=	'BNKDEF'
		and		parameter_type  	= 	'COMBO'
		and 	parameter_category 	= 	'PAYMODE'
		and		parameter_text		=	@paymode
		and		language_id			= 	@ctxt_language
	end
	/*code added by Esther J on 24/03/2009 for the defect id ES_bnkdef_00013 ends*/


	select	 @fb_tmp                        = @fb

	select	 @companycode_tmp               = company_code
	from	 emod_ou_vw( nolock)
	where	 ou_id                          = @ctxt_ouinstance
	and	 dbo.fin_getdatepart( @paydate)between	 effective_from	and	 isnull( effective_to, '01-01-9999')

	select	 @relpayou_tmp                  = ltrim( rtrim( ouinstid))
	from	 fw_admin_view_ouinstance( nolock)
	where	 ouinstname                     = @relpayou

	select	 @supplierarea_tmp              = ltrim( rtrim( ouinstid))
	from	 fw_admin_view_ouinstance( nolock)
	where	 ouinstname                     = @supplierarea

	select	 @suppgroup_code                = suppgroup_code
	from	 supp_accgroup_view(nolock)
	where	 upper( loid)		= upper( @lo_id)
	and	 upper( suppliercode)	= upper( @supplier)
	/*
	VOUCHER TYPE  
	SpyBR0053 Voucher Type null check   
	error Select Voucher Type. Critical  
	*/
	if	 @ppvouchertype                 is null
	begin	
		select	 @m_errorid  = 3690970
		return	
	end
	/*
	Request Date   
	SpyBR0054 Request Date null check  
	Enter Request Date. Critical  
	*/
	if	 @requestdate                   is null
	begin	
		select	 @m_errorid  = 79
		return	
	end
	/*
	SpyBR0055 Request Date validity check   
	If Request Date is later than system date,     
	error Request Date cannot be later than the system date. Modify Request Date. Critical  
	*/
	if	 @requestdate                   > @sysdate_tmp
	begin
		select	 @m_errorid  = 230
		return	
	end
	/*
	SpyBR0056 EmodSerCoValTrn1: Fetch BU and Company Code   
	input: OU=login OU,   Date= Request Date. Get   
	output: BU,   Company Code. 
	*/

	/*SpyBR0057 FB null check   error Select Finance Book. Critical  */
	if	 @fb                            is null
	begin	
		select	 @m_errorid  = 254
		return	
	end	
	/*
	SpyBR0058 :FB validity check   
	Invoke service EmodSerBuOuValTrn1 in Organization select-up.   
	Give input: FB Id, OU=Payment Release Point, date = Pay Date.   
	Get output: Yes/No. Display error, if any, returned by the service  
	*/

	exec @ret_tmp = emod_sysact_spfbval @relpayou_tmp,@paydate,@fb

	if @ret_tmp <> 0
	begin
		select	@m_errorid	=	case @ret_tmp
						when	1	then	3690971
						when	2	then	3690972
						when	3	then	414
						when	4	then	509
						when	5	then	508
						when	6	then	381
						when	7	then	384
						when	8	then	384
					end
	end

	/*	
	SpyBR0035 Supplier null check   
	error Enter Supplier Code. Critical  
	*/

	if	 @supplier                      is null
	begin	
		select	 @m_errorid                     = 3690973
		return	
	end	
	/*	
	SpyBR0036 ***: Supplier existence & Active status check   
	Invoke service SuppSer100 in Supplier component. Give input: Supplier Code, ErrMsg=Yes.  
	Get output: validation for Supplier existence & Active status, Supplier Name,   
	Supplier Account Group, Supplier Type, Supplier Classification, Identification Agency,   
	Identification No., Supplier BU, Supplier Company. Display error,   
	if any, returned by service. If the service does not return error,   
	and the Supplier Type = "One time", show error  
	*/

	/*Code added for DTS ID: ES_fcc_00084(10H109_FCC_00001) starts here*/
	declare @allow_mulpvcls	fin_paramcode

	select	@allow_mulpvcls		= parameter_code
	from	cps_processparam_sys(nolock)
	where	company_code		= @companycode_tmp
	and		parameter_type		= 'BFGMPC'
	and		parameter_category	= 'PYMT'
	and		parameter_code		= 'Y'

	if @allow_mulpvcls is null or @allow_mulpvcls = ''
		select @allow_mulpvcls = 'N'

	if @allow_mulpvcls = 'N'
	begin
	/*Code added for DTS ID: ES_fcc_00084(10H109_FCC_00001) ends here*/	
		/*Code added by Ananth P. against: ES_spy_00173 Begins*/
		if	exists 
				(
				select	'X' 
				from	fcc_bfg_prd_close_status (nolock)     
				where	company_code 	= @companycode_tmp    
				and  	ou_id  			= @ctxt_ouinstance    
				and  	bfg_code  		= 'PYMT'    
				and  	fb_id  			= @fb
				and		@paydate		between		fcc_finprd_startdt	and	fcc_finprd_enddt		
				and  	status  		= 'O'
				)    
		begin
			select	@ctxt_ouinstance	= @ctxt_ouinstance
		end
		else
		begin
	--		raiserror ('Financial Period is not in open status for the given Pay date',16,1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,64 
			return    
		end
		/*Code added by Ananth P. against: ES_spy_00173 Ends*/
	end/*Code added for DTS ID: ES_fcc_00084(10H109_FCC_00001)*/
	
/* Code changed by Esther J on 13/08/2007 for defect id SPYDMS412AT_000518 : Performance Tuning starts*/
/*
-- 	if	 not exists(
-- 		select	 'X'
-- 		from	 supp_otherdtls_vw( nolock)
-- 		where	 upper( supplier_code) = upper( @supplier)
-- 		and	 upper( buid) 	= 	upper( @bu_id)
-- 		and	 upper( loid) 	= 	upper( @lo_id)
-- 		and	 status       	= 	'AC'
-- 		)
-- 	begin	
-- 		select	 @m_errorid                     = 3690974
-- 		return	
-- 		
-- 	end
-- 	/*
-- 	SpyBR0037 : Fetch Supplier OU status   
-- 	Invoke service SuppSer104 in supplier component.   
-- 	Give input: Supplier Code, OU= Supplier Registered At OU.   
-- 	Get output: OU level Status. Display error, if any, returned by service. 
-- 	*/
-- 	select	 @ou_status_tmp                 = ltrim( rtrim( status))
-- 	from	 supp_otherdtls_vw( nolock)
-- 	where	 upper( supplier_code) = upper( @supplier)
-- 	and	 upper( buid) = upper( @bu_id)
-- 	and	 upper( loid) = upper( @lo_id)
-- 
-- 	/*
-- 	SpyBR0038 Supplier Hold Pay status check   
-- 	If OU level Status is "Hold Pay" or "Hold Buy",display error   
-- 	*/
-- 	if	 @ou_status_tmp                 in( 'HP', 'HB')
-- 	begin	
-- 		select	 @m_errorid                     = 3690975
-- 		return	
-- 	end	
-- 
-- 	/*SpyBR0039 Fetch Supplier Name Fetch Supplier Name    */
-- 	select	 @suppliername         = 	ltrim( rtrim( supplier_name))
-- 	from	 supp_otherdtls_vw( nolock)
-- 	where	 upper( supplier_code) = 	upper( @supplier)
-- 	and	 loid        = 	@lo_id

*/
	
	--Code for Def Id : 14H109_General_00137 starts here
	
	select 	@swpay_tmp 			= parameter_value
	from 	ips_processparam_vw ( nolock )
	where 	company_code		= @companycode_tmp
	and		parameter_code		= 'SWISSPAYAPPLI'
	
	if @swpay_tmp	=	'Y'
	begin
		select @ep_tmp = 1
	end
	else 	if @swpay_tmp	=	'N'
	begin
		select @ep_tmp = 0
	end
	
	--Code for Def Id : 14H109_General_00137 ends here
	
	select @ou_status_tmp = supp_ou_supstatus
	from supp_ou_suplmain (nolock)
	where 	supp_ou_loid 			= @lo_id
	AND   	supp_ou_ouinstid 		= @supplierarea_tmp
	and 	supp_ou_supcode 		= @supplier
	
	if @ou_status_tmp in ('HP','HB')  
	begin	
		select	 @m_errorid                     = 3690975
		return	 
	end	
	
	if	 @ou_status_tmp        <> 'AC'
	begin
		select	 @m_errorid                     = 3690974
		return	
	end	

	select	 @suppliername         =  ltrim( rtrim( supp_spmn_supname))
	from	 supp_spmn_suplmain( nolock)
	where	 supp_spmn_supcode = @supplier
	and		 supp_spmn_loid    = @lo_id
/* Code changed by Esther J on 13/08/2007 for defect id SPYDMS412AT_000518 : Performance Tuning ends*/


	/*
	SpyBR0059 Pay Currency null check Check   
	error Select Pay Currency. Critical  
	*/

	if	 @paycurrencycode               is null
	begin	
		select	 @m_errorid                     = 591
		return	
	end

	/*
	SpyBR0060  
	Invoke service EmodSerValCurCoTrn2 of Organization select-up component.   
	Give input: Pay currency, Login Ou, Date =Request date.   
	Get Output: validation of Pay currency code. If the Output is false   
	display error message returned by service  
	*/
	exec 	@ret_tmp = emod_sysact_spcompcurrmap      @ctxt_ouinstance,@requestdate,@paycurrencycode

	if @ret_tmp <> 0
	begin
		select	@m_errorid	=	case @ret_tmp
						when	1	then	426
						when	2	then	3690976
						when	3	then	3690977
						when	4	then	3690978
						when	5	then	3690979
						when	6	then	381
						when	7	then	384
						when	8	then	3690980
					end
	end

	/*	
	EXCHANGE RATE VALIDATION  
	SpyBR0061 Null check for Exchange Rate   
	error Enter Exchange Rate. Critical  
	*/

	if	 @exchangerate                  is null
	begin	
		select	 @m_errorid	= 	673
		return	
	end	

	/*
	SpyBR0062 Exchange Rate validity check (Base cuurency)   
	If Pay Currency is same as Base Currency,     
	check if Exchange Rate is "1",     
	error. For Base Currency,   Exchange Rate should be "1". Modify Exchange Rate. Critical  
	*/
	select	 @basecurrencycode_tmp          = currency_code
	from	 emod_basecurr_vw( nolock)
	where	 company_code                = @companycode_tmp
	and	 flag                           = 'B'

	if	 @paycurrencycode               = @basecurrencycode_tmp
	and	 @exchangerate                  < > 1
	begin	
		select	 @m_errorid	= 	118
		return	
	end	

	/*
	SpyBR0044 OpsSerTrn1 : Exchange Rate Type fetch rule    
	If Pay Currency is not Base Currency, invoke service OpsSerTrn1 in OU Parameter select-up   
	component. Provide input : (1) Param Code = selecttlementERType, (2) OU- login OU.   
	Get output : ParamChar=Exchange Rate Type for liability selecttlement.   
	Display error, if any, returned by the service.   
	*/

	if	 @paycurrencycode     < > @basecurrencycode_tmp
	begin
		
		select	 @exchangeratetype_tmp          = ltrim( rtrim( parameter_value))
		from	 ops_processparam_vw( nolock)
		where	 ou_id                          = @ctxt_ouinstance
		and		 parameter_code                 = 'SETTLEMENTERTYPE'
		and		 parameter_type                 = 'PMSYS'
		/*		
		SpyBR0045 Exchange Rate Type fetch check   
		Check if Exchange Rate Type is fetched, else display error message  
		*/
		if	 @exchangeratetype_tmp          is null
		begin	
			select	 @m_errorid	= 	105
			return	
		end

		exec @ret_tmp = erate_sysact_spgetexcgrate     
		@ctxt_ouinstance,
		@ctxt_user,
		@ctxt_language,
		@paycurrencycode,
		@basecurrencycode_tmp,
		@paydate,
		@exchangeratetype_tmp,
		@exchangerate_tmp     output,
		@exchangerate_max_tmp          output,
		@exchangerate_min_tmp          output,
		@exchangeratecat_tmp           output,
		@currencyunits_tmp             output,
		'SPY'
		
		if @ret_tmp <> 0
		begin
			select	@m_errorid	=	case @ret_tmp
					when	1	then	3690981
					when	2	then	3690982
					when	3	then	620
					when	4	then	3690983
					when	5	then	101
					when	6	then	381
					when	7	then	384
					when	8	then	463
				end
			return
		end

		/* Code added by Esther J for the DTS id 9H123-1_spy_00017  starts */
		If @ForwardContractNo IS NULL --48054
		BEGIN
		IF	 @exchangerate                  < @exchangerate_min_tmp
		OR	 @exchangerate                  > @exchangerate_max_tmp
		BEGIN	
			select	 @m_errorid	= 3691154 --101
			RETURN	
		END	
		END
		/* Code added by Esther J for the DTS id 9H123-1_spy_00017  ends */
	end
	/*
	SpyBR0040 Null check for Pay Date   
	error Enter Pay Date. Critical  
	*/
	if	 @paydate                       is null
	begin	
		select	@m_errorid	=	68
		return	
	end

	/*
	SpyBR0064 Pay Date validity check   
	If Pay Date is earlier than Request Date,     
	error Pay Date cannot be earlier than Request Date. Modify Pay Date. Critical  
	*/
	if	 @paydate                       < @requestdate
	begin
		select	@m_errorid	=	199
		return	
	end

	--Code Added by Antoinette for the bug id SPYDMS412AT_000534 starts here
	select @getdate_tmp = convert(nvarchar(10),dbo.RES_Getdate(@ctxt_ouinstance),120)
/*code modified for the dtsid:ES_spy_00248[10H109_spy_00034:10H109_spy_00044] begins here*/
	/*code added for the dtsid:9H123-1_SPY_00026 starts here*/
	if @paydate > @getdate_tmp
	begin	
		if EXISTS(
		   select 'X'
		   from   cps_processparam_sys(NOLOCK)
		   where  company_code				= @companycode_tmp
				  AND parameter_type		= 'PMSYS'
				  AND parameter_category	= 'PDCSPPV'
				  AND parameter_code		in('Y','WDocRef')--dtsid:ES_spy_00248[10H109_spy_00034]
				)
		begin
			select @ctxt_language	=	@ctxt_language
		end
		else
		begin
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,1212
			return
		end
/*code modified for the dtsid:ES_spy_00248[10H109_spy_00034:10H109_spy_00044] ends here*/
		if EXISTS(
				select 'X' 
				from  supp_spmn_suplmain (nolock)
				where supp_spmn_supcode = @supplier
				and	  supp_spmn_suptype = 'OT'
				and	  supp_spmn_loid	= @lo 
				
				 )
			begin
				exec fin_german_raiserror_sp 'SPY',@ctxt_language,1220
				return
			end
	end
	/*code added for the dtsid:9H123-1_SPY_00026 ends here*/

	/*code added by Esther J for the DTS id 9H123-!_spy_00014 starts */
	if @ppvouchertype_tmp = 'PP'
	begin
		select @ctxt_ouinstance = @ctxt_ouinstance
	end
	else
	begin
		if	@paydate > @getdate_tmp
		begin

			-- "Pay Date cannot be later than the system date for the selected Voucher Type. Modify the Pay Date / Voucher type and Proceed"
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,3004
			return
		end
	end	
	
	--Code for Def Id : 14H109_General_00137 starts here
	if exists (	Select 'X'
				FROM bnkdef_rcpt_pay_mode_vw (nolock)
				WHERE 	language_id  			= 	@ctxt_language
				and 	elect_flag_code			=	@ep_tmp
				and     ou_id					= 	@ctxt_ouinstance
				and		rcpt_pymt_mode_code		=	@paymode_tmp
				and		allow_future_date_flag			=	1
			  )
	--Code for Def Id : 14H109_General_00137 ends here
	begin
		select @ctxt_ouinstance = @ctxt_ouinstance
	end
	else
	begin
		if	@paydate > @getdate_tmp
		begin
			-- "Pay Date cannot be later than the system date for the selected Pay Mode. Modify the Pay Date and Proceed"
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,3000
			return
		end
	end	

	/*code added by Esther J for the DTS id 9H123-!_spy_00014 ends*/

	/*code commented by Esther J for the DTS id 9H123-!_spy_00014 starts*/
	/*
	--if	@paydate <> @getdate_tmp --commented and added for bugid:ES_spy_00138
	if	@paydate > @getdate_tmp
	begin
		-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
		exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
		return
	end
	--Code Added by Antoinette for the bug id SPYDMS412AT_000534 ends here
	*/
	/*code commented by Esther J for the DTS id 9H123-!_spy_00014 ends*/

	/*
	SpyBR0065 Null check for Payment Release Point   
	error Enter Payment Release Point. Critical  
	*/
	if	 @relpayou                      is null
	begin	
		select	@m_errorid	=	74
		return	
	end
	/*
	SpyBR0067 ArdSerGetSPATrn2: Fetch Supplier Prepayment account   
	If Voucher Type is "Prepayment", invoke service ArdSerGetSPATrn2 in ARD.   
	Give input: Supplier Account Group, FB, Currency, OU=login OU, Date=Request Date,   
	Supplier Classification, Supplier BU, Supplier Company.   
	Get output: Supplier Prepayment Account. Display error, if any, returned by service  
	Getting the Supplier Group  
	*/

	select 	@pp_accountcode_tmp	=	@accountcode

	
	DECLARE @acctype	fin_accounttype
	--declare @errorflag	fin_flag--code commented for dtsid:ES_spy_00194
	
	if 	@ppvouchertype_tmp	=	'PP'
	begin
		select	@acctype	=	'SPA'
	end
	else	if @ppvouchertype_tmp	=	'PPD'	
	begin
		select	@acctype	=	'SDA'
	end

	exec ard_supp_val_default_account
	@ctxt_language,
	@ctxt_ouinstance,
	@ctxt_service,
	@ctxt_user,
	@supplier,
	@paycurrencycode,
	@fb,
	'Y',
	'SPY',
	@requestdate,
	@acctype,
	@pp_accountcode_tmp,
	@m_errorid	OUTPUT
	
	if @m_errorid <> 0
	begin
		return
	end
	/*
	67-69 done. (not Implemented)  
	SpyBR0070 Null check for Pay Route   
	error Select Payment Route. Critical  
	*/

	if	 @paymentroute           is null
	begin	
		select	@m_errorid = 277
		return	
	end	
	/*
	SpyBR0071 Null check for BankCash Code  
	error Select Bank/Cash Code. Critical  
	*/
	if	 @bankcash       is null
	begin
		select	@m_errorid = 248
		return	
	end
	/*
	SpyBR0072 ***: Validity check for BankCash Code   
	Invoke service *** in BankCash Definition.   
	Give input: Payment Route,   BankCash Code. 
	Get output: validation of BankCash Code.   
	Display error,   if any,   returned by service (not implemented)    
	SpyBR0073 Null check for Pay Mode   
	error Select Pay Mode. Critical  
	*/
	if	 @paymode                       is null
	begin	
		select	@m_errorid = 273
		return	
	end
	/*
	SpyBR0074 ***: Validity check for Pay Mode   
	Invoke service BNKDEFSERVALTrn1 from Bank Cash Definition.   
	Give input: OU=Release Payment OU, Electronic Payment= No, Payment Route, BankCashCode,  
	Pay Mode, Finance Book. Get output:BankCash Code & Pay Mode validated.   
	Display error, if any, returned by service.  
	SpyBR0075 Null check for Priority Check   
	Select Priority. Critical 
	*/
	if	 @priority                      is null
	begin	
		select	@m_errorid = 281
		return	
	end
	/*
	SpyBR0075a  
	If Pay Mode is not "Cash", check if Pay Charges option is selected, else error  
	pay charge is not coming as I/o  
	SpyBR0075b  
	Check if Priority selected is "High", "Medium" or "Low", else error  
	*/
	IF	 @priority_tmp                  not in( 'H', 'L', 'M')
	begin	
		select	@m_errorid = 281
		return	
	end
	/*
	SpyBR0076 : Fetch Currency for BankCash Code   
	Invoke service BnkDefSerCurrTrn1 in Bank cash Definition component.   
	Give input: OU=login OU, Payment Route, BankCash Code. Get output: BankCash Currency.  
	*/
	select	 @bnkcshcurrency_tmp            = ltrim( rtrim( currency_code))
	from	 bnkdef_sysact_bnkcshptt_vw( nolock)
	where	 company_code                 = @companycode_tmp
	and		bank_cash_code         = @bankcash
	and		bank_ptt_cash                  = @paymentroute_tmp
	and		language_id					   = @ctxt_language

	/*code added by Esther J for the DTS id 9H123-!_spy_00014 starts*/
	if	@paydate > @getdate_tmp and @bnkcshcurrency_tmp <> @paycurrencycode
	begin
		-- For a Future dated check Bank Currency and Pay Currency should be same. Modify the Bank Currency and Proceed.
		exec fin_german_raiserror_sp 'SPY',@ctxt_language,3003
		return
	end	
	/*code added by Esther J for the DTS id 9H123-!_spy_00014 ends*/

	/*
	SpyBR0077 Validate Currency for Pay Mode   
	(1)If Pay Mode is not "Direct Debit", BankCash Currency must be same as Pay Currency.   
	(2) If Pay Mode is "Direct Debit" and Pay Currency is Base Currency, BankCash Code   
	must be in Base Currency. If these conditions are not satisfied, show error  
	*/
	/*code changed by Esther J on 24/03/2009 for the defect id ES_bnkdef_00013 starts*/
	--if	 @paymode_tmp                   < > 'DB'
	/* Code Commented and added by samuel for bug id : es_spy_00308 starts here */  
 --if  @paymode_tmp                   not in  ('DB','LC')  
 --/*code changed by Esther J on 24/03/2009 for the defect id ES_bnkdef_00013 ends*/  
 --begin  
 -- if  @bnkcshcurrency_tmp            < > @paycurrencycode  
 -- begin   
 --  select @m_errorid = 14  
 --  return   
 -- end  
 --end   

	--14H109_SPY_00056
	if	isnull(@paymode_tmp,'') = 'DB'  and isnull(@allowcrosscurr,'N') = 'Y' and @tr_payment = 0
	begin
		select	@m_errorid = 0
	end	
	else
	begin  
		if  @paymode_tmp not in  ('ep'/*epe-17774*/,'DB','LC') and @ppsmulticurr_flag = 'NO'  
		begin  
			if  @bnkcshcurrency_tmp <> @paycurrencycode  
			begin   
				select @m_errorid = 14  
				return   
			end    
		end  

		if  @paymode_tmp not in  ('ep'/*epe-17774*/,'DB','LC','OT') and @ppsmulticurr_flag = 'YES'  
		/* Code Commented and added by samuel for bug id : es_spy_00308 Ends here */  
		begin
			if	 @bnkcshcurrency_tmp            < > @paycurrencycode
			begin	
				select	@m_errorid = 14
				return	
			end
		end	
		
		--epe-17774
		if @bnkcshcurrency_tmp not in (@paycurrencycode, @basecurrencycode_tmp) and @pps_code ='NO'-- --EPE-44709
		begin 
			select @m_errorid  = 122
			return	
		end
		
		--epe-17774
	end
	--14H109_SPY_00056	
	/*
	SpyBR0078 Validate Currency for Direct Debit   
	If Pay Mode is "Direct Debit" and Pay Currency is not Base Currency,   
	BankCash Code must be in Base or Pay Currency. else error  
	*/
	/* Code changed by Esther J for defect id ES_bnkdef_00013 starts */
	/*
	if	 not exists(
			select	 'x'
			from	 bnkdef_sysact_bnkcshptt_vw( nolock)
			where	 company_code                   = @companycode_tmp
			and	 bank_cash_code                 = @bankcash
			and	 bank_ptt_cash                  = @paymentroute_tmp
			and	 currency_code                  in( @paycurrencycode, @basecurrencycode_tmp))
	begin	
		select @m_errorid  = 122
		return	
	end
	*/

	--Code added for dtsid: ES_bnkdef_00048:11h103_spy_00047 starts
	if  exists(	select	'x'
					from	Bnkdef_user_bank_map(nolock)
					where	CompanyCode	=	@companycode_tmp
					and		OU			=	@ctxt_ouinstance
					and		UserName	=	@ctxt_user
					and		TranType	=	'SPY'
					and		AccessRights=	'RE'
					and		BankCode	=	@bankcash)
		begin
			exec	fin_german_raiserror_sp 'SPY',@ctxt_language,5051,@bankcash
			return
		end
	--Code added for dtsid: ES_bnkdef_00048:11h103_spy_00047 ends
	
	if isnull(@allowcrosscurr,'N') = 'Y' and @tr_payment = 0
	begin
		select @m_errorid  = 0 
	end
	else
	begin
		if	 @paymode_tmp                   in ('ep','DB'  )	--epe-17774
		and  @paycurrencycode               <> @basecurrencycode_tmp and @ppsmulticurr_flag = 'NO'-- Code Added by samuel for bug id : es_spy_00308  	
		begin

			if	 exists(
				select	 'x'
				from	 bnkdef_sysact_bnkcshptt_vw( nolock)
				where	 company_code                   = @companycode_tmp
				and		bank_cash_code                 = @bankcash
				and		bank_ptt_cash                  = @paymentroute_tmp
				and		currency_code                  in( @paycurrencycode, @basecurrencycode_tmp))
			begin	 
				select @companycode_tmp = @companycode_tmp
			end
			else
			begin
				select @m_errorid  = 122
				return	
			end
		end
	end
	/* Code changed by Esther J for defect id ES_bnkdef_00013 ends*/

	select	 @paytype_tmp  	= dbo.spy_getcode( 'COMBO','PAYTYPE', @paymentroute,@ctxt_language)
	
	if	 @paytype_tmp	= 'B'
	begin
		if	 @paymode_tmp  IN( 'DD','PO') and isnull(@ddoption,'') = ''
		begin
			select	 @m_errorid  = 285
			return	
		end
			-- code changed for the dts id  11H103_rp_00054 [ES_rp_00328] starts
		--ELSE	if  @paymode_tmp  not in ( 'DD','PO') and @ddoption is not null
		ELSE	if  @paymode_tmp  not in ( 'DD','PO','DB') and isnull(@ddoption,'')<>''
		-- code changed for the dts id  11H103_rp_00054 [ES_rp_00328] ends
		begin
			select	 @m_errorid  = 286
			return	
		end

	end
	/*
	SpyBR0079 ArdSerBcmAcTrn1: Fetch BankCash Account   
	Invoke service ArdSerBcmAcTrn1 in ARD. Give input: Bankcash Code, FB, Date=Pay Date.   
	Get output: BankCash account.  
	*/
	exec ardisspgetbcpaccode            
	@ctxt_language,
	@ctxt_ouinstance,
	@ctxt_service,
	@ctxt_user,
	@fb,
	@bankcash,
	@requestdate,
	@bankcash_accountcode_tmp 	output,
	@errormsg1 			output

	if	 @supplierdocumentnumber        is not null
	or	 @supplierdocumentdate          is not null
	or	 @supplierdocumentamount        is not null
	begin

		if	 @supplierdocumentnumber        is null
		or	 @supplierdocumentdate          is null
		or	 @supplierdocumentamount        is null
		begin	
			select	@m_errorid = 46
			return	
		end
	end	
	/*
	SpyBR0082 Null check for Pay Amount   
	error Enter Pay Amount. Critical  
	*/
	if	 @payamount                     is null
	begin	
		select	@m_errorid = 64
		return	
	end

	/*Code added by karthi k.k for the bug id SPYDMS412AT_000551 starts*/
	if @payamount <= 0
	begin
		exec fin_german_raiserror_sp 'SPY',@ctxt_language,61 
		return
	end
	/*Code added by karthi k.k for the bug id SPYDMS412AT_000551 ends*/

	/*
	SpyBR0083 Null check for Ordering Point   
	For any row,  if Ref Doc Type is entered,   check if Ordering Point is entered,   else error Enter Ordering Point for Ref Doc Type <%1>. Critical  
	SpyBR0084 Null check for Ref Doc No. For any row,   if Ref Doc Type is entered,   check if Ref Doc No. is entered,   else error Enter Ref. Document No. for Ref Doc Type <%1>. Critical  
	SpyBR0085 Null check for Document Pay Amount For any row,   if Ref Doc Type is entered,   check if Document Pay Amount is entered,   else error Enter Document Pay Amount for Ref Doc Type <%1>. Critical 
	SpyBR0086 Check for Document Pay Amount For each row,   check if Document Pay Amount is greater than zero,   else error Document Pay Amount must be greater than zero. Modify the amount for Ref. Document No. <%1>. Critical  
	SpyBR0087 Doc pay Amount validation criteria If Voucher Type is "Prepayment",   perform the following validations for Doc Pay Amount for each Ref Doc No..    
	SpyBR0088 ***: Fetch advance allowed (BPO) If Ref Doc Type is "Blanket PO",   invoke service in BPO component. Give input: Order No.= Ref. Doc No.,   OU= Ordering Point. Get output: Advance Amount (A),   Advance Tolerance % (B),   Advance Paid ( C),  
	*/

	/*
	Order Currency. All amounts are in Order Currency    
	SpyBR0089 ***: Fetch advance allowed (BSCO) If Ref Doc Type is "Blanket SCO",   invoke service in BSO component. Give input: Order No.= Ref. Doc No.,   OU= Ordering Point. Get output: Advance Amount (A),   Advance Tolerance % (B),   Advance Paid ( C), 




























	*/

	if	 lower( @ctxt_service) = 'SPYEdPPMnSrModAut'
	begin	
		select @status_tmp                    = 'RE'
	end
	else	if	 lower( @ctxt_service) = 'spyauppmnsrreturn'
	begin
		select @status_tmp                    = 'RT'
	end
	else	
	begin
		select @status_tmp                    = 'F'
	end

	/* moved here  for dts id 11H103_spy_00048 starts */
	if 	@ppvouchertype_tmp	=	'PP'
	begin
		select	@trantype_tmp	=	'PM_SPPV'
	end
	else	if @ppvouchertype_tmp	=	'PPD'	
	begin
		select	@trantype_tmp	=	'PM_SDV' /*14H109_mcam_00001*/
	end
	/* moved here  for dts id 11H103_spy_00048 ends*/	

	IF @ctxt_service = 'spyauppmnsrreturn'
	BEGIN
		DECLARE	@applied_flag	fin_flag
		declare @exec_flag	fin_flag


		/*if 	@ppvouchertype_tmp	=	'PP'
		begin
			select	@trantype_tmp	=	'PM_SPPV'
		end
		else	if @ppvouchertype_tmp	=	'PPD'	
		begin
			select	@trantype_tmp	=	'PM_SDA'
		end*/

		update spy_prepay_vch_hdr
		set 	status      = 	@status_tmp,	
			modifiedby	    =	@ctxt_user,
			modifieddate	=	dbo.RES_Getdate(@ctxt_ouinstance)
		where	ou_id 		= 	@ctxt_ouinstance
		and	voucher_no      = 	@vouchernumber
		and	tran_type       =	@trantype_tmp

		exec	tcal_status_upd_sp
			@ctxt_ouinstance ,@ctxt_language,@ctxt_user,@ctxt_service,@guid,
			@ctxt_ouinstance,@trantype_tmp,@vouchernumber,null,null,
			'SPY','SPY',@vouchernumber,@status_tmp,
			@applied_flag	output ,@exec_flag	output,@m_errorid	 out				
	END
	ELSE
	BEGIN
		declare	 @tran_amount fin_amount
		declare	 @payamount_tmp        fin_amount
	
		select	 @payamount_tmp                 = pay_amount,
				 @tran_amount                   = voucher_amount
		from	 spy_prepay_vch_hdr( nolock)
		where	 ou_id     = @ctxt_ouinstance
		and		 voucher_no                     = @vouchernumber
		and		 tran_type      IN ('PM_SPPV','PM_SDV')
	
		if	 @payamount_tmp                 = @payamount
		select	 @payamount                 = @tran_amount

	/*code added by Esther J on 24/03/2009 for the defect id ES_bnkdef_00013 starts*/
		if @paymode_tmp = 'LC'
		begin
			--select @today  = dbo.RES_Getdate(@ctxt_ouinstance)--ES_spy_00397[11H103_spy_00010:11H103_spy_00040]
			select @today  = @paydate--ES_spy_00397[11H103_spy_00010:11H103_spy_00040]
			select	@refid = @lc_refid--ES_spy_00397: 11H103_spy_00010
			exec SPY_lc_validation @ctxt_language,@ctxt_ouinstance,@ctxt_service,@ctxt_user,'SPPV',
			     @lo_id,null,@lcnumber output --ES_spy_00397[11H103_spy_00010:11H103_spy_00032]
			     ,@today,@bankcash,@paycurrencycode,@m_errorid output,
			     @ppvouchertype_tmp, @refid output, @supplier
	
			if @m_errorid <> 0 
				return
		end 
		else
		begin
			if @lcnumber is not null 
			begin	
				--2023	LC Number can not be entered when the Pay mode %s.
				exec fin_german_raiserror_sp  'SPY',@ctxt_language,2023,@paymode
				return
			end
		end
	
	/*code added by Esther J on 24/03/2009 for the defect id ES_bnkdef_00013 ends*/
-- code added for EPE-32731
	if  @tr_payment = 1 and @trustreceiptwithbankeraccept = '1' 
	begin
		exec fin_german_raiserror_sp  'SPY',@ctxt_language,1112
		return
	end
	-- code added for EPE-32731
		/*code added by Esther J for the defect 10H109_spy_00047 ; TRUST RECEIPT starts*/
		declare @payamt_inbkcurr_tmp		fin_amount
	
		if @tr_payment = 1 or @trustreceiptwithbankeraccept = '1'-- code added for EPE-32731
		begin
			if @bnkcshcurrency_tmp = @paycurrencycode
					select @payamt_inbkcurr_tmp = @payamount
			else
				    select @payamt_inbkcurr_tmp = round((@payamount * @exchangerate), @pamt_tmp)
	
			exec spy_tr_validation_sp @ctxt_language,@ctxt_ouinstance,@ctxt_service,@ctxt_user,@guid,'PPV',@ppvouchertype_tmp,
			  					  @paymode_tmp,@payamt_inbkcurr_tmp,@paydate,@bankcash,@fb,
								  @tr_lmtbalance,
								  @tr_payment,@trustreceiptwithbankeraccept,-- code added for EPE-32731
								   @tr_precent output, @tr_amount  output,
								@tr_tenure	output, @tr_duedate output, @m_errorid  output	
			if @m_errorid <> 0 
				return
	
		end
		else
		begin
			/*TRSPY022	Trust Receipt Validation - 2	
			If Payment through Trust Receipt is Unchecked and values given in any of the following controls, Trust Receipt %  Trust Receipt Amount, Trust Receipt Tenure, Trust Receipt Due Date, display error.
			*/
			if @tr_precent is not null or @tr_amount is not null or					  
			   @tr_tenure is not null or @tr_duedate is not null  					  
			begin
				--4000	Trust Receipt % / Trust Receipt Amount / Trust Receipt Tenure / Trust Receipt Due Date can be given only when Payment through Trust Receipt check box is checked. Remove the details or Check the checkbox.
				exec fin_german_raiserror_sp  'SPY',@ctxt_language,4000
				return
			end
		end
		/*code added by Esther J for the defect 10H109_spy_00047 ; TRUST RECEIPT ends*/
	
		/* Added for dts id 11H103_spy_00048 starts */
		select @prjsubprjdesc  = NULL  -- code added for the dts id 11H103_spy_00048:11H103_spy_00117
				
		if (isnull(@PrjOU,'') <> '' or isnull(@prjsubprjcd,'') <> ''  )
		begin
			exec fin_val_cc_projcode	@ctxt_language,@ctxt_ouinstance,@ctxt_service,@ctxt_user,
										'SPY', 'SAVE', @guid, @prjou_tmp, @prjsubprjcd,
										@ctxt_ouinstance, @vouchernumber, @trantype_tmp, @prjsubprjdesc output, 
										@successflag1 output, @ccplaceholder output, @m_errorid  output

			if @m_errorid   <> 0 
			begin
					return
			end
		END
		/* Added for dts id 11H103_spy_00048 ends */

		/*code added for the defect id :EPE-48054 starts here */

		
		exec frwd_cntrct_amt_back_update	
				@ctxt_language,  
				@ctxt_ouinstance,
				@ctxt_service,   
				@ctxt_user,		
				@vouchernumber,	
				@payamount,		
				'SPPV',	
				'SPPV',		
				@m_errorid output 

			If @m_errorid <> 0
			begin
				return
			end

			exec frwrd_cntrt_cmnhdr_validate
				@ctxt_language,     
				@ctxt_ouinstance,   
				@ctxt_service,      
				@ctxt_user,         
				@payamount,         
				@ForwardContractNo,	
				@exchangerate,		
				@bankcash,			
				@compcode,
				'SPPV',
				@m_errorid    output
				
			If @m_errorid <> 0
			begin
				return
			end
	
   --code added for the defect id :EPE-48054 ends here */

		update	 spy_prepay_vch_hdr 
		set	 	
			bank_cash_acct		= @bankcash_accountcode_tmp,
			bank_cash_code		= @bankcash,
			dd_charges    		= @ddoption_tmp,
			exchange_rate 		= round( @exchangerate, @perate_tmp),
			fb_id         		= @fb_tmp,
			modifiedby    		= @ctxt_user,
			modifieddate  		= @sysdate_tmp,
			pay_amount    		= round( @payamount, @pamt_tmp),
			pay_currency  		= @paycurrencycode,
			pay_date      		= @paydate,
			pay_mode      		= @paymode_tmp,
			payment_route 		= @paymentroute_tmp,
			priority      		= @priority_tmp,
			relpay_ou     		= @relpayou_tmp,
			remarks       		= @remarks,
			request_date  		= @requestdate,
			status        		= @status_tmp,
			supp_area     		= @supplierarea_tmp,
			supp_code     		= @supplier,
			supp_doc_amt  		= round( @supplierdocumentamount, @pamt_tmp),
			supp_doc_date 		= @supplierdocumentdate,
			supp_doc_no   		= @supplierdocumentnumber,
			supp_prepay_acct	= @pp_accountcode_tmp,
			timestamp     		= timestamp + 1,
			batch_id      		= @guid,
			voucher_type  		= @ppvouchertype_tmp,
			voucher_amount		= @payamount,
			lcnumber			= @lcnumber --code added by Esther J for the defect ES_bnkdef_00013 ; LC	
			,refid				= @refid
			/*code added by Esther J for the defect 10H109_spy_00047 ; TRUST RECEIPT starts*/
			,tr_flag			= @tr_payment,
			 tr_amount			= @tr_amount,
			 tr_tenure			= @tr_tenure,
			 tr_duedate			= @tr_duedate,
			 tr_percent 		= @tr_precent,
			 surnotype_no		= @surnumtype				
			/*code added by Esther J for the defect 10H109_spy_00047 ; TRUST RECEIPT ends*/
			/*Code Added By Indira.G For Defect Id:ES_spy_00391 Starts*/
			 ,crosscur_erate    = isnull(crosscur_erate,@exrate), --ES_spy_00526
			 bank_amount        = isnull(bank_amount,@payamount1),
			 bank_base_amount   = isnull(bank_base_amount,@baseamount)
			/*Code Added By Indira.G For Defect Id:ES_spy_00391 Ends*/
			--Added for dts id 11H103_spy_00048 starts 
			 ,project_ou        = @prjou_tmp,
			  Project_code       = @prjsubprjcd ,
			 --Added for dts id 11H103_spy_00048 ends 
			 TRWithBankerAccept = @trustreceiptwithbankeraccept -- code added for EPE-32731
			 ,contract_no		= @forwardcontractno --EPE-48054
		where	ou_id 			= @ctxt_ouinstance
		and	voucher_no			= @vouchernumber
		and	tran_type		in ('PM_SPPV','PM_SDV')
	
		delete	from	 spy_tranno_tmp
		where	 guid                           = @guid
	
		insert	
		into	 spy_tranno_tmp( guid,tran_no,lastmoddate,paybatch_no,vou_type)
		values	( @guid	,@vouchernumber,@sysdate_tmp, 'N.A.', 'PPV')

		
		delete	
		from	 spy_prepay_vch_dtl
		where	 ou_id   	= 	@ctxt_ouinstance
		and	 voucher_no     = 	@vouchernumber
		and	 tran_type      in ('PM_SPPV','PM_SDV')

		--EPE-70555
		if exists(	select	'*'
					from	cps_taxparam_sys c(nolock),
							tset_tax_community_vw t(nolock),
							tcal_taxtype_tran_map m (nolock)
					where	company_code	=	@compcode
					and		c.tax_type		=	t.tax_type
					and		c.tax_community	=	t.tax_community
					and		default_calculation = 'Y'
					and		taxcalc_applicable_at	=	'L'
					and		m.tax_type		=	t.tax_type
					and		m.tax_community	=	t.tax_community
					and		m.tran_type		=	'PM_sppV'
					and		m.applicability	=	'Y'
				)
		begin
			select	@guid = @guid
		end
			/*Code Commented for RITSL/RMC_FIN_53 Begins*/
	/*
		else
		begin
		--EPE-70555
		exec @ret_tmp = spyppsp_posting_ch
			@ctxt_language,
			@ctxt_ouinstance,
			@ctxt_service,
			@ctxt_user,
			@payamount,
			@guid,
			@vouchernumber,
			/*Code Added By Indira.G For Defect Id:ES_spy_00391 Starts*/
		    @exrate,                      
		    @payamount1
		    /*Code Added By Indira.G For Defect Id:ES_spy_00391 Ends*/
	
		if	 @ret_tmp                       < > 0
		begin	
			select	 @m_errorid                     = 3690985
			return	
		end
		end--EPE-70555
	*/
	/*Code Commented for RITSL/RMC_FIN_53 Ends*/
	END
	
	select	@status_tmp         = 	status,
		    @payamount          = 	pay_amount
	from	 spy_prepay_vch_hdr( nolock)
	where	 ou_id              = 	@ctxt_ouinstance
	and		 voucher_no         = 	@vouchernumber
	and		 tran_type         in ('PM_SPPV','PM_SDV')

	IF	 @paymode_tmp                   = 'OT'
	AND	 @status_tmp                    = 'RE'
	BEGIN
		SELECT	 @status_tmp         = 'PA'
	END

	/*code added for Logistics_prepayment starts*/
	
	update  spy_tranno_tmp
	set		old_guid	=	@guid
	where	guid		=	@guid
	
	update	spy_prepay_tmp
	set		new_guid	=	@guid
	where	old_guid	=	@guid	

	/*code added for Logistics_prepayment ends*/
	
	/* code added for 11H103_spy_00048 starts */	
	update DTL  
	set 	project_ou 		= hdr.project_ou,
			Project_code  	= hdr.project_code
	from	spy_acct_info_dtl	DTL (nolock) ,
			spy_prepay_vch_hdr  hdr (nolock) 
	where   hdr.ou_id               = @ctxt_ouinstance
	and		hdr.voucher_no          = @vouchernumber
	and		DTL.ou_id				= hdr.ou_id
	and 	DTL.tran_no		  		= hdr.voucher_no
	and 	DTL.tran_type			= hdr.tran_type 
	and   	isnull(hdr.project_ou,'') <> ''
	and    isnull(hdr.project_code,'') <> ''
	/* code added for 11H103_spy_00048 ends */

	select 	@accountdesc 	= ltrim(rtrim(ml_account_desc))
	from	as_opacctfball_ml_vw (nolock)
	where	company_code	= @companycode_tmp
	and 	account_code 	= @accountcode
	and 	fb_id			= @fb
	and		language_id 	= @ctxt_language
--14H109_mcam_00001		

	if @called_from = 'NONE'
	begin
		select	@bankcash												'BANKCASH',
				@bankdescription										'BANKDESCRIPTION',
				@ddoption												'DDOPTION',
				@exchangerate											'EXCHANGERATE',
				@fb														'FB',
				@guid													'GUID',
				@ctxt_user												'LASTMODIFICATIONBY',
				@sysdate_tmp											'LASTMODIFIEDDATE',
				@payamount												'PAYAMOUNT',
				@paycurrencycode										'PAYCURRENCYCODE',
				convert( nvarchar( 10), @paydate, 120)					'PAYDATE',
				@paymentroute											'PAYMENTROUTE',
				@paymode												'PAYMODE',
				@ppvouchertype											'PPVOUCHERTYPE',
				@priority												'PRIORITY',
				@relpayou												'RELPAYOU',
				@remarks												'REMARKS',
				convert( nvarchar( 10), @requestdate, 120) 				'REQUESTDATE',
				dbo.spy_getdesc( 'STATUS','VOUSTATUS',@status_tmp,1) 	'STATUS',
				@supplier												'SUPPLIER',
				@supplierarea											'SUPPLIERAREA',
				@supplierdocumentamount									'SUPPLIERDOCUMENTAMOUNT',
				convert( nvarchar( 10), @supplierdocumentdate, 120)		'SUPPLIERDOCUMENTDATE',
				@supplierdocumentnumber									'SUPPLIERDOCUMENTNUMBER',
				@suppliername											'SUPPLIERNAME',
				@timestamp + 1											'TIMESTAMP',
				@vouchernumber											'VOUCHERNUMBER',
				@errorno												'ERRORNO',
				@fprowno												'FPROWNO',
				@placeholder1											'PLACEHOLDER1',
				@placeholder2											'PLACEHOLDER2',
				@placeholder3											'PLACEHOLDER3',
				@placeholder4											'PLACEHOLDER4',
				0														'SUCCESSFLAG',
				@ctxt_ouinstance										'ouinstid',
				@ctxt_ouinstance										'CsOUInStance',
				@trantype_tmp											'trantype',
				@accountcode											'accountcode',
				@accountdesc											'accountdesc'
				,@lcnumber												'LCNUMBER'--code added by Esther J for the defect ES_bnkdef_00013 ; LC	
				/* Code added for the dts id 10H109_spy_00047 starts */
				,@tr_payment											'TR_PAYMENT',
				@tr_precent												'TR_PRECENT',
				@tr_amount												'TR_AMOUNT',
				@tr_tenure												'TR_TENURE',
				@tr_duedate												'TR_DUEDATE',
				@tr_lmtbalance											'TR_LMTBALANCE'	,	   
				@surnumtype												'SURNUMTYPE'
				
				/*Code Added By Indira.G For Defect Id:ES_spy_00401 Starts*/
				/*Code Added By Indira.G For Defect Id:ES_spy_00391 Starts*/
				,@exrate    'exrate',      
				@payamount1    'payamount1', 
				@baseamount    'baseamount' 
				/*Code Added By Indira.G For Defect Id:ES_spy_00391 Ends*/
				/*Code Added By Indira.G For Defect Id:ES_spy_00401 ends*/
				/* Code added for the dts id 10H109_spy_00047 ends*/
				,@refid 'lc_refid' -- code added for the bug id::ES_spy_00397:11H103_spy_00010
				/* code added for 11H103_spy_00048 starts */
				,@PRJOU				'PRJOU',
				@PRJSUBPRJCD		'PRJSUBPRJCD',
				@PRJSUBPRJDESC		'PRJSUBPRJDESC',
				@ForwardContractno      'ForwardContractNo' --EPE-48054
				/* code added for 11H103_spy_00048 ends*/
			end
			else
			begin
				update	mca_sel_doc_tmp
				set		error_id	= 0
				where	hdn_guid = @guid			
			end
--14H109_mcam_00001						
	set nocount off
end





