/*$File_version=ms4.3.0.15$*/
/*$file name : spyauapenspblkautpbdtl.sql*/
/*==================================================
   stored procedure : spyauapenspblkautpbdtl
   method           : spyauapenmtblkautpbdtl
   author           : Veera
	created on       : 26 mar 2002 19:18:24:477
   created at       : s4353
   generated by     : fpuser
   modified by      :  Jinesh
   modified on       : 30-Apr-2004
  description       : SPYDMS41ACTST_000168
   modified by             :T.R.Vidhya
   modified date           :26/01/2005
   modified purpose        :Audit Trial Development bug id : SPYDMS41UTST_000005
*/
/*==================================================*/
/*Modified by		Date				Remarks		*/
/*S.Shankaranand		5/9/04				For German Transaction		*/
/******************************************************************************************/

/********************************************************************************/

/* modified by  : M. Devanathan	                                        */
/* date         : 07th June 2005                                                */
/* description  : SPYDMS412AT_000025		                                */
/* modified by  : Uma Maheswari	                                        */
/* date         : 13th June 2005                                                */
/* description  : SPYDMS412AT_000025		                                */

/* modified by  : Uma Maheswari	                                        */
/* date         : 24th June 2005                                                */
/* description  : SPYDMS412AT_000045		                                */
/********************************************************************************/
/*Modified by		Modified date		Modified purpose	*/
/*S.balaji			06/05/2005			SPYDMS412AT_000181  */
/*S.balaji			19/09/2006			SPYDMS412AT_000255  */
/* Porselvi.J		17-04-2007			SPYDMS412AT_000372	*/
/* Porselvi.J		18-04-2007			SPYDMS412AT_000372	*/
/* Porselvi.J		09-07-2007			SPYDMS412AT_000493	*/
/* vijayan.j		11-09-2007			RPDMS412AT_000248	*/
/* Aparna M.		03/05/2008			8H123-1_spy_00001	*/
/* Aparna M.		03/07/2008			8H123-1_spy_00017	*/
/* Selvan G			10/Jul/2008			8H123-1_spy_00025	*/
/* Selvan G			15/Jul/2008			8H123-1_spy_00025	*/
/* R.Mohandas		19/01/2010			9H123-1_SPY_00026	*/
/* R.Mohandas		19/01/2010			9H123-1_SPY_00030(9H123-1_SPY_00026)*/
/*Pusba Prasanaa.B.R. 29/07/2010		ES_cps_00008		*/
/*Esther J			17/08/2011			11H103_spy_00010:11H103_spy_00037 */
/* Sharmila M	20/01/2012	ES_bnkdef_00048:11h103_spy_00047	*/
/* Damodharan. R	30/08/2012			12H124_SPY_00007					*/
/* Divyalekaa		03/05/2015			14H109_GENERAL_00059:14H109_spy_00046 */
/* Kavitha R		18/02/2016			14H109_mcam_00001*/
/* Balaji C			22/11/2016			ES_spy_01569					*/
/* Balaji C			23/06/2017			BAK-120							*/
/* Vignesh E		07/01/2021			EPE-34128						*/
--Amani.P			15-09-2021			EPE-37936
--Amani.P			11-10-2021		EPE-38698
--Nithya S			17/05/2024		EPE-79558:EPE-81543
/*suryakala A       22-01-2025       CU Merging-PJRMC-1252 */
/************************************************************************/

create   procedure spyauapenspblkautpbdtl
	@bankcash   			fin_bankcashcode,
	@ctxt_language   		fin_ctxt_language,
	@ctxt_ouinstance  		fin_ctxt_ouinstance,
	@ctxt_service   		fin_ctxt_service,
	@ctxt_user   			fin_ctxt_user,
	@docpriority   			fin_priority,
	@docpriorityml   		fin_priority,
	@guid   				fin_guid,
	@modeflag   			fin_modeflag,
	@paybatchnumber   		fin_documentnumber,
	@paybatchnumberfromsearch  	fin_documentnumber,
	@paybatchnumberml   	fin_documentnumber,
	@paybatchnumbertosearch fin_documentnumber,
	@paydatefrom   			fin_date,
	@paydateml   			fin_date,
	@paydateto   			fin_date,
	@paymentroutesearch   	fin_route,
	@requestdate   			fin_date,
	@searchreqdatefrom   	fin_date,
	@searchreqdateto   		fin_date,
	@supplierfrom   		fin_suppliercode,
	@supplierml   			fin_suppliercode,
	@suppliername   		fin_name,
	@suppliernameml  		fin_name,
	@supplierto 			fin_suppliercode,
	@timestamp1  			fin_timestamp,
	@useridentity   		fin_ctxt_user,
	@wfdockey               fin_wfdockey,
	@wforgunit      fin_wforgunit,
	@errorno   				fin_errorno,
	@fprowno   				fin_rowno,
	@placeholder1   		fin_placeholder,
	@placeholder2   		fin_placeholder,
	@placeholder3   		fin_placeholder,
	@placeholder4   		fin_placeholder,
	@successflag   			fin_successflag,
	@PrepaymentsCheck 		fin_paramchar,
	@m_errorid  			fin_int output
as
begin
	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	-- @m_errorid should be 0 to indicate success
	select @m_errorid =0

	--BEGIN of Standard code for getting precision type
	declare @pqty_tmp              fin_int ,
		@pamt_tmp                  fin_int ,
		@prate_tmp                 fin_int ,
		@perate_tmp                fin_int ,
		@phigh_tmp                 fin_int ,
		@pmed_tmp                  fin_int ,
		@plow_tmp                  fin_int
	
	exec 	fin_sp_precisiontype_rtr @pqty_tmp output, @pamt_tmp output,
		@prate_tmp output, @perate_tmp output, @phigh_tmp output,
		@pmed_tmp output, @plow_tmp output
	--END of Standard code for getting precision type

	select @bankcash 		= ltrim(rtrim(@bankcash))
	select @ctxt_service 		= ltrim(rtrim(@ctxt_service))
	select @ctxt_user 		= ltrim(rtrim(@ctxt_user))
	select @docpriority 		= ltrim(rtrim(@docpriority))
	select @guid 			= ltrim(rtrim(@guid))
	select @modeflag 		= ltrim(rtrim(@modeflag))
	select @paybatchnumberfromsearch= ltrim(rtrim(@paybatchnumberfromsearch))
	select @paybatchnumber 		= ltrim(rtrim(@paybatchnumber))
	select @paybatchnumberml 	= ltrim(rtrim(@paybatchnumberml))
	select @paybatchnumbertosearch 	= ltrim(rtrim(@paybatchnumbertosearch))
	select @paydatefrom 		= ltrim(rtrim(@paydatefrom))
	select @paydateml 		= ltrim(rtrim(@paydateml))
	select @paydateto 		= ltrim(rtrim(@paydateto))
	select @paymentroutesearch 	= ltrim(rtrim(@paymentroutesearch))
	select @requestdate 		= ltrim(rtrim(@requestdate))
	select @searchreqdatefrom 	= ltrim(rtrim(@searchreqdatefrom))
	select @searchreqdateto 	= ltrim(rtrim(@searchreqdateto))
	select @supplierfrom 		= ltrim(rtrim(@supplierfrom))
	select @supplierml 		= ltrim(rtrim(@supplierml))
	select @suppliernameml 		= ltrim(rtrim(@suppliernameml))
	select @supplierto 		= ltrim(rtrim(@supplierto))
	select @useridentity 		= ltrim(rtrim(@useridentity))
	select @placeholder1 		= ltrim(rtrim(@placeholder1))
	select @placeholder2 		= ltrim(rtrim(@placeholder2))
	select @placeholder3 		= ltrim(rtrim(@placeholder3))
	select @placeholder4 		= ltrim(rtrim(@placeholder4))

	if @bankcash = '~#~' 
		select @bankcash = null
	if @ctxt_language = -915 
		select @ctxt_language = null
	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null
	if @ctxt_service = '~#~' 
		select @ctxt_service = null
	if @ctxt_user = '~#~' 
		select @ctxt_user = null
	if @docpriority = '~#~' 
		select @docpriority = null
	if @guid = '~#~' 
		select @guid = null
	if @modeflag = '~#~' 
		select @modeflag = null
	if @paybatchnumberfromsearch = '~#~' 
		select @paybatchnumberfromsearch = null
	if @paybatchnumber = '~#~' 
		select @paybatchnumber = null
	if @paybatchnumberml = '~#~' 
		select @paybatchnumberml = null
	if @paybatchnumbertosearch = '~#~' 
		select @paybatchnumbertosearch = null
	if @paydatefrom = '1900-01-01' 
		select @paydatefrom = null
	if @paydateml = '1900-01-01' 
		select @paydateml = null
	if @paydateto = '1900-01-01' 
		select @paydateto = null
	if @paymentroutesearch = '~#~' 
		select @paymentroutesearch = null
	if @docpriorityml = '~#~'
		select @docpriorityml = null
	if @requestdate = '1900-01-01' 
		select @requestdate = null
	if @searchreqdatefrom = '1900-01-01' 
		select @searchreqdatefrom = null
	if @searchreqdateto = '1900-01-01' 
		select @searchreqdateto = null
	if @supplierfrom = '~#~' 
		select @supplierfrom = null
	if @supplierml = '~#~' 
		select @supplierml = null
	if @suppliernameml = '~#~' 
		select @suppliernameml = null
	if @supplierto = '~#~' 
		select @supplierto = null
	if @timestamp1 = -915 
		select @timestamp1 = null
	if @useridentity = '~#~' 
		select @useridentity = null
	if @errorno = -915 
		select @errorno = null
	if @fprowno = -915 
		select @fprowno = null
	if @placeholder1 = '~#~' 
		select @placeholder1 = null
	if @placeholder2 = '~#~' 
		select @placeholder2 = null
	if @placeholder3 = '~#~' 
		select @placeholder3 = null
	if @placeholder4 = '~#~' 
		select @placeholder4 = null
	if @successflag = -915 
		select @successflag = null

 	declare @status_tmp  			fin_status,
	 	@compcode_tmp   			fin_companycode,
	 	@exchangeratetype_tmp		fin_param_text,
	 	@basecurrencycode_tmp		fin_currency,
	 	@unadjppchk_flag 			fin_flag,
	 	@flag_out 					fin_flag,
		/*Code added for Defect ID 12H124_SPY_00007 starts here*/
		@unadjdebitchk_flag			fin_flag,
		@debitflag_out				fin_flag,
		@supp_count					fin_int,
		@culist						fin_desc255,
		@sulist						fin_desc255,
		/*Code added for Defect ID 12H124_SPY_00007 ends here*/
		@voucher_type  				fin_notypeno,
		@voucher_tmp				fin_documentnumber,
		@paybatch_no				fin_documentnumber,
		@voucher_no					fin_documentnumber,
        	/*Code Added By Selvan G for the Bug Id : 8H123-1_spy_00025 starts here */
		--@errdesc 					fin_text255,--9H123-1_SPY_00026
		@errno						fin_int,
		@bankcash_out				fin_bankcashcode,
		@accountcode_out			fin_accountcode,
		@event_out					fin_finevent,
		@usage_out					fin_finusage,
		@fbid_out					fin_financebookid,
		@currency_out				fin_currencycode,
		@bank_cash_code				fin_bankcashcode,
		@errormsg_out				fin_placeholder,
		@date_tmp					fin_date,--9H123-1_SPY_00026
		@lo							fin_loid--9H123-1_SPY_00026
		/*Code Added By Selvan G for the Bug Id : 8H123-1_spy_00025 Ends here */
	/* Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008 starts here */
	declare	@albkdt					fin_paramchar
	declare	@cur_date				fin_date
	declare	@pymt_type				fin_paramchar
	declare	@pymt_date				fin_date
	declare	@errmsg					fin_desc255
	/* Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008 ends here */	

	/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 begins here*/
	declare @sur_guid					fin_guid,
			@surdate					fin_date,
			@fb_id						fin_financebook,
			@basecur					fin_currencycode,		
			@receiptcategory			fin_receiptcategory,
			@sundryreceiptvoucher		fin_desc255,
			@receiptmethod				fin_method,
			@receiptmode				fin_receiptmode,
			@receiptroute				fin_route,
			@bankdescription  			fin_bankdescription,
			@bankcode					fin_bankcode,			
			@remitter					fin_desc255,
			@boe_account				fin_accountcode,
			@costcenter					fin_costcenter,
			@analysiscode				fin_desc40,
			@subanalysiscode			fin_desc40,
			@pbnum_tmp					fin_desc40,
			@vnonew_tmp					fin_desc40,
			@transactionou				fin_int,
			@be_amount					fin_amount,
			@be_amount_base				fin_amount,
			@be_percent					fin_duepercentage,
			@be_currency				fin_currencycode,
			@bebasecur_erate			fin_exchangerate,
			@be_duedate					fin_date,
			@be_boeno					fin_bankcode,
			@be_flag					fin_chkflag,
			@be_issuedat				fin_remarks,
			@eratetype					fin_paramchar,
			@retcode_tmp				fin_int,
			@paybecur_erate				fin_amount,
			@maxtollimit				fin_amount,
			@mintollimit				fin_amount,
			@totalpayamount				fin_amount,
			@buid_tmp					fin_buid,
			@errorid					fin_int,/* Begins - Code added / Commented /Modified against rTrack ID : CU Merging-PJRMC-1252*/
			@be_notype					fin_notypeno/* ends - Code added / Commented /Modified against rTrack ID : CU Merging-PJRMC-1252*/
	/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 ends here*/	
	--14H109_mcam_00001
	declare		@called_from	fin_param_text

	/* Code changes by Vignesh E for Rtrack ID EPE-34128 starts here */
	declare @compcode               fin_companycode
	declare	@Backdated_value		fin_int	
	/* Code changes by Vignesh E for Rtrack ID EPE-34128 ends here */

	select @called_from = 'NONE'
	if exists(select 1 from mca_sel_doc_tmp(nolock)
				where  hdn_guid = @guid)
	begin
		update	mca_sel_doc_tmp
		set		error_id	= 1
		where	hdn_guid = @guid
		
		select @called_from = 'MCAM'
	end		
--14H109_mcam_00001	
	
	/* code added for the defect id EPE-79558:EPE-81543 starts here */
	if exists(	select	'X'
					from	fb_tmp(nolock)
					where   rsih_guid_tmp = @guid
					AND		pps_flag	in	('APP','REJ')
				)
	begin
		select	@called_from	= 'MOB_APPR'
	end
	/* code added for the defect id EPE-79558:EPE-81543 ends here */

	if @fprowno is null or @fprowno = 0   
	begin  
		--select @fprowno = 1  --Commented for DTS ID: 9H123-1_SPY_00030(9H123-1_SPY_00026)
		select @fprowno = 0
	end

	select	@fprowno = @fprowno + 1-- Code moved here for the DTS ID: 9H123-1_SPY_00030(9H123-1_SPY_00026)

	--Code modified by Porselvi.J for bug id : SPYDMS412AT_000493 starts
	if @modeflag not in ('X','Y','Z')
	begin
		select	0 		'errorno',
			@fprowno	'fprowno',
			'' 		'placeholder1',
			'' 		'placeholder2',
			''	 	'placeholder3',
			''		'placeholder4',
			0 		'successflag'
		return
	end

--	select	@fprowno = @fprowno + 1--Commented for DTS ID: 9H123-1_SPY_00030(9H123-1_SPY_00026)
	--Code modified by Porselvi.J for bug id : SPYDMS412AT_000493 ends
	select 	@date_tmp	= convert(nvarchar(10),dbo.RES_Getdate(@ctxt_ouinstance),120)--9H123-1_SPY_00026
	
	/* Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008 starts here */

	/*Code added for rtrack id : BAK-120 starts*/
		if exists	(	select 'x'
						from   spy_paybatch_dtl a(nolock),
							   si_doc_hdr hdr(nolock)
						where  a.paybatch_no	= @paybatchnumberml
						and    a.ou_id			= @ctxt_ouinstance
						and    a.cr_doc_ou		= hdr.tran_ou
						and    a.cr_doc_no		= hdr.tran_no
						and    a.tran_type		= hdr.tran_type
						and    hdr.tran_type	in ('PM_IV', 'PM_EV', 'PM_DPI', 'PM_ORPI', 
                        							   'PM_ROPI', 'PM_RSPI', 'PM_PI', 'PM_MI', 
                        							   'PM_SDI', 'PM_SCI', 'PM_SDA', 'PM_SCA', 
                        							   'PM_STC', 'PM_CV', 'PM_SRC')
						and    hdr.doc_status	in ('RVD', 'HLD', 'RV', 'HD', 'REV', 'R')
					)
		begin
			--raiserror('Credit document is not in valid status for the Paybatch %s , Kindly visit the main page.',16,1,@paybatchnumberml)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,6107,@paybatchnumberml
			return
		end
	/*Code added for rtrack id : BAK-120 ends*/

	/* Code changes by Vignesh E for Rtrack ID EPE-34128 starts here */
	select 	@compcode 	= company_code
	from 	emod_ou_vw(nolock)
	where 	ou_id 	= @ctxt_ouinstance
	and 	dbo.fin_getdatepart(dbo.RES_Getdate(@ctxt_ouinstance)) between effective_from 
			and isnull(effective_to,'01-01-9999')
	/* Code changes by Vignesh E for Rtrack ID EPE-34128 ends here */
	
	select	@pymt_date = pay_date, @pymt_type = payment_route
	from	spy_paybatch_hdr(nolock)
	where	ou_id 			= @ctxt_ouinstance 
	and 	paybatch_no 	= @paybatchnumberml
	
	select @cur_date = convert(nvarchar(10),dbo.RES_Getdate(@ctxt_ouinstance),120)
	
	Select @albkdt = parameter_code 
	from cps_processparam_sys(nolock) 
	where	parameter_type		= 'PMSYS' 
	and		parameter_category	= 'AlBakDtdTrans'
	and		language_id			= @ctxt_language
	and     company_code		=@compcode--EPE-38698
	--and		ou_id				= @ctxt_ouinstance EPE-37936

	/* Code changes by Vignesh E for Rtrack ID EPE-34128 starts here */
if @albkdt <>'NO'--EPE-38698
BEGIN
	Select @Backdated_value = paymode_typevalue 
	from cps_backdated_payment(nolock) 
	where	company_code	=@compcode
	--and		ou_id				= @ctxt_ouinstance EPE-37936
	and		language_id	    =@ctxt_language
	and		paymode_category=@albkdt
	and		paymode_typecode='SPY'
	and		paymode_status	='AC'
end
	/* Code changes by Vignesh E for Rtrack ID EPE-34128 ends here */
		
	if @pymt_date < @cur_date
	Begin
		if @albkdt = 'No'
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end	
		else 
		if @albkdt = 'CSH' and @pymt_type NOT IN ('C')
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end
		else
		if @albkdt = 'BNK' and @pymt_type NOT IN ('B')
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end
		else
		if @albkdt = 'BNKCSH' and @pymt_type NOT IN ('C','B')
		begin
			-- raiserror ('Pay Date should be equal to the System Date', 16, 1)
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,50,'','','','','','','',@errmsg output 
			return
		end
/* Code changes by Vignesh E for Rtrack ID EPE-34128 starts here */
		if ((DATEDIFF(day, @pymt_date, @cur_date)>@Backdated_value) )
		Begin
			--Back Dated Payments allowed only for %a days. Modify Pay Date.
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,102,@Backdated_value,'','','','','','',@errmsg output
			return
		End
/* Code changes by Vignesh E for Rtrack ID EPE-34128 ends here */
	End
		
	/* Code added by Pusba Prasanaa.B.R. for defect id: ES_cps_00008 ends here */
	
	/* Code added for DTS Id: 9H123-1_SPY_00026 Begins Here */
	SELECT 	@lo 		= lo_id
	FROM   	emod_lo_bu_ou_vw
	WHERE  	ou_id 		= @ctxt_ouinstance
	AND    	dbo.RES_Getdate(@ctxt_ouinstance) BETWEEN effective_from 
			AND ISNULL(effective_to, dbo.RES_Getdate(@ctxt_ouinstance))
	/* Code added for DTS Id: 9H123-1_SPY_00026 Ends Here */

	select 	@status_tmp 	= status
	from 	spy_paybatch_hdr(nolock)
	where 	paybatch_no 	= @paybatchnumberml 
	and 	ou_id 		= @ctxt_ouinstance

	if @status_tmp <> 'F'
	begin
                --raiserror('Paybatch is not in Fresh status . To Authrise Paybatch In Draft or Returned Please  Go to Next Page',16,1)
                select @m_errorid = 3690908
		return
	end

	if not exists
		(
		select 	'X'
		from 	spy_paybatch_hdr(nolock)
		where 	timestamp 	= @timestamp1
		and 	paybatch_no 	= @paybatchnumberml
		and 	ou_id 		= @ctxt_ouinstance
		)
	begin
		--raiserror('Paybatch has been modified by another user',16,1)
		select @m_errorid = 514
		return
	end

	select 	@compcode_tmp	= company_code
	from 	emod_ou_vw(nolock)
	where 	ou_id	= @ctxt_ouinstance

	select 	@basecurrencycode_tmp =	currency_code
	from	emod_basecurr_vw(nolock)
	where 	company_code 	= @compcode_tmp
	and 	flag 		= 'B'

	select  @exchangeratetype_tmp = ltrim(rtrim(parameter_value))
	from 	ops_processparam_vw (nolock)
	where 	ou_id 			= @ctxt_ouinstance
	and 	parameter_code 		= 'SETTLEMENTERTYPE'
	and 	parameter_type		= 'PMSYS'

	select 	@unadjppchk_flag = parameter_code 
	from 	fin_quick_code_met (nolock)
	where 	component_id 		= 'SPY'
	and 	parameter_type 		= 'COMBO'
	and 	parameter_category 	= 'ACUNADPPYMT'
	and 	parameter_text 		= @PrepaymentsCheck
	and 	language_id 		= @ctxt_language

	select	@voucher_type = voucher_notype
			,@unadjdebitchk_flag	=	isnull(unadjdebitchk_flag,'I')	--Code added for Defect ID 12H124_SPY_00007
	from	spy_paybatch_hdr(nolock)
	where	ou_id 		= @ctxt_ouinstance 
	and 	paybatch_no 	= @paybatchnumberml
	
	
	/*code added for the dtsid:9H123-1_SPY_00026 starts here*/
	if @paydateml > @date_tmp
	begin	
		if EXISTS(
		   select 'X'
		   from   cps_processparam_sys(NOLOCK)
		   where  company_code				= @compcode_tmp
				  AND parameter_type		= 'PMSYS'
				  AND parameter_category	= 'PDCPV'
				  AND parameter_code		= 'N'
				)
		begin
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,1212
			return
		end
	
	if EXISTS(
				select 'X' 
				from  supp_spmn_suplmain (nolock)
				where supp_spmn_supcode = @supplierml
				and	  supp_spmn_suptype = 'OT'
				and	  supp_spmn_loid	= @lo
				
				 )
			begin
				exec fin_german_raiserror_sp 'SPY',@ctxt_language,1222,@fprowno
				return
			end
	end
	/*code added for the dtsid:9H123-1_SPY_00026 ends here*/
	--Added for ES_bnkdef_00048:11h103_spy_00047 starts
	declare @bankcashtmp	fin_bankcashcode
				
	select 	@compcode 	= company_code
	from 	emod_ou_vw(nolock)
	where 	ou_id 	= @ctxt_ouinstance
	and 	dbo.fin_getdatepart(dbo.RES_Getdate(@ctxt_ouinstance)) between effective_from 
			and isnull(effective_to,'01-01-9999')
	
	if  exists(	select	'x'
				from	spy_pb_bankpayamount_dtl,
						Bnkdef_user_bank_map(nolock)
				where	paybatch_no	=	@paybatchnumberml
				and		ou_id		=	@ctxt_ouinstance
				and		CompanyCode	=	@compcode
				and		OU			=	ou_id
				and		UserName	=	@ctxt_user
				and		TranType	=	'SPY'
				and		bank_cash_code	=	bankcode)
	begin
				select	@bankcashtmp	=	bank_cash_code
				from	spy_pb_bankpayamount_dtl,
						Bnkdef_user_bank_map(nolock)
				where	paybatch_no		=	@paybatchnumberml
				and		ou_id			=	@ctxt_ouinstance
				and		CompanyCode		=	@compcode
				and		OU				=	ou_id
				and		UserName		=	@ctxt_user
				and		TranType		=	'SPY'
				and		bank_cash_code	=	bankcode
				
		exec	fin_german_raiserror_sp 'SPY',@ctxt_language,5051,@bankcashtmp
		return
	end
	--Added for ES_bnkdef_00048:11h103_spy_00047 ends
	


	/* Code Added By selvan G for the Bug Id : 8H123-1_spy_00025 starts here */
	insert into spy_paybatch_hdr_tmp
		(guid,ou_id,paybatch_no,pay_date,timestamp,fb_id,request_date,pay_currency,basecur_erate,tran_type)--EPE-79085
	select 	@guid,ou_id,paybatch_no,pay_date,1,fb_id,request_date,pay_currency,basecur_erate,tran_type--EPE-79085
	from	spy_paybatch_hdr(nolock)
	where	paybatch_no     = @paybatchnumberml
	and	ou_id 		= @ctxt_ouinstance

	insert into spy_paybatch_dtl_tmp(
		/*Code commented and added for Defect ID 12H124_SPY_0007 starts here*/
		--guid,ou_id,paybatch_no,cr_doc_ou,cr_doc_no,term_no,tran_type,
		guid,ou_id,paybatch_no,cr_doc_ou,cr_doc_no,term_no,tran_type,supplier_code,
		cr_doc_type,timestamp,supp_ctrl_acct,supp_acc_no)
	--select	@guid,ou_id,paybatch_no,cr_doc_ou,cr_doc_no,term_no,tran_type,
	select	@guid,ou_id,paybatch_no,cr_doc_ou,cr_doc_no,term_no,tran_type,supplier_code,
		/*Code commented and added for Defect ID 12H124_SPY_0007 ends here*/
		cr_doc_type,1,supp_ctrl_acct,ctrl_acct_type
	from	spy_paybatch_dtl( nolock)
	where	paybatch_no     = @paybatchnumberml
	and	ou_id		= @ctxt_ouinstance
	
	/* Code Added By selvan G for the Bug Id : 8H123-1_spy_00025 Ends here */

	declare Voucher_num_gen cursor static for     
	select 	paybatch_no,voucher_no
	from 	spy_voucher_hdr(nolock)
	where 	ou_id 		= @ctxt_ouinstance 
	and 	paybatch_no 	= @paybatchnumberml    
	
	open Voucher_num_gen    

	fetch next from Voucher_num_gen into @paybatch_no,@voucher_no

	while @@fetch_status = 0    
	begin    
		exec 	spy_spnumgeneration
			@ctxt_language,@ctxt_ouinstance,'S',@ctxt_user,
			@voucher_type,'PV',@paydateml, --Aparna M. 8H123-1_spy_00001
			@voucher_tmp out,@errno OUT    

		if @errno > 0 or @voucher_tmp is null
		begin 
			-- Voucher Number Can not be generated,Change Voucher No Type
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,4
			close 	Voucher_num_gen    
			deallocate Voucher_num_gen    
			return 18    
		end
		
		insert into spy_voucher_hdr( 
			ou_id,paybatch_no,voucher_no,timestamp,voucher_amount,
			vouch_amt_bef,roundoff_amt,exchange_rate,par_exchange_rate,
			pay_currency,payee,pay_mode,bank_cash_code,priority,
			dd_charges,status,supp_receipt_no,receipt_date,
			reason_code,hld_reason_code,hld_remarks,rev_remarks,
			rev_date,batch_id,supp_acct_in,supp_bank_ref,supp_acc_no,
			esr_line,lsv_id,createdby,createddate,modifiedby,modifieddate,
			/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 begins here*/
			be_amount,				be_amount_base,					be_percent,						be_currency,
			be_duedate,				be_boeno,						be_flag,						be_issuedat,
			/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 ends here*/
			request_date,supplier_code)	--Code added by vijayan.j for the bug id:RPDMS412AT_000248
		select 	ou_id,paybatch_no,@voucher_tmp,timestamp,voucher_amount,
			vouch_amt_bef,roundoff_amt,exchange_rate,par_exchange_rate,
			pay_currency,payee,pay_mode,bank_cash_code,priority,
			dd_charges,case when pay_mode = 'OT' then 'PA'
				   	else	'RE' end,
			supp_receipt_no,receipt_date,reason_code,hld_reason_code,
			hld_remarks,rev_remarks,rev_date,@guid,supp_acct_in,
			supp_bank_ref,supp_acc_no,esr_line,lsv_id,createdby,
			createddate,modifiedby,modifieddate,
			/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 begins here*/
			be_amount,				be_amount_base,					be_percent,						be_currency,
			be_duedate,				be_boeno,						be_flag,						be_issuedat,
			/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 ends here*/
			request_date,supplier_code	--Code added by vijayan.j for the bug id:RPDMS412AT_000248
		from 	spy_voucher_hdr(nolock)
		where 	ou_id		= @ctxt_ouinstance 
		and 	voucher_no	= @voucher_no
		
		update 	spy_voucher_dtl with (rowlock)
		set 	voucher_no 	= @voucher_tmp,
			batch_id	= @guid
		where 	paybatch_no 	= @paybatch_no
		and 	voucher_no 	= @voucher_no

		/* Code Added and commented By selvan G for the Bug Id : 8H123-1_spy_00025 starts here */
		select	@bank_cash_code	= bank_cash_code
		from	spy_voucher_hdr (nolock)
		where	paybatch_no	= @paybatchnumberml	
		and	ou_id		= @ctxt_ouinstance
		and	voucher_no	= @voucher_tmp

		/*code added for the dts id 11H103_spy_00010:11H103_spy_00037 starts*/
		declare @pay_currency   fin_currencycode,
				@bank_currency	fin_currencycode,
				@basecur_erate  fin_exchangerate
	
		select 	@pay_currency = pay_currency,  
				@basecur_erate = basecur_erate
		from	spy_paybatch_hdr(nolock)
		where	paybatch_no     = @paybatchnumberml
		and		ou_id 			= @ctxt_ouinstance
		--EPE-79558:EPE-81543
		if isnull(@pay_currency,'') =''
		begin
			select 	@pay_currency = pay_currency,  
					@basecur_erate = pay_cur_erate
			from	spy_paybatch_dtl(nolock)
			where	paybatch_no     = @paybatchnumberml
			and		ou_id 			= @ctxt_ouinstance

		end
		--EPE-79558:EPE-81543
		select @bank_currency	 = currency_code  
		from bnkdef_sysact_bnkcshptt_vw (nolock) 
		where company_code	=	@compcode_tmp	
		and bank_cash_code	= 	@bank_cash_code 
		and language_id		= 	@ctxt_language
		
		/*code added for the dts id 11H103_spy_00010:11H103_spy_00037 ends */

		insert into spy_genvoucher_tmp
			   (voucher_no,		    cr_doc_fb_id,		    cr_doc_erate,	cr_doc_parbase_erate,
			    cr_doc_amount,	    tran_net_amount,		    cr_doc_cur,		discount,
			    penalty,		    pay_amount,			    bank_cash_code,	cr_doc_type,
			    cr_doc_no,		    cr_doc_ou,			    term_no ,		guid,
			    line_no,		    timestamp
				,pay_currency,		bank_currency ,	pay_cur_erate --code added for the dts id 11H103_spy_00010:11H103_spy_00037
			    )
		select	     @voucher_tmp ,	    A.cr_doc_fb_id,		    A.basecur_erate,	A.parbasecur_erate ,
			    /* A.cr_doc_amount */B.cr_doc_amount,	    isnull(A.tran_net_amount,0),    A.cr_doc_cur,	isnull(B.discount,0),
			    isnull(A.penalty,0),    A.pay_amount,		    @bank_cash_code,	A.cr_doc_type,
			    A.cr_doc_no,	    A.cr_doc_ou,		    B.term_no ,		@guid  ,
			    cr_doc_line_no,	    1	    
				,@pay_currency,		@bank_currency ,@basecur_erate --code added for the dts id 11H103_spy_00010:11H103_spy_00037
		from	    spy_paybatch_dtl (nolock) A ,spy_voucher_dtl B(nolock)
		where	    A.paybatch_no 	= @paybatch_no
		and	    A.ou_id		= @ctxt_ouinstance 
		and	    B.paybatch_no	= A.paybatch_no
		and	    B.voucher_no	= @voucher_tmp
		and	    B.ou_id		= A.ou_id
			/* Code added for the dts id 11H103_spy_00044:11H103_spy_00045 starts */
		and B.cr_doc_ou = A.cr_doc_ou
		and B.cr_doc_no = A.cr_doc_no
		and B.cr_doc_type = A.cr_doc_type
		and B.term_no  = A.term_no		
		/* Code added for the dts id 11H103_spy_00044:11H103_spy_00045 ends*/

		delete	from	spy_acct_info_dtl
		where 	tran_no  	= @voucher_no
		and 	ou_id	 	= @ctxt_ouinstance 
		and	component_name	<> 'TCAL'

		exec	spy_posting_advancedpaybatch @guid, @ctxt_ouinstance, @ctxt_user,@ctxt_language,@bankcash_out ,
			@accountcode_out, @event_out, @usage_out, @fbid_out, @currency_out, @errormsg_out out , @errno out
	
		if @errno <> 0 or @errormsg_out is not null
		begin
			select	@m_errorid	=   case 
							when isnull(@errno,0) = 0 and @errormsg_out is not null then 99 
							else @errno 
						    end
			close Voucher_num_gen    
			deallocate Voucher_num_gen
			return
		end


		delete from spy_genvoucher_tmp
		where guid  =	@guid
		
		
		update 	spy_acct_info_dtl  with (rowlock)
		set 	tran_no	 	= @voucher_tmp ,    
			batch_id 	= @guid
		where 	tran_no  	= @voucher_no
		and 	ou_id	 	= @ctxt_ouinstance 
		and	component_name	= 'TCAL' --selvan G 8H123-1_spy_00025
		
		/*update 	spy_acct_info_dtl  with (rowlock)
		set 	tran_no	 	= @voucher_tmp ,    
			batch_id 	= @guid
		where 	tran_no  	= @voucher_no
		and 	ou_id	 	= @ctxt_ouinstance */
		/* Code Added and commented By selvan G for the Bug Id : 8H123-1_spy_00025 ends here */

		insert into tcal_tran_hdr(
			tran_no,tax_type,tran_type,tran_ou,tax_community,tran_date,
			applicable_flag,company_code,buid,fbid,tran_curr,incl_option,
			tax_excl_amt,tax_incl_amt,tran_amt,comp_tax_amt,corr_tax_amt,
			party_type,supp_cust_code,assessee_type,cap_deduct_charge,
			bas_exch_rate,pbas_exch_rate,comp_tax_amt_bascurr,
			corr_tax_amt_bascurr,nontax_tc_amt,nontax_disc_amt,
			component_name,original_tran_no,reversed_tran_no,doc_status,
			tax_status,tax_adj_status,cert_recd_status,dr_cr_flag,usage_id,
			trade_type,tax_on,addnl_param1,addnl_param2,addnl_param3,
			addnl_param4,created_at,created_by,created_date,modified_by,
			modified_date,timestamp,receipt_type,tax_amt_invoiced)
		select	@voucher_tmp,tax_type,tran_type,tran_ou,tax_community,tran_date,
			applicable_flag,company_code,buid,fbid,tran_curr,incl_option,
			tax_excl_amt,tax_incl_amt,tran_amt,comp_tax_amt,corr_tax_amt,
			party_type,supp_cust_code,assessee_type,cap_deduct_charge,
			bas_exch_rate,pbas_exch_rate,comp_tax_amt_bascurr,
			corr_tax_amt_bascurr,nontax_tc_amt,nontax_disc_amt,
			component_name,original_tran_no,reversed_tran_no,doc_status,
			tax_status,tax_adj_status,cert_recd_status,dr_cr_flag,usage_id,
			trade_type,tax_on,addnl_param1,addnl_param2,addnl_param3,
			addnl_param4,created_at,created_by,created_date,modified_by,
			modified_date,timestamp,receipt_type,tax_amt_invoiced
		from	tcal_tran_hdr(nolock)
		where	tran_no		= @voucher_no
		and	tran_ou		= @ctxt_ouinstance 

		insert 	into tcal_tax_hdr(
			tran_no,tax_type,tran_type,tran_ou,tran_line_no,own_tax_region,
			own_regd_no,party_tax_region,party_regd_no,decl_tax_region,
			tax_category,tax_class,tax_register,tax_reference,ref_doc_type,
			ref_doc_no,ref_doc_ou,item_tc_type,item_tc_usage_id,item_tc_variant,
			distrib_charge,distrib_disc,tax_uom,quantity,basic_amt,stat_tax,
			tc_amt,disc_amt,taxable_amt,taxable_perc,nontax_tc_amt,
			nontax_disc_amt,comp_tax_amt,corr_tax_amt,comp_tax_amt_bascurr,
			corr_tax_amt_bascurr,ded_tax_amt,ded_tax_amt_bascurr,dr_cr_flag,
			addnl_param1,addnl_param2,addnl_param3,addnl_param4,created_by,
			created_date,modified_by,modified_date,tax_excl_amt,tax_incl_amt,
			ref_doc_line_no,tax_community,taxable_amt_base,warehouse,
			tds_tran_amt)
		select	@voucher_tmp,tax_type,tran_type,tran_ou,tran_line_no,own_tax_region,
			own_regd_no,party_tax_region,party_regd_no,decl_tax_region,
			tax_category,tax_class,tax_register,tax_reference,ref_doc_type,
			ref_doc_no,ref_doc_ou,item_tc_type,item_tc_usage_id,item_tc_variant,
			distrib_charge,distrib_disc,tax_uom,quantity,basic_amt,stat_tax,
			tc_amt,disc_amt,taxable_amt,taxable_perc,nontax_tc_amt,
			nontax_disc_amt,comp_tax_amt,corr_tax_amt,comp_tax_amt_bascurr,
			corr_tax_amt_bascurr,ded_tax_amt,ded_tax_amt_bascurr,dr_cr_flag,
			addnl_param1,addnl_param2,addnl_param3,addnl_param4,created_by,
			created_date,modified_by,modified_date,tax_excl_amt,tax_incl_amt,
			ref_doc_line_no,tax_community,taxable_amt_base,warehouse,
			tds_tran_amt
		from	tcal_tax_hdr(nolock)
		where	tran_no		= @voucher_no
		and	tran_ou		= @ctxt_ouinstance 

		update 	tcal_tax_dtl with (rowlock)
		set 	tran_no 	= @voucher_tmp
		where 	tran_no 	= @voucher_no
		and	tran_ou		= @ctxt_ouinstance 

		update 	tcal_tax_postings with (rowlock)
		set 	tran_no 	= @voucher_tmp
		where 	tran_no 	= @voucher_no
		and	tran_ou		= @ctxt_ouinstance 

		update 	tcal_tran_summary with (rowlock)
		set 	tran_no 	= @voucher_tmp
		where 	tran_no 	= @voucher_no
		and	tran_ou		= @ctxt_ouinstance 

		delete 	from spy_voucher_hdr
		where 	ou_id		= @ctxt_ouinstance
		and 	voucher_no	= @voucher_no
		and 	paybatch_no	= @paybatch_no

		delete 	from tcal_tax_hdr
		where 	tran_ou		= @ctxt_ouinstance
		and 	tran_no		= @voucher_no

		delete 	from tcal_tran_hdr
		where 	tran_ou		= @ctxt_ouinstance
		and 	tran_no		= @voucher_no

		fetch next from Voucher_num_gen into @paybatch_no,@voucher_no
	end    
	close Voucher_num_gen    
	deallocate Voucher_num_gen

	/* Code Added By Selvan G For the Bug Id : 8H123-1_spy_00025 starts here */
	--Fbpposting Validation sp
	/*exec 	fbp_is_loc_sptrnpostings
		@ctxt_language,@ctxt_ouinstance,'spyadrpmnsrcreate',
		@ctxt_user,@guid,@errno output,@errdesc output,'N'

	if @errno > 0 
	begin
 		exec  fin_fbp_error_handle @ctxt_language,@errno,@errdesc
		return
	end*/
	/* Code Added By Selvan G For the Bug Id : 8H123-1_spy_00025 Ends here */
	
	/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 begins here*/
	if @ctxt_service = 'SPYAuApEnSrBlkAut'
	begin
		declare cur_vou cursor static static for     
		select 	paybatch_no,voucher_no 
		from 	spy_voucher_hdr(nolock)
		where 	ou_id 		= @ctxt_ouinstance 
		and 	paybatch_no = @paybatchnumberml    
		
		open cur_vou    

		fetch next from cur_vou into @pbnum_tmp,@vnonew_tmp    

		while @@fetch_status = 0    
		begin 
			select 	@be_flag		= 	be_flag,
					@bankcode		= 	bank_cash_code,
					@be_boeno		= 	be_boeno,
					@be_amount		=	be_amount,
					@be_amount_base	=	be_amount_base,
					@be_percent		=	be_percent,
					@be_currency	=	be_currency,
					@be_duedate		=	be_duedate,
					@be_issuedat	=	be_issuedat
			from 	spy_voucher_hdr(nolock)
			where 	ou_id 			= 	@ctxt_ouinstance 
			and 	paybatch_no 	= 	@paybatchnumberml 		
			and		voucher_no		= 	@vnonew_tmp
			
			select 	@fb_id		= fb_id
			from 	spy_paybatch_hdr(nolock)
			where 	ou_id 		= @ctxt_ouinstance 
			and 	paybatch_no = @paybatchnumberml 	
		
			if @be_flag	=	1
			begin
				select 	@totalpayamount = sum(isnull(pay_amount,0)) 
				from 	spy_paybatch_dtl(nolock)
				where 	ou_id 			= @ctxt_ouinstance 
				and 	paybatch_no 	= @paybatchnumberml 		
			 	
	 			select  @eratetype		=	ltrim(rtrim(parameter_value))  
				from  	ops_processparam_vw (nolock)  
				where  	ou_id    		=	@ctxt_ouinstance  
				and  	parameter_code  =	'SETTLEMENTERTYPE'  
				and  	parameter_type  =	'PMSYS'
			 	
	 			if @pay_currency <> @be_currency
	 			begin
					exec 	@retcode_tmp = erate_sysact_spgetexcgrate
							@ctxt_ouinstance,@ctxt_user,@ctxt_language,
							@pay_currency,@be_currency,@pymt_date,@eratetype, 
							@paybecur_erate out,@maxtollimit out,@mintollimit out,'','','SPY'  	 	
							
					select	@totalpayamount	=	@totalpayamount*@paybecur_erate	
				end	
				
				if @basecur <> @be_currency
	 			begin
					exec 	@retcode_tmp = erate_sysact_spgetexcgrate
							@ctxt_ouinstance,@ctxt_user,@ctxt_language,
							@be_currency,@basecur,@pymt_date,@eratetype, 
							@bebasecur_erate out,@maxtollimit out,@mintollimit out,'','','SPY'  	 	
							
					select	@be_amount_base	=	isnull(@be_amount,(@totalpayamount*@be_percent)/100)*@bebasecur_erate	
				end	
				else
				begin
					select	@bebasecur_erate = 1
					select	@be_amount_base	=	isnull(@be_amount,(@totalpayamount*@be_percent)/100)
				end	

				
				select @be_amount	=	isnull(@be_amount,(@totalpayamount*@be_percent)/100)
				
				update 	spy_paybatch_hdr_tmp
				set		be_amount_base	=	@be_amount_base,
						be_amount		=	@be_amount
				where 	guid			=	@guid	
				
				update 	spy_voucher_hdr_tmp
				set		be_amount		=	@be_amount,
						be_amount_base	=	@be_amount_base,
						be_percent		=	@be_percent,
						be_currency		=	@be_currency,
						be_duedate		=	@be_duedate,
						be_boeno		=	@be_boeno,
						be_flag			=	@be_flag,
						be_issuedat		=	@be_issuedat
				where 	guid			=	@guid
				
				select	@surdate		=	isnull(@pymt_date,@date_tmp),
						@transactionou	=	@ctxt_ouinstance
			
				select 	@receiptcategory  	=	parameter_text
				from 	fin_quick_code_met ( nolock )
				where 	component_id 		= 	'SUR'
				and 	parameter_type 		= 	'CBO'
				and 	parameter_category	= 	'RPTCAT'
				and		parameter_code		= 	'R'
				and		language_id			= 	@ctxt_language
				
				select	@receiptmethod 			= rcpt_pymt_method 
				from	bnkdef_rcpt_pay_method_vw (nolock)
				where 	rcpt_pymt_method_code	= 'RGLR'
				and 	language_id  			= @ctxt_language	

				select	@receiptmode 			= rcpt_pymt_mode 
				from	bnkdef_rcpt_pay_mode_vw (nolock)
				where 	rcpt_pymt_mode_code		= 'OT'
				and 	language_id  			= @ctxt_language	
				
				select	@receiptroute			=  rcpt_pymt_route
				from	bnkdef_rcpt_pay_route_vw (nolock)
				where 	rcpt_pymt_route_code 	= 'B'
				and 	language_id  			= @ctxt_language
				
				select	@bankdescription 	=	bank_desc
				from	bnkdef_code_mst(nolock)
				where	bank_code			= @bankcode
				and		company_code		= @compcode	
			
				select @sur_guid = newid()	
				
				select @remitter	=	'Auto-generated from '+	@pbnum_tmp

				select	@boe_account	=	boe_account
				from	ard_boe_buycr_account (nolock)
				where	company_code	=	@compcode
				and		fb_id			=	@fb_id
				and		bankcode		=	@bankcode
				and		currency_code	=	@be_currency
				and		@surdate		between	be_effective_from and isnull(be_effective_to,'01-01-9999')	
				
				if isnull(@boe_account,'') = ''
				begin
					--Account Code not defined for Bill of Exchange Liability Account. Define Account code in Account Rule Definition and Proceed.
					exec fin_german_raiserror_sp 'SPY',@ctxt_language,1518
					close 		cur_vou    
					deallocate 	cur_vou  
					return 1
				end
				
				select	@costcenter		=   ltrim(rtrim(center_no))
				from 	mac_acc_ce_cc_mapping (nolock)
				where 	account_no		=	@boe_account
				and		bu_id			=	@buid_tmp
				and		@surdate between effective_date	and isnull(expiry_date,'01-01-9999')	
				
				if	exists	(	select	'x'
								from	abb_account_analysis_map(nolock)
								where	company_code			=	@compcode
								and		account_code			=	@boe_account
								and		default_analysis_code	=	'Y'
								and		map_status				=	'A'
							)
				begin
					select	top 1 @analysiscode		=	analysis_code,
							@subanalysiscode		=	sub_analysis_code
					from	abb_account_analysis_map(nolock)
					where	company_code			=	@compcode
					and		account_code			=	@boe_account
					and		default_analysis_code	=	'Y'
					and		map_status				=	'A'		
				end
				else	if	exists	(	select	'x'
										from	abb_account_analysis_map(nolock)
										where	company_code			=	@compcode
										and		account_code			=	@boe_account
										and		default_analysis_code	=	'N'
										and		map_status				=	'A'
									)
				begin
					--Analysis code for the specified account code %s has to be defaulted
					exec fin_german_raiserror_sp 'CBA',@ctxt_language,285,@boe_account
					close 		cur_vou    
					deallocate 	cur_vou 
					return	1	
				end					

				insert into sur_is_voucher_dtl_tmp
				(
					guid,				account_code,				analysis_code,			Account_Amount, 
					cost_center,		currency_code,				drcr_flag,				exchangerate, 
					fb,					usage,						instrdate,				modeflag, 
					netcramount,		remarksml,					
					subanalysis_code,	fprowno 
				)
				values
				(	
					@sur_guid,			@boe_account,				@analysiscode,			@be_amount,
					@costcenter,		@be_currency,				'CR',					@bebasecur_erate,--@exchangerate,
					@fb_id,				NULL,						NULL,					NULL,
					@be_amount,			@be_boeno,
					@subanalysiscode,	1
				)	
											
				if Exists(	Select	'X'
							From	sur_is_voucher_dtl_tmp(nolock)
							where	guid	=	@sur_guid
						 )
				Begin							
					exec	sur_is_autogensp--abrreconspsavehchk1
							'~#~',--@authorizationnumber,
							@bankcode,
							@bankcode,
							@bankdescription,
							-915,--@calendaryear
							'~#~',--@cardnumber
							@date_tmp,--@createddate
							@ctxt_user,--@creationby
							@ctxt_language,
							@transactionou,--@ctxt_ouinstance,
							@ctxt_service,
							@ctxt_user,
							@be_currency,
							@bebasecur_erate,--@exchangerate,
							@fb_id,
							'~#~',---915,--@finmonth
							@sur_guid,
							-915,--@instramt
							'01/01/1900',--@instrdate
							'~#~',--@instrumentnumber
							'~#~',--@issuer
							'~#~',--@micrnumber
							@be_amount,
							NULL,--@notypeno,
							@be_amount,
							@receiptcategory,
							@surdate,
							@receiptmethod,
							@receiptmode,
							'~#~',--@receiptnumber,
							@receiptroute,
							@pbnum_tmp,--@referencedocumentnumber
							'Receipt of Bill of Exchange Loan',--@remarks
							@remitter,--@remittername
							'~#~',--@rptstatus
							-915,--@timestamp
							'Y',--@fbp_calling_mode
							'~#~',--@instrumenttype
							@m_errorid	 OUTPUT			
							
							if @m_errorid <> 0
							begin
								--Error in Sundry Receipt Autogeneration for Bill of Exchange.
								exec fin_german_raiserror_sp 'SPY',@ctxt_language,1513
								close 		cur_vou    
								deallocate 	cur_vou		
								return	1	
							end
						
							select 	@sundryreceiptvoucher = ReceiptNumber
							from sur_is_voucher_dtl_tmp (nolock)
							where guid = @sur_guid
							
							update	sur_receipt_hdr 
							set		auto_gen_flag	=	'Y'
							Where	receipt_no		=	@sundryreceiptvoucher
							and		Ou_id			=	@transactionou	
							
							update	spy_voucher_hdr
							set 	receipt_no	= @sundryreceiptvoucher
							WHERE	ou_id 		= @ctxt_ouinstance
							AND		voucher_no	= @voucher_tmp
							
							UPDATE tmp
							SET    receipt_no = hdr.receipt_no
							FROM   spy_paybatch_dtl_tmp tmp(NOLOCK),   
								   spy_voucher_DTL dtl	(NOLOCK),
 								   spy_voucher_hdr hdr (NOLOCK)
							WHERE  tmp.guid		 	= @guid
							and	   tmp.cr_doc_ou 	= dtl.cr_doc_ou
							AND    tmp.cr_doc_no 	= dtl.cr_doc_no
							AND    tmp.term_no 	 	= dtl.term_no
							AND    tmp.tran_type 	= dtl.cr_doc_type
							AND    tmp.ou_id 	 	= dtl.ou_id
							and    tmp.paybatch_no	= dtl.paybatch_no 
							AND    dtl.paybatch_no  = hdr.paybatch_no
							AND    dtl.voucher_no   = hdr.voucher_no
							AND    dtl.ou_id 	    = hdr.ou_id

							delete sur_is_voucher_dtl_tmp 
							where guid = @sur_guid
				end	--if Exists(	Select	'X' From	sur_is_voucher_dtl_tmp(nolock)		
			end	--if @be_flag	=	1
			
			fetch next from cur_vou into @pbnum_tmp,@vnonew_tmp    /*Code added for ITS Id : ES_spy_01569*/
						
		END --while @@fetch_status = 0
		
		/*Code added for ITS Id : ES_spy_01569 starts*/
		close 		cur_vou    
		deallocate 	cur_vou  
		/*Code added for ITS Id : ES_spy_01569 ends*/
	
	end	--if @ctxt_service = 'SPYAuApEnSrBlkAut'
	/*Code added for 14H109_GENERAL_00059:14H109_spy_00046 ends here*/

	if @ctxt_service in ('spyauapensrblkaut')
	begin
		if @unadjppchk_flag in ('H','W')
		begin
			exec 	sispyisvalppchksp
				@ctxt_ouinstance,@ctxt_user,@ctxt_language,@ctxt_service,
				'','',@guid,@paybatchnumberml,@paybatchnumberml,'',''
				,'','','','','','',@flag_out output,@m_errorid output
	
			/*Code commented for Defect ID 12H124_SPY_00007 starts here*/
			/*	
			if @unadjppchk_flag in ('H')
			begin
				if @flag_out = 'Y'
				begin
					exec fin_sp_raise_error '','','','','SPY',39302142,@m_errorid output  --For German Bank Implementation
					return
				end
			end
	
			update	spy_paybatch_hdr
			set 	unadjppchk_flag = @flag_out
			where	paybatch_no	= @paybatchnumberml
			and	ou_id		= @ctxt_ouinstance
			*/
			/*Code commented for Defect ID 12H124_SPY_00007 ends here*/
		end

		/*Code added for Defect ID 12H124_SPY_00007 starts here*/
		if @unadjdebitchk_flag in ('H','W')
		begin
			exec spyciunadjdebitchksp	@ctxt_ouinstance,
										@ctxt_user,
										@ctxt_language,
										@ctxt_service,
										@paybatchnumberml,
										@guid,
										@paydateml,
										@debitflag_out	output,
										@supp_count		output,
										@culist			output,
										@sulist			output,
										@m_errorid		output
		end

		if (@unadjppchk_flag = 'H' and @flag_out = 'Y') and (@debitflag_out = 'N' or (@unadjdebitchk_flag = 'W' and @debitflag_out = 'Y') or @unadjdebitchk_flag = 'I')
		begin
			--Unadjusted Prepayments exist for the Supplier Codes included in the Pay Batch No. "%a" at row no. %b
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,1081,@paybatchnumberml,@fprowno
			return
		end

		if (@unadjdebitchk_flag = 'H' and @debitflag_out = 'Y') and (@flag_out = 'N' or (@unadjppchk_flag = 'W' and @flag_out = 'Y') or @unadjppchk_flag = 'I')
		begin
			--Unadjusted Debit Documents exist for customer(s) mapped to supplier(s) in the Pay Batch No. "%a" at row no. %b
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,1082,@paybatchnumberml,@fprowno
			return
		end

		if (@unadjppchk_flag = 'H' and @flag_out = 'Y') and (@unadjdebitchk_flag = 'H' and @debitflag_out = 'Y')
		begin
			--Unadjusted Prepayments exist for the Supplier Codes and Unadjusted Debit Documents exist for customer(s) mapped to supplier(s) in the Pay Batch No. "%a" at row no. %b
			exec fin_german_raiserror_sp 'SPY',@ctxt_language,1083,@paybatchnumberml,@fprowno
			return
		end

		if @unadjppchk_flag = 'I'
		begin
			select	@flag_out = 'N'
		end

		if @unadjdebitchk_flag = 'I'
		begin
			select	@debitflag_out = 'N'
		end

		update	spy_paybatch_hdr_tmp
		set		unadjppchk_flag			=	@unadjppchk_flag,
				unadjexist_flag			=	@flag_out,
				unadjdebitchk_flag		=	@unadjdebitchk_flag,
				unadjdebitexist_flag	=	@debitflag_out
		where	paybatch_no				= 	@paybatchnumberml
		and		ou_id					= 	@ctxt_ouinstance
		and		guid					=	@guid
		/*Code added for Defect ID 12H124_SPY_00007 ends here*/
	end
	/* Code commented By selvan G for the Bug Id : 8H123-1_spy_00025 starts here */
	/*insert into spy_paybatch_hdr_tmp
		(guid,ou_id,paybatch_no,timestamp,pay_date)--Aparna M. 8H123-1_spy_00017
	select 	@guid,ou_id,paybatch_no,1,@paydateml --Aparna M. 8H123-1_spy_00017
	from	spy_paybatch_hdr(nolock)
	where	paybatch_no     = @paybatchnumberml
	and	ou_id 		= @ctxt_ouinstance

	insert into spy_paybatch_dtl_tmp(
		guid,ou_id,paybatch_no,cr_doc_ou,cr_doc_no,term_no,tran_type,
		cr_doc_type,timestamp)
	select	@guid,ou_id,paybatch_no,cr_doc_ou,cr_doc_no,term_no,tran_type,
		cr_doc_type,1
	from	spy_paybatch_dtl( nolock)
	where	paybatch_no     = @paybatchnumberml
	and	ou_id		= @ctxt_ouinstance*/
	/* Code Added and commented By selvan G for the Bug Id : 8H123-1_spy_00025 ends here */
	if @called_from	= 'MOB_APPR'--EPE-79558:EPE-81543
	begin		
		return
	end

	--14H109_mcam_00001
	if @called_from = 'NONE'
	begin
		select 	@errorno 	'errorno',
			@fprowno 	'fprowno',
			@placeholder1 	'placeholder1',
			@placeholder2 	'placeholder2',
			@placeholder3 	'placeholder3',
			@placeholder4 	'placeholder4',
			@successflag 	'successflag'
	end
	else
	begin
			update	mca_sel_doc_tmp
			set		error_id	= 0
			where	hdn_guid = @guid		
	end
	--14H109_mcam_00001
	set nocount off
end











